### ISSUE TITLE
Testnet `schema/websocketHelp` endpoint error

### ISSUE THREAD

**Issue by saulfautley** [BitMEX/api-connectors#100]
It looks like there's an error on:
https://testnet.bitmex.com/api/v1/schema/websocketHelp

It works fine on the live server:
https://www.bitmex.com/api/v1/schema/websocketHelp

This is causing the bitmex-realtime-api Node module to throw an error when using `testnet: true` because it checks the above endpoint to verify that the stream table exists. I assume the same issue will be seen on other WS connectors that do the same thing.

**Comment by STRML** [comment]
Thanks for the note. This is now fixed.
