### ISSUE TITLE
AttributeError: Resource 'Order' has no operation 'Order_get'

### ISSUE THREAD

**Issue by danielmogilny** [BitMEX/api-connectors#101]
Is client.Order.Order_get missing?

Python 3.5, swaggerpython API, installed via pip3

client = bitmex.bitmex(api_key=key , api_secret =secret)
client.Order.Order_get().result()

Error:

    print(client.Order.Order_get().result())
  File "/usr/local/lib/python3.6/site-packages/bravado/client.py", line 199, in __getattr__
    return CallableOperation(getattr(self.resource, name), self.also_return_response)
  File "/usr/local/lib/python3.6/site-packages/bravado_core/resource.py", line 108, in __getattr__
    (self.name, item))
AttributeError: Resource 'Order' has no operation 'Order_get'

**Comment by scoupafi** [comment]
You are probably referring to `Order_getOrders`.
`Order.Order_get()` does not exist as far as I know.
You can resolve the call names by visiting https://www.bitmex.com/api/explorer. After clicking on the name of a call your URL will be something along the lines of:
https://www.bitmex.com/api/explorer/#!/Order/Order_getOrders
which would result to a call like:
`order_result = client.Order.Order_getOrders(symbol = 'XBTUSD', ...).result()`

**Comment by danielmogilny** [comment]
Shouldn't it be called Order.Order_get() to be more consistent with Position.Position_get()?
