### ISSUE TITLE
Order.Order_newBulk causes stuck script

### ISSUE THREAD

**Issue by scoupafi** [BitMEX/api-connectors#102]
Greetings,
I've been calling 
`order_response = client.Order.Order_newBulk(orders = json.dumps(batch_orders)).result()`
where `batch_orders` is a list of dictionaries like:
`[{'symbol': 'XBTUSD', 'side': 'Buy', 'orderQty': 0.00075, 'price': 1000.0, 'ordType': 'Limit'}, {'symbol': 'XBTUSD', 'side': 'Buy', 'orderQty': 0.00075, 'price': 1333.3333333333333, 'ordType': 'Limit'}, {'symbol': 'XBTUSD', 'side': 'Buy', 'orderQty': 0.00075, 'price': 1666.6666666666665, 'ordType': 'Limit'}, {'symbol': 'XBTUSD', 'side': 'Buy', 'orderQty': 0.00075, 'price': 1999.9999999999998, 'ordType': 'Limit'}]`

My script will just stop without any response, not matter how long I wait.
Do you have any suggestions on this?

**Comment by scoupafi** [comment]
Could this be due to https://www.bitmex.com/app/restAPI#Order-Minimum-Size-Limits ?

My orders won't necessarily be over 0.0025 BTC.

**Comment by jaredpeck** [comment]
Have you been able to find a solution? I've been trying to work out this issue for a whole day now

**Comment by jaredpeck** [comment]
I got it to workout. Your prices have to be rounded to the nearest 0.5 decimal. 

price = round(price * 2) / 2

**Comment by scoupafi** [comment]
I will try it out.
Thanks.

**Comment by scoupafi** [comment]
My error was that I used orderQty instead of simpleOrderQty when appropriate.
Some related response error would be very useful.
