### ISSUE TITLE
[nodejs] full application crash when bitmex WS server is down

### ISSUE THREAD

**Issue by askmike** [BitMEX/api-connectors#103]
This lib crashes the complete application if it receives a 502 when trying to connect to the websocket. It doesn't happen often, I've only had this happen recently (after running for about a week).

    WebSocket [ERROR]: Unexpected response from server [502]: <html>
    <head><title>502 Bad Gateway</title></head>
    <body bgcolor="white">
    <center><h1>502 Bad Gateway</h1></center>
    </body>
    </html>

    WebSocket [ERROR]: Closing Websocket
    Error: WebSocket closed. Please check errors above.
        at WebSocketClient.wsClient.onend (/x/node_modules/bitmex-realtime-api/lib/createSocket.js:71:34)
        at WebSocket.instance.on (/x/node_modules/bitmex-realtime-api/lib/ReconnectingSocket.js:41:18)
        at emitOne (events.js:115:13)
        at WebSocket.emit (events.js:210:7)
        at IncomingMessage.response.on (/x/node_modules/bitmex-realtime-api/lib/ReconnectingSocket.js:69:27)
        at emitNone (events.js:110:20)
        at IncomingMessage.emit (events.js:207:7)
        at endReadableNT (_stream_readable.js:1059:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by scoupafi** [comment]
Just a quick reminder that 5xx errors generally mean a server outage. 
Maybe your were trying to connect at a period of heavy load and the server closed you out.

**Comment by askmike** [comment]
That is exactly what happened. When this lib is unable to connect it
handles the error gracefully and reconnects later. With the only exception
(I have encountered) being this situation that completely crashes my bot.

On 21 Mar 2018 20:39, "scoupafi" <notifications@github.com> wrote:

Just a quick reminder that 5xx errors generally mean a server outage.
Maybe your were trying to connect at a period of heavy load and the server
closed you out.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BitMEX/api-connectors/issues/103#issuecomment-374939446>,
or mute the thread

**Comment by ryanfox** [comment]
`502` indicates there was an error between a proxy and the application server, not server overload. There isn't necessarily anything to connect to - it's not equivalent to a traffic spike that may pass.

When the application comes back online, it will be in some unknown state - it would be up to individual applications to determine what they want to do with their positions.

**Comment by askmike** [comment]
> When the application comes back online, it will be in some unknown state - it would be up to individual applications to determine what they want to do with their positions.

This is always the case with a reconnect from the websocket: after it happens local state of my application is different from the server since I missed a ton of messages. However this lib always reconnects on connection errors (it doesn't really matter where they happen: on the network, in their internal network or their ws server). This is what this libs always does (except the above error):

    0|mm       | WebSocket [INFO]: Retry in 300 ms
    0|mm       | WebSocket [INFO]: Reconnecting...
    0|mm       | WebSocket [INFO]: Connected.

When that happens I already rebuild my local state. The issue is that the lib always reconnects fine, except with the above error.

**Comment by STRML** [comment]
We should be attempting to reconnect in this case, not crashing outright. Patches welcome, otherwise we'll take a look at it in the coming weeks.

**Comment by LooOOooM** [comment]
Please reopen, as the bug is still present:

WebSocket [ERROR]: WebSocket closed with code 1006
Connection closed.
WebSocket [INFO]: Retry in 1000 ms
WebSocket [INFO]: Reconnecting...
WebSocket [INFO]: Connected.
Connection opened.
{"op":"subscribe","args":"order:XBTUSD"}


response  : {
    "statusCode": 502,
    "body": "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</
body>\r\n</html>\r\n",
    "headers": {
        "server": "awselb/2.0",
        "date": "Thu, 06 Sep 2018 10:35:56 GMT",
        "content-type": "text/html",
        "content-length": "138",
        "connection": "close",
        "set-cookie": [
            "AWSALB=zILlOB+Uuf0eM1wQryYtaQU1GbDvPrjiAvtcjJLFpVdYWu+oexw/VJeyjQl2GWzMY04cA8dU5rs311uObDKWGm4HFC+qb+nIqSzVsmzj08I5XiSQfqV61nYfWhI1;
 Expires=Thu, 13 Sep 2018 10:35:56 GMT; Path=/"
        ]
    },
    "request": {
        "uri": {
            "protocol": "https:",
            "slashes": true,
            "auth": null,
            "host": "www.bitmex.com",
            "port": 443,
            "hostname": "www.bitmex.com",
            "hash": null,
            "search": null,
            "query": null,
            "pathname": "/api/v1/trade",
            "path": "/api/v1/trade",
            "href": "https://www.bitmex.com/api/v1/trade"
        },
        "method": "GET",
        "headers": {
            "content-type": "application/json",
            "Accept": "application/json",
            "X-Requested-With": "XMLHttpRequest",
            "api-expires": 1536230216038,
            "api-key": "SECRET!!",
            "api-signature": "SECRET!!",
            "content-length": 70
        }
    }
}




undefined:1
<html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/haxus/gordon/gekko/exchanges/bitmex.js:164:50)
    at Request.self.callback (/home/haxus/ gordon/gekko/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/haxus/ gordon/gekko/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/haxus/gordon/gekko/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
