### ISSUE TITLE
Can you add  WebSocket http proxy config for python?

### ISSUE THREAD

**Issue by kanghua1981** [BitMEX/api-connectors#106]
I want use the connectors in china.but I need proxy to connect bitmex.

**Comment by YbyRonaldo** [comment]
You can solve this problem by setting proxy in bitmex_websocket.py. Thanks to websocket package, it has params for proxies. 
        In line 118: self.wst = threading.Thread(target=lambda: self.ws.run_forever()) 
You can set your proxy config in function run_forever():
        run_forever(http_proxy_host,http_proxy_port,http_proxy_auth=['username','password'])
I hope this can help you! And I want to know how would you deal with your order operation ? Bitmex only provide order operation by using REST. And its swaggerClient examlpe is  also forbidden by GFW. I haven't found a correct way to set proxy config. Do you have any idea?

**Comment by kanghua1981** [comment]
@YbyRonaldo tks,I had solve the websocket problem by setting OS variables http_proxy and https_proxy.
but using REST can't connect bitmex.com now.  Maybe I need more time to solve it

**Comment by YbyRonaldo** [comment]
It seems that the SwaggerClient will change your HTTP settings to default when running. So even you've global proxy settings it can't connect either.And the bravado package it used doesn't provide params to set proxy. Write your own REST API client may be a solution what I'm doing now. Or you can rent a server outside the mainland to run your code.

**Comment by sxz1216** [comment]
hi,I am also in China.  when I pip install the package and tend to connect to websocket but it always timeout .I tried to use the method up but it seemed no use.Need your help.

**Comment by STRML** [comment]
I'm sorry, but we do not support proxying your traffic, and misrepresenting your county may be a violation of the [BitMEX Terms of Service](https://www.bitmex.com/app/terms).
