### ISSUE TITLE
How to query Maker fee and Ticker fee of order list

### ISSUE THREAD

**Issue by Doudada** [BitMEX/api-connectors#108]
https://testnet.bitmex.com/app/fees that's page description trading will produce maker fee and ticker fee.I trying query /order API ,but i not find fee.
that's my query result
`  {`
        "orderID": "",
        "clOrdID": "",
        "clOrdLinkID": "",
        "account": ,
        "symbol": "XBTUSD",
        "side": "Sell",
        "simpleOrderQty": null,
        "orderQty": 25000,
        "price": 8509.5,
        "displayQty": null,
        "stopPx": null,
        "pegOffsetValue": null,
        "pegPriceType": "",
        "currency": "USD",
        "settlCurrency": "XBt",
        "ordType": "Limit",
        "timeInForce": "GoodTillCancel",
        "execInst": "",
        "contingencyType": "",
        "exDestination": "XBME",
        "ordStatus": "Filled",
        "triggered": "",
        "workingIndicator": false,
        "ordRejReason": "",
        "simpleLeavesQty": 0,
        "leavesQty": 0,
        "simpleCumQty": 2.938,
        "cumQty": 25000,
        "avgPx": 8509,
        "multiLegReportingType": "SingleSecurity",
        "text": "Submission from testnet.bitmex.com",
        "transactTime": "2018-03-23T07:26:34.002Z",
        "timestamp": "2018-03-23T07:28:03.369Z"
    }`

**Comment by ryanfox** [comment]
It's not clear what you are trying to do - what information are you trying to get?
