### ISSUE TITLE
need help... 'bravado.exception.HTTPBadRequest' am i doing something wrong?

### ISSUE THREAD

**Issue by flyinbug** [BitMEX/api-connectors#111]
![1](https://user-images.githubusercontent.com/37862907/38169816-f24f6088-35a6-11e8-96b6-52dde77f79ee.jpg)
It's good without APIKEY.
![2](https://user-images.githubusercontent.com/37862907/38169820-09a894de-35a7-11e8-8e74-2cb5b6d9ea74.jpg)
Occurs this error with APIkey and secret.

**Comment by flyinbug** [comment]
you are right! problem solved! thank you!

**Comment by cofibit** [comment]
@flyinbug how did you resolve this issue? I am having the same error on live on windows platform, should I be running it on unix?
