### ISSUE TITLE
Bitmex API throwing wrong timestamp

### ISSUE THREAD

**Issue by danglade** [BitMEX/api-connectors#115]
Bitmex API throwing wrong timestamp when sending 1D. If I check my time in UTC, currently today is 2018-04-10 1:34 AM. Last timestamp received by Bitmex api is 2018-4-11, that's a day off by my understanding. 
Now If I send 1M (1 minute) last timestamp seems fine, which is 2018-04-10 in UTC.

Whats going on?

Here is the URL I'm using
**/api/v1/trade/bucketed?symbol=XBTUSD&count=500&reverse=True&partial=False&binSize=1d**
**/api/v1/trade/bucketed?symbol=XBTUSD&count=500&reverse=True&partial=False&binSize=1m**

![image](https://user-images.githubusercontent.com/6461587/38531434-c58ea28c-3c3d-11e8-9257-151b98bd1877.png)

**1M**
[{"timestamp":"**2018-04-10T01:37:00.000Z**","symbol":"XBTUSD","open":6724.5,"high":6724.5,"low":6724.5,"close":6724.5,"trades":1,"volume":5,"vwap":6724.5,"lastSize":5,"turnover":74355,"homeNotional":0.00074355,"foreignNotional":5},{"timestamp":"2018-04-10T01:36:00.000Z","symbol":"XBTUSD","open":6717.5,"high":6724.5,"low":6720,"close":6724.5,"trades":5,"volume":74881,"vwap":6724.4973,"lastSize":44260,"turnover":1113600921,"homeNotional":11.136009210000001,"foreignNotional":74881},

{"timestamp":"**2018-04-10T01:35:00.000Z**","symbol":"XBTUSD","open":6727.5,"high":6727.5,"low":6717.5,"close":6717.5,"trades":12,"volume":10004,"vwap":6720.8818,"lastSize":4,"turnover":148854696,"homeNotional":1.4885469599999999,"foreignNotional":10004},{"timestamp":"2018-04-10T01:34:00.000Z","symbol":"XBTUSD","open":6727.5,"high":6747,"low":6727.5,"close":6727.5,"trades":29,"volume":102138,"vwap":6743.0883,"lastSize":677,"turnover":1514727277,"homeNotional":15.14727277,"foreignNotional":102138},

{"timestamp":"**2018-04-10T01:33:00.000Z**","symbol":"XBTUSD","open":6721,"high":6727.5,"low":6717.5,"close":6727.5,"trades":19,"volume":14946,"vwap":6719.0755,"lastSize":460,"turnover":222446062,"homeNotional":2.22446062,"foreignNotional":14946},{"timestamp":"2018-04-10T01:32:00.000Z","symbol":"XBTUSD","open":6735,"high":6735,"low":6721,"close":6721,"trades":29,"volume":8309,"vwap":6727.2116,"lastSize":100,"turnover":123519752,"homeNotional":1.2351975200000003,"foreignNotional":8309},

{"timestamp":"**2018-04-10T01:31:00.000Z**","symbol":"XBTUSD","open":6731.5,"high":6748,"low":6727.5,"close":6735,"trades":60,"volume":50681,"vwap":6735.3674,"lastSize":50,"turnover":752484609,"homeNotional":7.5248460900000005,"foreignNotional":50681},{"timestamp":"2018-04-10T01:30:00.000Z","symbol":"XBTUSD","open":6725,"high":6738.5,"low":6721.5,"close":6731.5,"trades":31,"volume":20586,"vwap":6730.834,"lastSize":33,"turnover":305855894,"homeNotional":3.0585589400000006,"foreignNotional":20586},

{"timestamp":"**2018-04-10T01:29:00.000Z**","symbol":"XBTUSD","open":6715,"high":6735.5,"low":6715.5,"close":6725,"trades":34,"volume":55791,"vwap":6731.7402,"lastSize":256,"turnover":828814546,"homeNotional":8.28814546,"foreignNotional":55791},{"timestamp":"2018-04-10T01:28:00.000Z","symbol":"XBTUSD","open":6700.5,"high":6715.5,"low":6700.5,"close":6715,"trades":23,"volume":845175,"vwap":6703.7608,"lastSize":674,"turnover":12608216157,"homeNotional":126.08216157,"foreignNotional":845175},

**1D**
[{"timestamp":"**2018-04-11T00:00:00.000Z**","symbol":"XBTUSD","open":6763,"high":6768.5,"low":6731,"close":6731.5,"trades":12537,"volume":67829398,"vwap":6754.0186,"lastSize":500,"turnover":1004304860586,"homeNotional":10043.048605860015,"foreignNotional":67829398},

{"timestamp":"**2018-04-10T00:00:00.000Z**","symbol":"XBTUSD","open":7014,"high":7177.5,"low":6600,"close":6763,"trades":446035,"volume":2772773920,"vwap":6875.6876,"lastSize":10000,"turnover":40327854762581,"homeNotional":403278.54762581136,"foreignNotional":2772773920},

{"timestamp":"**2018-04-09T00:00:00.000Z**","symbol":"XBTUSD","open":6900.5,"high":7137,"low":6885,"close":7014,"trades":334646,"volume":1602230571,"vwap":6995.453,"lastSize":44,"turnover":22904790754766,"homeNotional":229047.90754766003,"foreignNotional":1602230571},

{"timestamp":"**2018-04-08T00:00:00.000Z**","symbol":"XBTUSD","open":6612,"high":7058.5,"low":6608,"close":6900.5,"trades":374658,"volume":1935569407,"vwap":6889.4247,"lastSize":10,"turnover":28096050090990,"homeNotional":280960.50090990175,"foreignNotional":1935569407},

**Comment by STRML** [comment]
You are getting the "partial" response. 

We do not recognize `True` and `False`. Use `true` and `false` or `1` and `0`.

**Comment by danglade** [comment]
Hows that relevant to the timestamp situation?

**Comment by STRML** [comment]
"partial" returns an in-progress bin. Essentially it returns one bin in the future with the OHLC data as aggregated so far. For example, if it is 9:20 and the user queries this, we will return the 10:00 bin with OHLC data aggregated from what has traded from 9:00 to 9:20. This is useful for charting.

**Comment by danglade** [comment]
Thank you for your help. Btw, where I can find more information about Partial? Is there more Bitmex API info?

**Comment by ryanfox** [comment]
There is some info [here.](https://testnet.bitmex.com/app/wsAPI#Subscriptions) The API documentation is [here.](https://testnet.bitmex.com/app/apiOverview)

**Comment by danglade** [comment]
Thank you.
