### ISSUE TITLE
Python "has no attribute 'bitmex'"

### ISSUE THREAD

**Issue by 2803media** [BitMEX/api-connectors#117]
Hi I have Python 3.6 install and after installing BitMEX Python client 

here is the pip list:

```
bitmex (0.2.2)
bitmex-ws (0.3.1)
bravado (9.2.2)
bravado-core (4.13.2)
certifi (2018.1.18)
chardet (3.0.4)
idna (2.6)
jsonref (0.1)
jsonschema (2.6.0)
msgpack-python (0.5.6)
numpy (1.14.2)
pandas (0.22.0)
pip (9.0.3)
python-dateutil (2.7.2)
pytz (2018.3)
PyYAML (3.12)
requests (2.18.4)
rfc3987 (1.3.7)
setuptools (39.0.1)
simplejson (3.13.2)
six (1.11.0)
strict-rfc3339 (0.7)
swagger-spec-validator (2.1.0)
TA-Lib (0.4.17)
urllib3 (1.22)
webcolors (1.8.1)
websocket-client (0.46.0)
```

And the code use:

```
import bitmex
client = bitmex.bitmex()
result = client.Quote.Quote_get(symbol="XBTUSD", reverse=True, count=1).result()
print(result)
```
And I have the following error:

    Traceback (most recent call last):
      File "/home/ff/public_html/bitmex/bitmex-testnet2.py", line 2, in <module>
         client = bitmex.bitmex()
    AttributeError: module 'bitmex' has no attribute 'bitmex'

Where is the error?

Thanks

**Comment by letterk** [comment]
/home/ff/public_html/bitmex/bitmex-testnet2.py
directory bitmex
conflicts

**Comment by 2803media** [comment]
Damned you're right thanks!
