### ISSUE TITLE
Current Swagger spec generates a faulty Haskell client

### ISSUE THREAD

**Issue by Lucsanszky** [BitMEX/api-connectors#118]
The swagger code generator for a http-client based Haskell client (https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/HaskellHttpClientCodegen.java)
will generate a code that doesn't compile. 

**The reason:** The code generator will create two lenses with identical names (`chatChannelIdL`) because the `/chat` endpoint has a `channelID` response parameter, while the `/chat/channels` endpoint has an `id` response parameter. The Haskell code generator creates the names for the lenses by concatenating the `#ref` name and the response parameter name and making them camelCase. E.g.: if the `#ref` is `#/definitions/ChatChannel` and the parameter is `id`, we get `chatChannelIdL` and if the `#ref` is `#/definitions/Chat` and the parameter is `channelID`, then again we get `chatChannelIdL`. This will result in a name clash and thus, a compile error. 

An easy fix would be to change the `/chat/channels` response 200 `#ref` to `#/definitions/ChatChannels`.
https://github.com/BitMEX/api-connectors/blob/master/swagger.json#L506
https://github.com/BitMEX/api-connectors/blob/master/swagger.json#L4343

What do you think? Would you be okay with a spec change or should I report this to the swagger-codegen guys and ask them to defend against possible name clashes?

**Comment by STRML** [comment]
Hi @Lucsanszky - you're proposing creating another type for an array of ChatChannels? That's doable but a bit messy. It would be my preference that the codegen checks for conflicts as it should not be possible for the parameter to one function to collide with the return type of another. Simply keeping track of what has been allocated so far then appending a monotonic counter should take care of the immediate problem.

**Comment by Lucsanszky** [comment]
Hey @STRML,

What I'm proposing is to rename the `#/definitions/ChatChannel` response 200 reference to `#/definitions/ChatChannels`. So changing lines 506 and 4343 in https://github.com/BitMEX/api-connectors/blob/master/swagger.json from `"$ref": "#/definitions/ChatChannel"` to `"$ref": "#/definitions/ChatChannels"` and ` "ChatChannel": {` to ` "ChatChannels": {` respectively.
This will resolve the name clashing problem. I'm more than happy to create a PR with the changes. 

Regardless, I'll probably notify the swagger-codegen team about the name clash issue, since it is a good idea to defend against that possibility in the future.

Thanks!

**Comment by STRML** [comment]
Ah, but that would make our definition inconsistent. We use singular nouns for all of our models. I would rather this be fixed in codegen than change our spec.

**Comment by STRML** [comment]
That said, you could easily do some sed-fu on your copy of the spec and use that to generate a working connector.

**Comment by Lucsanszky** [comment]
Makes sense! I'll let the codegen team know.

And yup, that's what I did to create a working connector. :)
