### ISSUE TITLE
Python get current orders

### ISSUE THREAD

**Issue by 2803media** [BitMEX/api-connectors#119]
Hi I search but can't find a way to get the list of orders not yet closed with the official python connector.

I try 

```
client.Execution.Execution_get().result()
client.Order.Order_getOrders(filter=json.dumps({"open": True})).result()
```
but only get orders not yet filled but not orders current on trade

Thanks

**Comment by maoetc** [comment]
Try this:

client.Order.Order_getOrders(filter=json.dumps({'ordStatus': 'New'})).result()

**Comment by 2803media** [comment]
With your command I only get pending orders but not orders currently in trade...

The command which works is:

`client.Position.Position_get().result()`

Thanks
