### ISSUE TITLE
Can't call function Execution_getTradeHistory with parameters in python.

### ISSUE THREAD

**Issue by atlet** [BitMEX/api-connectors#12]
If I run this code:
```python
res, http_response = bitMEXAuthenticated.Execution.Execution_getTradeHistory(symbol = 'XBTUSD', end_time = '2013-10-20').result()
```
I get folowing error: `bravado_core.exception.SwaggerMappingError: Execution_getTradeHistory does not have parameter end_time`
 Bu if I run this code:
```python
res, http_response = bitMEXAuthenticated.Execution.Execution_getTradeHistory(symbol = 'XBTUSD').result()
```
I get folowing error:
`bravado.exception.HTTPUnauthorized: 401 Unauthorized: {u'error': {u'message': u'Signature not valid.', u'name': u'HTTPError'}}`

But if I run function without parameters, it's working fine:
```python
res, http_response = bitMEXAuthenticated.Execution.Execution_getTradeHistory().result()
```

What I'm doing wrong?

**Comment by STRML** [comment]
You weren't doing anything wrong - we made a mistake in the API key integration for certain requests.

Please pull the project & try again.

**Comment by atlet** [comment]
Great, now it's working fine. Tnx for fast solution.
