### ISSUE TITLE
Signature not valid on POST order

### ISSUE THREAD

**Issue by romanrakus** [BitMEX/api-connectors#121]
Hello,

I've tried your C# sample to create order and get orders list. Everything works fine for https://testnet.bitmex.com/. After I've switched to https://bitmex.com/ and real account open order throws me 'Signature not valid' error unless get orders list and others work just fine.

Are there any problems with signature?

**Comment by ryanfox** [comment]
Is your API key for testnet or bitmex.com?

**Comment by romanrakus** [comment]
I have this problem with bitmex.com

**Comment by romanrakus** [comment]
Any updates on this?

**Comment by romanrakus** [comment]
Hello,

Together with a support team, we defined that problem is if you don't put www in the URL. So, you cannot use https://bitmex.com/. Valid URL is https://www.bitmex.com/.

**Comment by jrabone** [comment]
Thanks @romanrakus you saved my life
