### ISSUE TITLE
Authentication invalid. Please check your credentials. 

### ISSUE THREAD

**Issue by rahul05ranjan** [BitMEX/api-connectors#122]
BitMEX-Delta-Server listening on http://localhost:4444
WebSocket [ERROR]: Authentication invalid. Please check your credentials. Message: {"error":"Invalid API Key."}
WebSocket [INFO]: The WebSocket will terminate. Please manually reconnect.
WebSocket [ERROR]: WebSocket closed unexpectedly.
Client closed due to unrecoverable WebSocket error. Please check errors above.

I inserted right Api key and secret key but it still showing the error mention above.

**Comment by ryanfox** [comment]
Double check that you created the key on the same version of the exchange you are trying to connect to. The example config [connects to testnet by default.](https://github.com/BitMEX/api-connectors/blob/master/official-ws/delta-server/config.example.js#L9)
