### ISSUE TITLE
Break Even Price

### ISSUE THREAD

**Issue by danglade** [BitMEX/api-connectors#127]
Hello, 

I'm querying the GetPosition on the Testnet.
My current position is the following

**Qty**: 4000
**Value**: 0.4254
**Mark** Price: 9402.8

On the response there is the "**breakEvenPrice**" , according to the calculator on Bitmex I should be on profit at this point, not really breaking even.

![image](https://user-images.githubusercontent.com/6461587/39592459-cc1f2410-4ed4-11e8-9fae-8cfa09162a4f.png)

Would like to understand more reasoning behind this number.
Appreciate the help.

**Comment by ryanfox** [comment]
`breakEvenPrice` takes fees into account. [See the BitMEX docs](https://testnet.bitmex.com/app/fees) for more information on that.

Note for `XBT`, the maker fee is -0.0250% - awfully close to the 2.43% in your screenshot above.
