### ISSUE TITLE
Live stream on C# 

### ISSUE THREAD

**Issue by Spino1981** [BitMEX/api-connectors#129]
Is there a way to get a live stream from BitMex using C#?
I see there is REST API but that would mean poll information at intervals.
Is websocket available for C#? Or a way to use the node.js or python websocket to feed C#?

**Comment by Spino1981** [comment]
Thank you for the reply, I see in the documentation that delta server
requires node js, how does that work with C#?
Luca

**Comment by ryanfox** [comment]
It runs a server locally, that you can poll with any client you wish.
