### ISSUE TITLE
trailing stop loss order

### ISSUE THREAD

**Issue by AhmMontasser** [BitMEX/api-connectors#130]
Hello, 

Am trying to set correct trailing stoploss orders. However, i don't clearly understand the difference between the following parameters 

pegOffsetValue => i don't know what is this exactly and i didn't understand the documentation or get it by trying
price => i understand this is the execution price.
stopPx => i understand this is the price at which the order is submitted to the order book 

i tried different setups on the testnet to understand by trial but i am not sure if i get things right, 
 Also, i don't see the order moving with the price as expected when using for example 

> client.Order.Order_new(symbol='XBTUSD', ordType='StopLimit',pegPriceType='TrailingStopPeg',pegOffsetValue=-20,orderQty=-10, price=tick['last']-200,stopPx=tick['last']-50).result()

Thanks for your help,

**Comment by ryanfox** [comment]
`pegOffsetValue` specifies the distance your trailing value starts from the triggering price. For example, if the mark price is 10,000, and you specify a `pegOffsetValue` of -10, your triggering price will be 9990.

`price` is the price your order will be submitted at. This only applies to Stop Limit orders, Stop Market orders do not need a price.

To create a trailing stop loss order, don't specify `stopPx`. The `stopPx` is calculated from `execInst` and `pegOffsetValue`. `execInst` can be `MarkPrice` (the default), `LastPrice`, or `IndexPrice`.

So to adapt your example above, suppose the last price was 9500. Instead of specifying `stopPx=tick['last']-50`, try `execInst='Last', pegOffsetValue=-50`.

See [the API explorer](https://testnet.bitmex.com/api/explorer/#!/Order/Order_new) or [the docs](https://testnet.bitmex.com/app/orderTypeFAQ#Stop-Limit-Order-Example) for more info.

**Comment by AhmMontasser** [comment]
very good 
thank you @ryanfox  

when i tried the order chased the price by changing the trigger but the limit price remains the same ? 
is that normal ? can i allow the limit price to chase also ?

**Comment by boxxa** [comment]
I am having a similar issue with the trailing stop API.

I have an order of 1000 get filled so I submit this and it doesn't seem to flip the peg value.

For a stop on a SELL order of -1000 I pass this and would expect to see a 1000 stop order for 100 more than the last price.  
```
{symbol:"XBTUSD",ordType:"Stop",pegPriceType:"TrailingStopPeg",pegOffsetValue:100,type:"MarketIfTouched",execInst:'LastPrice',orderQty:1000}
```
And for a stop on a BUY order of 1000, I pass this and would expect to see a -1000 stop order for 100 less than the last price.
```
{symbol:"XBTUSD",ordType:"Stop",pegPriceType:"TrailingStopPeg",pegOffsetValue:-100,type:"MarketIfTouched",execInst:'LastPrice',orderQty:-1000}
```

It seems like the stop price doesn't calculate properly and is always > so orders get triggered right away.

**Comment by ryanfox** [comment]
@AhmMontasser the two options are a limit order or market order. See [1 and 2 here.](https://testnet.bitmex.com/app/orderTypeFAQ#Stop-Orders)

@boxxa Make sure you are issuing a valid order - `type` isn't a parameter.

**Comment by boxxa** [comment]
Not going to reopen the issue but wanted to comment since I missed the notification it seems @ryanfox 

Can you issue a stop loss on a new order? I found a way to do it when I get the execution notification but it seems bundling the trailing stop offset into the single API call isn't valid. No?

**Comment by JaySNL** [comment]
I do have a feeling it's wrong in the API. 
See: https://snag.gy/pyG5xI.jpg

When placing a trailing stop through the web interface, sell side, with a negative trailing value, we get a stopPx that's <=. If we push it through the API we get a >= on the sell side, but we want it to close then the price is below stopPx, not above, else it always gets triggered.

pegPriceType: TrailingStopPeg
PegOffsetValue: -(value)
ordType: "MarketIfTouched"
Side: ["side"]
execInst: "Close"
stopPx: (value)

**Comment by HollandRisley** [comment]
> very good
> thank you @ryanfox
> 
> when i tried the order chased the price by changing the trigger but the limit price remains the same ?
> is that normal ? can i allow the limit price to chase also to prevent a market order ?

Hi @ryanfox - Did you ever find a way to get the limit price to also chase the current price as well as the stop price?

**Comment by HollandRisley** [comment]
> very good
> thank you @ryanfox
> 
> when i tried the order chased the price by changing the trigger but the limit price remains the same ?
> is that normal ? can i allow the limit price to chase also to prevent a market order ?


Hi @AhmMontasser - Did you ever find a way to get the limit price to also chase the current price as well as the stop price?

**Comment by bendelo** [comment]
Currently this is not supported the trailing stop only updates the stopPx, but in future we might support floating Pegged orders.

**Comment by cryptoflipper** [comment]
@JaySNL shouldn't that ordType be 'Stop' rather than 'MarketIfTouched' for a trailing stop? I think if you use 'MarketIfTouched' that is a trailing profit order, though I haven't found a use for that yet.

**Comment by FM100X** [comment]
Hi, how can I place a market order via api, and include as well a trailing stop loss.

As of now I have the market order first (see below) and then place a trailing stop loss? 

Market Order:
client.Order.Order_new(symbol = symbol, orderQty = buyOrderQty, side = "Buy", ordType = ordType).result()

TrailingStop Loss:
bulk_order_SL.append({"symbol":symbol, 'ordType':"Stop", "pegPriceType":'TrailingStopPeg',"pegOffsetValue":-trailing_stop, "orderQty":-total_qty_outstanding })
client.Order.Order_newBulk(orders=json.dumps(bulk_order_SL)).result()

How to combine all in one, if possible?

**Comment by HollandRisley** [comment]
HI @FM100X,

You can't include Market Orders in Bulk Order Placement. This is a pain to work around. In my bot I do the following:

Place Stop Loss and LimitWhenHit orders (Target Points).
When confirmed as placed successfully
Place the Market Order

Hope this helps

**Comment by qboy21** [comment]
@ryanfox. This issue still persist in the Testnet UI same as @JaySNL mentioned when 
execInst: Close
pegPriceType: TrailingStopPeg
stopPx: Value (double)
orderQty: Value (double)
PegOffsetValue: -(value)

The trigger is backwards <= 20650.0 (50.0 trail) | 20452.5 | Trailing Stop | Filled
