### ISSUE TITLE
NodeJS WS Client: Subscribing to symbol tables with symbol "*" is broken

### ISSUE THREAD

**Issue by andersea** [BitMEX/api-connectors#132]
It is legal on to subscribe to updates for all symbols using "*", in other words, this is supported server-side. However the NodeJS WS client is broken here and will emit an empty array for each message recieved.

There are at least a couple of issues.

First, in createSocket.js, the following code will not work for symbol "*":

    // This is similar to _groupBy, but faster.
    for (let i = 0; i < data.data.length; i++) {
        const d = data.data[i];
        if (symbolData[d[filterKey]]) symbolData[d[filterKey]].push(d);
    }

`d[filterKey]` will be the name of the symbol and will never match "*".

Then in deltaParser.js, the following code breaks:

    if (!client._data[tableName][symbol] || dataArr.length) {
        client._data[tableName][symbol] = dataArr;
    }

This will store the partial data under key "*", causing all later updates to not be able to find the data that needs to be updated. To be correct, the code should iterate over the data array and extract the symbol for each element and store it under the right key.

Go ahead and say feel free to submit a pr.. I dare you!

**Comment by ryanfox** [comment]
I actually believe this is resolved. I get callback invocations for all symbols, subscribing like so:
```
client.addStream("*", "orderBookL2", function(data, symbol, tableName) {
    console.log("callback hit for symbol " + symbol);
});
```

Can you verify it works as expected for you as well?

**Comment by andersea** [comment]
Interesting. I'll give it another look as soon as I am able.

**Comment by andersea** [comment]
This does indeed seem to be something bad in my client code. Closing.
