### ISSUE TITLE
client restart and stop

### ISSUE THREAD

**Issue by petrupp** [BitMEX/api-connectors#133]
node swagger client 

for example...
Usually in the get method.. 
```
client.Instrument.Instrument_get({symbol: "XBTUSD"})
		  .then(function(response) { ....
```

If you run the above code, it will be restarted every 2 minutes.
I want to stop rerun and control.

Perhaps this is in conflict with my crontab. Create a nonce error.
It seems to cause nonce error with my crontab and duplicate execution.

Is there a way to stop it?

**Comment by ryanfox** [comment]
I am not sure I follow what you are asking. That function returns a single value, it doesn't restart itself.

Also the `Instrument` endpoint doesn't require authentication, you should not get a nonce error using that endpoint.

You might double check that you are actually running the function you think you are.
