### ISSUE TITLE
Node-Fetch: Can't place any kind of market order?

### ISSUE THREAD

**Issue by amagumori** [BitMEX/api-connectors#135]
I'm trying to use the node-fetch client to place some simple orders to testnet.  I'm sending a very simple request that looks like this:

```
async function testOrder() {
  try {
    var res = await makeRequest('POST', 'order', {
      symbol: 'XBTM18',
      side: 'Sell',
      orderQty: 5,
      ordType: 'market'
    });
    console.log('response: ' + res);
  } catch (e) {
    console.error("error: ", e);
  }
}

...

await testOrder();
```

This throws an error of "invalid price", which doesn't make sense to me since one shouldn't have to specify a price for a market order?  Specifying a price throws an "unsupported ordType".  Changing something else gave a "orderQty is invalid".  

Essentially I'm testing the simplest order POST that I can and am getting whack-a-mole errors on every single property in the request object.

Baffled.  Plz help

**Comment by ryanfox** [comment]
`ordType` is case-sensitive - try `Market` instead of `market`.

**Comment by amagumori** [comment]
lol
