### ISSUE TITLE
how to get my oder with python?

### ISSUE THREAD

**Issue by iroywang** [BitMEX/api-connectors#138]
Cant find it in Readme. sry.

**Comment by nguyenlong500** [comment]
client.Order.Order_getOrders(filter=json.dumps({"open": True})).result()

**Comment by ryanfox** [comment]
More information is available at https://testnet.bitmex.com/api/explorer/#!/Order/Order_getOrders

**Comment by vinoth2900** [comment]
how to odder cancel  use python

**Comment by vinoth2900** [comment]
flask rest API

**Comment by vinoth2900** [comment]
use costumer id
