### ISSUE TITLE
Python: How to use Python Adapter to follow two kinds of coins? Like XBTUSD and XBTM18

### ISSUE THREAD

**Issue by so2liu** [BitMEX/api-connectors#142]
Hallo, I want to follow the price of XBTUSD and XBTM18. How can I do that with your python adapter? I have tried to initialize two objects with different symbols, but it seems not right. How should I do that in python script or should I change a little in the example code 'main.py' ?
By the way, what's the argument "clOrdIDPrefix" for open_orders() in the "main.py"? I tried to open two orders (with REST) and give the one id of them as argument. But I get a empty list. 
Thanks

**Comment by ryanfox** [comment]
There are two python adapters - one using REST API calls and one using websockets.

Using the REST client, you could make multiple calls to `Quote` to get information on two different symbols. For example:

    xbtusd = client.Quote.Quote_get(symbol='XBTUSD', count=1, reverse=True).result()
    xbtm18 = client.Quote.Quote_get(symbol='XBTM18', count=1, reverse=True).result()

`clOrdIDPrefix`: Assuming you mean bitmex_websocket.py and not main.py - this means client order id prefix. `clOrdID` is a client-specified string to uniquely identify orders, supplied at order creation. A prefix can be specified to limit the orders returned in the response. You can see how it is used [here.](https://github.com/BitMEX/api-connectors/blob/d7510ea785add146a41c4a5e8ec17320b34f9703/official-ws/python/bitmex_websocket.py#L97)

You can find out more about the endpoints via the [API explorer.](https://testnet.bitmex.com/api/explorer/#!/Order/Order_new)

**Comment by sgtStrom** [comment]
@qianyk369 I think you don't, see #156

**Comment by ryanfox** [comment]
`/quote` is currently functioning normally. In light of no other issues appearing, I am closing this.

**Comment by Kinzowa** [comment]
Hello, how can I see my open order with the WebSocket API?

```
ws.open_orders()
Traceback (most recent call last):

  File "<ipython-input-22-62228c96f0ef>", line 1, in <module>
    ws.open_orders()

TypeError: open_orders() missing 1 required positional argument: 'clOrdIDPrefix'
```

**Comment by qianyk369** [comment]
> Hello, how can I see my open order with the WebSocket API? where can I find my client order id prefix? thanks!
> 
> ```
> ws.open_orders()
> Traceback (most recent call last):
> 
>   File "<ipython-input-22-62228c96f0ef>", line 1, in <module>
>     ws.open_orders()
> 
> TypeError: open_orders() missing 1 required positional argument: 'clOrdIDPrefix'
> ```
not sure. I am using REST api - Order.Order_getOrders()

**Comment by Kinzowa** [comment]
Then I will try with the REST API :|

**Comment by SebastianLuebke** [comment]
> Hello, how can I see my open order with the WebSocket API? where can I find my client order id prefix? thanks!
> 
> ```
> ws.open_orders()
> Traceback (most recent call last):
> 
>   File "<ipython-input-22-62228c96f0ef>", line 1, in <module>
>     ws.open_orders()
> 
> TypeError: open_orders() missing 1 required positional argument: 'clOrdIDPrefix'
> ```

ws.data["order']

**Comment by qianyk369** [comment]
You should use REST API which is more easier.
Order.Order_getOrders(symbol=[some symbol,]filter=[somefilter]).result()

Thanks

Sebastian Noel Lübke <notifications@github.com> 于2020年1月31日周五 上午11:47写道：

**Comment by ian-collab** [comment]
> Hello, how can I see my open order with the WebSocket API? where can I find my client order id prefix? thanks!
> ws.open_orders()
> Traceback (most recent call last):
> 
>   File "<ipython-input-22-62228c96f0ef>", line 1, in <module>
>     ws.open_orders()
> 
> TypeError: open_orders() missing 1 required positional argument: 'clOrdIDPrefix'

You need to have placed the order using a prefix for clOrdID, e.g. "Entry1", or "Entry2" have the prefix "Entry".

You can do this via the REST API

Then 
ws.open_orders("Entry) will show any order whose clOrdID begins with the string "Entry"

The BitMEXWebsocket class here is written only to filter for open orders beginning with a specific string for some reason.

A method in that class returning all open orders might be useful
