### ISSUE TITLE
Possible to get closed positions?

### ISSUE THREAD

**Issue by stefanmendoza** [BitMEX/api-connectors#145]
Is it possible to retrieve all closed positions? The Swagger doc states `Summary of Open and Closed Positions`, but it seems to only return open positions, even when providing a filter of `{"isOpen": "False"}` or `{"isOpen": "false"}`?

**Comment by stefanmendoza** [comment]
@ryanfox would you happen to know?

**Comment by ryanfox** [comment]
Sending a GET request to `/position` returns all your positions, open or closed.

You can try it out with [the API explorer.](https://testnet.bitmex.com/api/explorer/#/Position)

**Comment by stefanmendoza** [comment]
@ryanfox I've tried that but it only ever returns 0 or 1 positions (none or the current open one). I have not been able to retrieve closed positions through that endpoint.

**Comment by ryanfox** [comment]
Are you using the correct endpoint - i.e. testnet vs live?

Another thing to test would be opening two positions simultaneously, and see if both are returned.

**Comment by stefanmendoza** [comment]
Yes, the Live endpoint. Essentially, when hitting the Swagger endpoint for `/position` it only returns open positions, which at most has been one for me. What query is used to retrieve closed positions? I'll also try the two position idea when I get a chance.

**Comment by stefanmendoza** [comment]
@ryanfox  Yes, the Live endpoint. Essentially, when hitting the Swagger endpoint for `/position` it only returns open positions, which at most has been one for me. What query is used to retrieve closed positions? I'll also try the two position idea when I get a chance.

**Comment by LucasRodriguez** [comment]
@stefanmendoza did you manage to figure this out? would you mind sharing your fix? currently struggling with this too.

**Comment by LucasRodriguez** [comment]
@ryanfox Any inputs on this?
