### ISSUE TITLE
Python REST API Problem

### ISSUE THREAD

**Issue by YbyRonaldo** [BitMEX/api-connectors#146]
My program runs well in ''GET'' method with authenticated, but when I tried to "POST"  a new order it response an error with HttpError code 403 Access Denied. I tried it on the TESTNET API Explorer, it runs without any problem seems the endpoint going well. How can I deal with it?

**Comment by ryanfox** [comment]
Make sure the API key you are using has `Order` permissions:
https://testnet.bitmex.com/app/apiKeysUsage#API-Key-Permissions

> If you wish to execute orders with your API Key, you must add the `"order"` permission upon creation.

**Comment by YbyRonaldo** [comment]
thanks a lot! I had ignored the type of API key I was using. The problem has been solved now.
