### ISSUE TITLE
Couldn't find user/margin call from python api

### ISSUE THREAD

**Issue by dlguddus** [BitMEX/api-connectors#147]
I couldn't find any mapping info which connect between API Endpoint and python api call name.
For example, **GET /position** in API Endpoint match to **client.Position.Position_get().result()**.
Please provide information about python api call names. 
I couldn't find any of this in github.
json does not match either.

**Comment by ryanfox** [comment]
On the client side, you can use `dir` to enumerate the available functions.

The function names explain which API endpoints they map to - for example, `client.User.User_getMargin` sends a GET request to `/user/margin`.

For a list of available API endpoints, see the [API explorer.](https://testnet.bitmex.com/api/explorer/)

**Comment by rx1e** [comment]
can you write how to use the "dir" syntax ?
I tried client.User.dir() without sucess.

thanks

**Comment by ryanfox** [comment]
`dir()` is a Python [built-in function.](https://docs.python.org/3/library/functions.html#dir)

You want to use something like `dir(client.User)`.
