### ISSUE TITLE
fetch balance

### ISSUE THREAD

**Issue by AhmMontasser** [BitMEX/api-connectors#148]
Hello 
Am using bitmex python API, i want to fetch my current account balance and open positions but i don't find how can i do this ?
Please advice,

**Comment by ryanfox** [comment]
You can get account balance by querying `client.User.User_getWalletSummary`. Open positions are available through `client.Position.Position_get`.

All API endpoints are documented at [the API explorer.](https://testnet.bitmex.com/api/explorer/#!/Position/Position_get)
