### ISSUE TITLE
KeyError: 'tickLog' - when calling ws.get_ticker() with api_key

### ISSUE THREAD

**Issue by cryptonaut1357** [BitMEX/api-connectors#149]
`2018-06-03 21:00:15,420 - bitmex_websocket - INFO - Got all market data. Starting.
Traceback (most recent call last):
  File "C:/Users/N/untitled/BITMEX/Websocket/WebSock.py", line 52, in <module>
    run()
  File "C:/Users/N/untitled/BITMEX/Websocket/WebSock.py", line 24, in run
    ticker = ws.get_ticker()
  File "C:\Users\N\untitled\BITMEX\Websocket\bitmex_websocket.py", line 83, in get_ticker
    return {k: round(float(v or 0), instrument['tickLog']) for k, v in ticker.items()}
  File "C:\Users\N\untitled\BITMEX\Websocket\bitmex_websocket.py", line 83, in <dictcomp>
    return {k: round(float(v or 0), instrument['tickLog']) for k, v in ticker.items()}
KeyError: 'tickLog'
`

Using the standard websocket code.
Without the api key it works, with api key & secret this error occurs.
Would appreciate help!
regards

**Comment by ryanfox** [comment]
We'll need more information to diagnose what's going on. What are you trying to do? What code are you running?

**Comment by cohaolain** [comment]
Even with the very simple program below this still occurs the majority of the time with me. It does appear to work sometimes, however:
`from bitmex_websocket import BitMEXWebsocket
socket = BitMEXWebsocket(endpoint="https://www.bitmex.com/api/v1",
    symbol="XBTUSD", api_key=None, api_secret=None)
socket.get_ticker()
`
This throws the exception:
`Traceback (most recent call last):                                                                                                                                                              File ".\tickerTest.py", line 4, in <module>                                                                                                                                                     socket.get_ticker()                                                                                                                                                                         File "C:\Users\cohaolain\AppData\Local\Programs\Python\Python36\lib\site-packages\bitmex_websocket.py", line 83, in get_ticker                                                                  return {k: round(float(v or 0), instrument['tickLog']) for k, v in ticker.items()}                                                                                                          File "C:\Users\cohaolain\AppData\Local\Programs\Python\Python36\lib\site-packages\bitmex_websocket.py", line 83, in <dictcomp>                                                                  return {k: round(float(v or 0), instrument['tickLog']) for k, v in ticker.items()}                                                                                                        KeyError: 'tickLog'`

**Comment by ryanfox** [comment]
`get_ticker()` depends on `tickLog` being set in the dict. This occurs when `getInstrument()` is called - as a workaround you could call `socket.get_instrument()` immediately after creating the socket.

**Comment by GrilledChickenThighs** [comment]
I understand calling get_instrument() before get_ticker() acts as a workaround, but why not add tickLog to the dictionary when calling get_ticker() to avoid the bug and having to workaround?
`
   def get_ticker(self):
        '''Return a ticker object. Generated from quote and trade.'''
        lastQuote = self.data['quote'][-1]
        lastTrade = self.data['trade'][-1]
        ticker = {
            "last": lastTrade['price'],
            "buy": lastQuote['bidPrice'],
            "sell": lastQuote['askPrice'],
            "mid": (float(lastQuote['bidPrice'] or 0) + float(lastQuote['askPrice'] or 0)) / 2
        }

        # The instrument has a tickSize. Use it to round values.
        instrument = self.data['instrument'][0]
        instrument['tickLog'] = int(math.fabs(math.log10(instrument['tickSize'])))  # Add this for fix.
        return {k: round(float(v or 0), instrument['tickLog']) for k, v in ticker.items()}
`

**Comment by r8m** [comment]
> I understand calling get_instrument() before get_ticker() acts as a workaround, but why not add tickLog to the dictionary when calling get_ticker() to avoid the bug and having to workaround?
> 
> ```
> def get_ticker(self):
>     '''Return a ticker object. Generated from quote and trade.'''
>     lastQuote = self.data['quote'][-1]
>     lastTrade = self.data['trade'][-1]
>     ticker = {
>         "last": lastTrade['price'],
>         "buy": lastQuote['bidPrice'],
>         "sell": lastQuote['askPrice'],
>         "mid": (float(lastQuote['bidPrice'] or 0) + float(lastQuote['askPrice'] or 0)) / 2
>     }
> 
>     # The instrument has a tickSize. Use it to round values.
>     instrument = self.data['instrument'][0]
>     instrument['tickLog'] = int(math.fabs(math.log10(instrument['tickSize'])))  # Add this for fix.
>     return {k: round(float(v or 0), instrument['tickLog']) for k, v in ticker.items()}
> ```

I think there is an error in calculating tickLog:
```
#Now round operation makes wrong price:
tickSize = 0.5
tickLog = int(math.fabs(math.log10(tickSize)))
round(123.5, tickLog)
Out[]: 124.0

#Correct round operation
tickLog = math.ceil(math.fabs(math.log10(tickSize)))
round(123.5, tickLog)
Out[]: 123.5
```
