### ISSUE TITLE
Run well in Testnet but error in real market

### ISSUE THREAD

**Issue by YbyRonaldo** [BitMEX/api-connectors#151]
My program run well at testnet and wanna to run in real market. However, when I tested to get my user information, it response an error below:
Traceback (most recent call last):
...
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
The response has a response error with code 400. All my requests response the same error above no matter the "GET" or "POST" methods, but all of these requests can success in Testnet. 
 I have just change the host URL from testnet.bitmex.com to www.bitmex.com and my apikeys from Testnet's to Bitmex's.  

Are there any differences in requests decode between Testnet and www.bitmex.com? I haven't found an introduction to explain differences.

**Comment by ryanfox** [comment]
Testnet is designed to be the same as www.bitmex.com - you should be able to change the URL and API key.

If you're encountering errors, it would help to have an example of what code is triggering it.
