### ISSUE TITLE
Where can I go for explanations about API enpoints fields? 

### ISSUE THREAD

**Issue by hel-o** [BitMEX/api-connectors#152]
I read FIX protocol but i cant find many fields, just for example I calling endpoint for positions and these fields like: rebalancedPnl, unrealisedPnlPcnt and anothers arent explained. 
Another thing is why in that enpoint, this "unrealisedPnlPcnt" field returns, for example: -0.0218 but when you see the web trading this value is: -2.18 %, seems like the value must be multiply by 100, so we have: -0.0218 * 100 = -2.18 % just like the web trading, but why ? just for this kind of reasons, where can I go for fields explanations?, the FIX protocol helps too but BitMEX adds their own fields.

**Comment by ryanfox** [comment]
Hi there, thanks for the feedback. We are adding descriptions to clarify fields in the documentation.

To your specific question: that number is presented as a % in the web interface for convenience. -0.0218 and 2.18% mean the same thing.
