### ISSUE TITLE
Can I quote a date range using websocket python project?

### ISSUE THREAD

**Issue by qianyk369** [BitMEX/api-connectors#153]
I am able to listen the realtime data using websocket. But I am wondering can I quote a history data using websocket?

Thanks

**Comment by ryanfox** [comment]
Websockets provide streaming updates. For historical data, see [the REST API connectors](https://github.com/BitMEX/api-connectors/tree/master/official-http) and [API explorer.](https://testnet.bitmex.com/api/explorer/)
