### ISSUE TITLE
GET /quote doesn't work via Python requests and via BitMEX API Explorer

### ISSUE THREAD

**Issue by roman88r** [BitMEX/api-connectors#156]
I get the following error with this request:

```
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
</body>
</html>
```

Thanks!

**Comment by treypeng** [comment]
Getting the same thing, directly and via ccxt.

**Comment by Igrok1979** [comment]
If I enter price manually w/o getting quotation, everything goes smoothly. Entry is made and SL and TP set

**Comment by roman88r** [comment]
Is there any update on this issue?

**Comment by Igrok1979** [comment]
Looks like not yet. I am using OrderBook/L2 as a substitute

**Comment by Igrok1979** [comment]
@roman88r I use get/trade/bucketed to get candles from API
https://www.bitmex.com/api/explorer/#!/Trade/Trade_getBucketed
It should work

**Comment by sgtStrom** [comment]
Any news? Same problem.

**Comment by roman88r** [comment]
It seems that this function has been turned off manually by Bitmex and this issue can be closed.

**Comment by ragupathis** [comment]
Hello All.,

We are facing the similar issue while running placing an order code in python terminal. 

Please look at the screenshot for better understanding.
![bitmex](https://user-images.githubusercontent.com/5587483/46411160-ae3b0680-c738-11e8-84fb-d69dbf4446d2.jpg)

We are running in the Testnet API and we are following the steps from this GitHub repo link https://github.com/BitMEX/api-connectors/tree/master/official-http/python-swaggerpy.


We are trying to place a custom order using WebSockets., pls give us a working approach to do that.

Thanks in advance.

**Comment by roman88r** [comment]
This function has been turned off manually by Bitmex. This has not been working for 4 months.. Info 1000%

**Comment by ragupathis** [comment]
Okay, thanks. Then how to create an order using an API? 
Is there any working solution?

**Comment by roman88r** [comment]
@ragupathis [https://www.bitmex.com/api/explorer/#!/Order/Order_new] work good

**Comment by ragupathis** [comment]
Okay thank you. I will check it out.

**Comment by bitRomney** [comment]
> Okay, thanks. Then how to create an order using an API?
> Is there any working solution?



> Okay, thanks. Then how to create an order using an API?
> Is there any working solution?

> as workaround, i am using OrderBook/L2

Using contributions from others who came before me with questions, I've hacked together a complete workaround guide over the past 6 months to allow Python2.x support and to avoid common errors digging thru the many, many open(and carelessly closed) issues in the repo BitMEX/api-connectors. This is an aggregation of useful resources I found to use to the api-connectors without bravado errors and import errors and with Python2.x support:

1 @mazmex7 has developed a nice workaround to support Python2.x. This code is fixed to use in Python 2.x and 3.x. Download here:
https://github.com/mazmex7/BitMEX-API-python
Another common error is 
```
ImportError: No module named parse.
```
His code fixes the ImportError using a try catch in line 3 of the bitmex.py file
Thank you @mazmex7

2 Some may still see this error 
```
/Library/Python/2.7/site-packages/swagger_spec_validator/validator20.py:56: SwaggerValidationWarning: Found "$ref: #/definitions/UserPreferences" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information.
  warnings.warn(swagger_validation_warning)
```
You can comment out the line 56 of validator20.py where it prints the error because the request is already successful

3 Getting a simple Price Quote
Work around to get the current price is using another endpoint. orderBook/L2 python:

```
import requests, json
response = requests.get("https://www.bitmex.com/api/v1/orderBook/L2?symbol=eth&depth=1 …").json()
ether_bid_price = response[1]['price']
```

**Comment by chg90** [comment]
> I wrote a tutorial here: https://link.medium.com/qDRwB8KgqT
> 
> 1 @mazmex7 has developed a nice workaround to support Python2.x. This code is fixed to use in Python 2.x and 3.x. Download here:
> https://github.com/mazmex7/BitMEX-API-python
> Another common error is
> 
> ```
> ImportError: No module named parse.
> ```
> His code fixes the ImportError using a try catch in line 3 of the bitmex.py file
> Thank you @mazmex7
> 
> 2 Some may still see this error
> 
> ```
> /Library/Python/2.7/site-packages/swagger_spec_validator/validator20.py:56: SwaggerValidationWarning: Found "$ref: #/definitions/UserPreferences" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information.
>   warnings.warn(swagger_validation_warning)
> ```
> You can comment out the line 56 of validator20.py where it prints the error because the request is already successful
> 
> 3 Getting a simple Price Quote
> Work around to get the current price is using another endpoint. orderBook/L2 python:
> 
> ```
> import requests, json
> response = requests.get("https://www.bitmex.com/api/v1/orderBook/L2?symbol=eth&depth=1 …").json()
> ether_bid_price = response[1]['price']
> ```

Thank you for your sharing！

I still have a question:

how to signature with apiKey and apiSecret when use url “https://www.bitmex.com/api/v1/orderBook/L2” ?
