### ISSUE TITLE
POST /order Python REST API Problem

### ISSUE THREAD

**Issue by roman88r** [BitMEX/api-connectors#157]
I get the following error with such request:

```
api_key = ****
api_secret = ***
base_url = 'https://www.bitmex.com'
verb = 'POST'
function_url = '/api/v1/order'
url = base_url + function_url
expires = int(round(time.time()) + 5)
data = {'symbol':'XBTUSD',
            'orderQty':1,
            'price':8000,
            'side':'Sell',
            'ordType':'Limit',
            'timeInForce':'GoodTillCancel'}

message = verb + function_url + str(expires) + json.dumps(data)
signature = hmac.new(api_secret, message, digestmod=hashlib.sha256).hexdigest()
headers = {'api-expires': str(expires),
               'api-key': api_key,
               'api-signature': signature
                }
r = requests.post(url, headers=headers)
```
Error: {"error":{"message":"Signature not valid.","name":"HTTPError"}

But when I try to make other authorized requests like this:
```
api_key = ****
api_secret = ***
base_url = 'https://www.bitmex.com'
verb = 'GET'
function_url = '/api/v1/order'
url = base_url + function_url
expires = int(round(time.time()) + 5)

message = verb + function_url + str(expires) + ''
signature = hmac.new(api_secret, message, digestmod=hashlib.sha256).hexdigest()
headers = {'api-expires': str(expires),
               'api-key': api_key,
               'api-signature': signature}
r = requests.get(url, headers=headers)
```
everyting is ok.
I think the problem is in data dictionary, but what exactly is the problem?
Thanks for help!

**Comment by bendelo** [comment]
You're not actually sending the data in the request body...

**Comment by roman88r** [comment]
Thanks! Now everything ok!

**Comment by playscforever** [comment]
`    api_key = API_KEY
    api_secret = API_SECRET
    base_url = BASE_URL
    verb = 'POST'
    function_url = '/api/v1/order'
    url = base_url + function_url
    expires = int(round(time.time()) + 5)
    data = {'symbol': 'XBTUSD',
            'orderQty': 1,
            'price': 8000,
            'side': 'Sell',
            'ordType': 'Limit',
            'timeInForce': 'GoodTillCancel'}

    message = verb + function_url + str(expires) + json.dumps(data)
    signature = hmac.new(bytes(api_secret, 'utf8'),bytes(message, 'utf8') , digestmod=hashlib.sha256).hexdigest()
    headers = {'api-expires': str(expires),
               'api-key': api_key,
               'api-signature': signature
               }
    r = requests.post(url, headers=headers, data=data)
    data = json.loads(r.text)
    print(data)`


@roman88r @bendelo 
I got same problem and i sending the data in the request body.Please Help me

**Comment by Rapha92** [comment]
I am having the same issues with the Post Request in Python - could you share the solution to access it via python?

**Comment by krsinin** [comment]
@roman88r are you still successfully using requests with post?

**Comment by roman88r** [comment]
> @roman88r are you still successfully using requests with post?

try this variant. ### - lines with corrections

```
api_key = *
api_secret = *
base_url = 'https://bitmex.com' ###
verb = 'POST'

data = {"symbol":"XBTUSD","orderQty":100,"price":2600,"ordType":"Limit"} ### side?

f_url = '/api/v1/order'
url = base_url + f_url
expires = int(round(time.time()) + 5) ###

#parsedURL = urlparse(url)
#path = parsedURL.path
#if parsedURL.query:
#     path = path + '?' + parsedURL.query

#if isinstance(data, (bytes, bytearray)):
#     data = data.decode('utf8')

#print("Computing HMAC: %s" % verb + path + str(expires) + data)
message = verb + f_url + str(expires) + json.dumps(data) ###

signature = hmac.new(api_secret, message, digestmod=hashlib.sha256).hexdigest() ###

headers = {'api-expires':str(expires),'api-key':api_key,'api-signature':signature}
r = requests.post(url, headers=headers, json=data) ###
pprint.pprint(r.json())
```

**Comment by krsinin** [comment]
json keyword did the trick. Thanks.

**Comment by GavryushkinSI** [comment]
Colleagues  I did not understand what should be done in the end
