### ISSUE TITLE
How to set APIKey/Secret in Golang

### ISSUE THREAD

**Issue by sgama** [BitMEX/api-connectors#159]
I'm not convinced the autogenerated Golang client worked for Authenticated endpoints.

I'm not sure how to set the APIKey and secret as the struct only contains a field for a Key, but not a secret.

Secondly, the client doesn't seem to do any of the nonce calculation or signature calculation
This is the code for setting the key, nonce and signature.

``
	if ctx != nil {
		// API Key Authentication
		if auth, ok := ctx.Value(ContextAPIKey).(APIKey); ok {
			var key string
			if auth.Prefix != "" {
				key = auth.Prefix + " " + auth.Key
			} else {
				key = auth.Key
			}
			localVarHeaderParams["api-key"] = key
			
		}
	}
	if ctx != nil {
		// API Key Authentication
		if auth, ok := ctx.Value(ContextAPIKey).(APIKey); ok {
			var key string
			if auth.Prefix != "" {
				key = auth.Prefix + " " + auth.Key
			} else {
				key = auth.Key
			}
			localVarHeaderParams["api-nonce"] = key
			
		}
	}
	if ctx != nil {
		// API Key Authentication
		if auth, ok := ctx.Value(ContextAPIKey).(APIKey); ok {
			var key string
			if auth.Prefix != "" {
				key = auth.Prefix + " " + auth.Key
			} else {
				key = auth.Key
			}
			localVarHeaderParams["api-signature"] = key
			
		}
	}
``

Do I just misunderstand the code structure or is the Golang client incomplete?

**Comment by YesYouKenSpace** [comment]
@sgama did you manage to get it to work? I realised there is no signature computation too.
