### ISSUE TITLE
tradeBin1m returns a huge array that keeps growing (nodejs bitmex-realtime-api)

### ISSUE THREAD

**Issue by n3m6** [BitMEX/api-connectors#16]
tradeBin1m stream returns an array that keeps adding to existing data and keeps growing. 
**Code modified from example.js:**
`client.addStream('XBTUSD', 'tradeBin1m', (data) => {
  console.log(JSON.stringify(data));
  console.log('\n');
});`

**Result:**
`[{"timestamp":"2017-09-09T20:58:00.000Z","symbol":"XBTUSD","open":4294.4,"high":4293.6,"low":4287.4,"close":4293.6,"trades":2,"volume":19436,"vwap":4287.9808,"lastSize":1250,"turnover":453282764,"homeNotional":4.53282764,"foreignNotional":19436}]

[{"timestamp":"2017-09-09T20:58:00.000Z","symbol":"XBTUSD","open":4294.4,"high":4293.6,"low":4287.4,"close":4293.6,"trades":2,"volume":19436,"vwap":4287.9808,"lastSize":1250,"turnover":453282764,"homeNotional":4.53282764,"foreignNotional":19436},{"timestamp":"2017-09-09T20:59:00.000Z","symbol":"XBTUSD","open":4293.6,"high":4292.2,"low":4287.6,"close":4287.6,"trades":2,"volume":2500,"vwap":4290.0043,"lastSize":1250,"turnover":58276250,"homeNotional":0.5827625000000001,"foreignNotional":2500}]

[{"timestamp":"2017-09-09T20:58:00.000Z","symbol":"XBTUSD","open":4294.4,"high":4293.6,"low":4287.4,"close":4293.6,"trades":2,"volume":19436,"vwap":4287.9808,"lastSize":1250,"turnover":453282764,"homeNotional":4.53282764,"foreignNotional":19436},{"timestamp":"2017-09-09T20:59:00.000Z","symbol":"XBTUSD","open":4293.6,"high":4292.2,"low":4287.6,"close":4287.6,"trades":2,"volume":2500,"vwap":4290.0043,"lastSize":1250,"turnover":58276250,"homeNotional":0.5827625000000001,"foreignNotional":2500},{"timestamp":"2017-09-09T21:00:00.000Z","symbol":"XBTUSD","open":4287.6,"high":4287.6,"low":4287.6,"close":4287.6,"trades":0,"volume":0,"vwap":null,"lastSize":null,"turnover":0,"homeNotional":0,"foreignNotional":0}]`

**Comment by n3m6** [comment]
Server is not resending the data. Data is just locally being stored in an array. Just a bit of confusion. Closing issue.

**Comment by Yoganesh** [comment]
Did you figure out a way to clean up old data from this data array?

**Comment by n3m6** [comment]
I figured it didn't matter, really, and could come in handy sometimes too.
