### ISSUE TITLE
How to pass authentication with Position WebSocket API in JavaScript/jQuery

### ISSUE THREAD

**Issue by dotnetjalps** [BitMEX/api-connectors#164]
We have got an internal system which uses Bitmex web socket real-time  API and we want to integrate with Javascript./jQuery So basic idea is to create a WebSocket call directly from the javascript/jQuery itself instead of node.js.

I have tried lots of stuff but unable to found any example there use it with Authentication. I know that with bitmex realtime API it can be done but what I want to do call following realtime api with javascirpt/jquery on the client side.

wss://www.bitmex.com/realtime?subscribe=position:XBTUSD;

here it's required to have authentication. I know that with NPM we can do like following.

const options = {
    testnet: false,
    apiKeyID: 'your api key id',
    apiKeySecret: 'your api key',
    maxTableLen: 10000
};

var client = new bixMEXClient(options);

I want to learn how we can do same using jquery/javascript without node.js or any other server-side framework. Any code sample will be highly appreciated.

**Comment by ryanfox** [comment]
The API connectors are designed to be run server-side. You may find [browserify](http://browserify.org/) useful.
