### ISSUE TITLE
ws-official: Wild card stream subscriptions returning empty arrays for orders?

### ISSUE THREAD

**Issue by kevzettler** [BitMEX/api-connectors#167]
possibly related to: https://github.com/BitMEX/api-connectors/issues/166

Here is an example To reproduce:
```
'use strict';
const BitMEXClient = require('./index');
// See 'options' reference below
const client = new BitMEXClient({
  testnet: true,
  apiKeyID: "",
  apiKeySecret: "",
});
// handle errors here. If no 'error' callback is attached. errors will crash the client.
client.on('error', console.error);
client.on('open', () => console.log('Connection opened.'));
client.on('close', () => console.log('Connection closed.'));
client.on('initialize', () => console.log('Client initialized, data is flowing.'));

client.addStream('XBTUSD', 'order', function(data, symbol, tableName) {
  console.log(`Got update for ${tableName}:${symbol}. Current state:\n${JSON.stringify(data).slice(0, 100)}...`);
  // Do something with the table data...
});

client.addStream('*', 'order', function(data, symbol, tableName) {
  console.log(`Got update for ${tableName}:${symbol}. Current state:\n${JSON.stringify(data).slice(0, 100)}...`);
  // Do something with the table data...
});
```

In the example:
* the `client.addStream('XBTUSD',` subscription will output order data.
* the `client.addStream('*', ` will output empty arrays

**Comment by kevzettler** [comment]
On further look, it seems like this might not ever have been supported and would be a new feature.

**Comment by kevzettler** [comment]
Was reproducing on an outdated version. Cannot seem to repro on latest master.

**Comment by ldupisani** [comment]
I'm still having this issue on version 0.4.0

It doesn't happen on all orders... only when you create a new order instrument that you haven't used before. 

Disconnect and reconnect seems to solve the issue, until you go back to zero order again.
