### ISSUE TITLE
403 error when trying to create a new order, tried both Python and JS client

### ISSUE THREAD

**Issue by CryxxsRun** [BitMEX/api-connectors#171]
Hi, 

I tried to use the API to create a new order but always got 403 Forbidden Error from BitMEX. I also tried the operation to get account balance and it worked fine - I got my account balance with no 403 error. Just the one for creating new order kept throwing 403 error... I also tried the JS client and the problem remains. Is it a bug and is there any workaround?

**Comment by bitRomney** [comment]
I wrote a tutorial for python to make and amend orders here: https://link.medium.com/qDRwB8KgqT
