### ISSUE TITLE
Latest javascript version is not published to the npm registry

### ISSUE THREAD

**Issue by sampsasaarela** [BitMEX/api-connectors#172]
It seems that npm version is not in sync.

If I install the package by `npm install bit_mex_api` command and try to use the `userApi.userGetWallet`method, it will throw `userApi.userGetWallet is not a function` error.

But if I install it directly from git repository, it works:
`mkdir bit_mex_api; cd bit_mex_api; git init; git remote add -f origin https://github.com/BitMEX/api-connectors; git config core.sparseCheckout true; echo \"auto-generated/javascript\" >> .git/info/sparse-checkout; git pull --depth=1 origin master; cd ..; npm --no-save i ./bit_mex_api/auto-generated/javascript/`

In npm, it says that last version was published 2 years ago? https://www.npmjs.com/package/bit_mex_api

**Comment by jhob** [comment]
A third party has published the `bit_mex_api` module. It is not supported by BitMEX.

Try https://www.npmjs.com/package/bitmex-realtime-api instead.
