### ISSUE TITLE
How in the world do you use the generated Swagger clients?

### ISSUE THREAD

**Issue by mjesuele** [BitMEX/api-connectors#18]
Hey guys, love BitMEX but am having a bear of a time figuring out how to use this Swagger-generated `typescript-fetch` API client. For starters, where in the world do I enter my API key?

Any steps in the right direction would be greatly appreciated at this point.

Thanks!

**Comment by autemox** [comment]
Yes, the C# API is a big fat joke.  Nobody has ever figured out how to use it from what i can find after searching for a while online.

BitMex's position on this is: "See the source code for details.  This is free code and we supply it as a starting point, but do not support it."

I got about halfway complete with my project before realizing that I was using the wrong programming language...

Very misleading BitMex...

**Comment by bendelo** [comment]
Swagger does not understand HMAC authentication methods. Here is an implementation of authentication in C#:
https://github.com/BitMEX/api-connectors/blob/master/official-http/csharp/BitMEXAPI.cs
