### ISSUE TITLE
Might be new. but swagger is terribly complicated.

### ISSUE THREAD

**Issue by Indiana3714** [BitMEX/api-connectors#182]
I have a few sample commands to work off (Python):
```

from bitmex import bitmex
import simplejson as json

api_key = '' # your api key
api_secret = '' # your api secret

client = bitmex(test=True, api_key=api_key, api_secret=api_secret)
all_orders = client.Order.Order_getOrders(symbol='XBTUSD', reverse=True).result()
```
That will succesfully print out all orders, in reverse order since the account was created.
 Can someone show me **where**/in which file those functions are called from?

Been checking the auto generated file, digging through bravado to search where the Order class and Order_getOrders function is defined. No luck. Funny how complicated bitmex is when bitfinex API was a breeze.

Otherwise I won't know how to do the rest of my required coding etc, finding open position etc.

**Comment by ryanfox** [comment]
The client code is auto-generated based on swagger.json - there isn't any source file _per se_. You can use `dir()` to inspect the client, or e.g. `client.Order` to see what operations are available.

In general, the available functions correspond to the endpoints listed in [the API explorer.](https://testnet.bitmex.com/api/explorer/)

**Comment by tr91** [comment]
`print client.Order `or `print client.Order()` does nothing useful. Can you please be a bit clearer with your instructions? Thanks in advance!

**Comment by Pav0l** [comment]
Try this:

`print(dir(client.Order))`
