### ISSUE TITLE
Create Ruby client

### ISSUE THREAD

**Issue by hmasila** [BitMEX/api-connectors#183]
Create a Ruby Client for Bitmex, just like the ones we have for Python, C# and Node.
Include a complete documented readme for Ruby developers to interact with the Bitmex API

**Comment by hmasila** [comment]
If given a 👍 I can start immediately.

**Comment by ryanfox** [comment]
There is already an auto-generated client at https://github.com/BitMEX/api-connectors/tree/master/auto-generated/ruby
