### ISSUE TITLE
The C# API connector return an error 

### ISSUE THREAD

**Issue by itriad** [BitMEX/api-connectors#184]
Hello,
The C# API connector have an issue:
{"error":{"message":"Nonce must be a valid number and below 2^53. You sent: 9012932817249180.","name":"HTTPError"}}

I already change my API key and no Typo

Thanks for any help

**Comment by FairDeveloper** [comment]
This worked for me:

            DateTime yearBegin = new DateTime(1970, 1, 1);
            long nowticks = DateTime.UtcNow.Ticks + 60000;
            long dawnoftimeticks= yearBegin.Ticks;
            long non = (nowticks - dawnoftimeticks)/10000;
            return non;

Although I only just started with my Bitrex account but when I run the swample code to retrieve orders I get [] which is better than the error I did get :-)

**Comment by FairDeveloper** [comment]
* Bitmex... oops

**Comment by itriad** [comment]
its work with this 
`
 private long GetUnixTimeStamp()
        {
            long timestamp = (long)((DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds);

            return (timestamp);
        }
        // apiSecret, verb + path + expires + data
        private string Query(string method, string function, Dictionary<string, string> param = null, bool auth = false, bool json = false)
        {
            string paramData = json ? BuildJSON(param) : BuildQueryData(param);
            string url = "/api/v1" + function + ((method == "GET" && paramData != "") ? "?" + paramData : "");
            string postData = (method != "GET") ? paramData : "";

            HttpWebRequest webRequest = (HttpWebRequest)WebRequest.Create(domain + url);
            webRequest.Method = method;

            if (auth)
            {
                // string nonce = GetNonce().ToString();
                string expires = (GetUnixTimeStamp() + 60).ToString();

                //string message = method + url + nonce + postData;

                string message = method + url + expires + postData;


                byte[] signatureBytes = hmacsha256(Encoding.UTF8.GetBytes(apiSecret), Encoding.UTF8.GetBytes(message));
                string signatureString = ByteArrayToString(signatureBytes);

                // webRequest.Headers.Add("api-nonce", nonce);
                webRequest.Headers.Add("api-expires", expires);
                webRequest.Headers.Add("api-key", apiKey);
                webRequest.Headers.Add("api-signature", signatureString);
            }
`

**Comment by itriad** [comment]
its work with this:


` private long GetUnixTimeStamp()
        {
            long timestamp = (long)((DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds);

            return (timestamp);
        }
        // apiSecret, verb + path + expires + data
        private string Query(string method, string function, Dictionary<string, string> param = null, bool auth = false, bool json = false)
        {
            string paramData = json ? BuildJSON(param) : BuildQueryData(param);
            string url = "/api/v1" + function + ((method == "GET" && paramData != "") ? "?" + paramData : "");
            string postData = (method != "GET") ? paramData : "";

            HttpWebRequest webRequest = (HttpWebRequest)WebRequest.Create(domain + url);
            webRequest.Method = method;

            if (auth)
            {
                // string nonce = GetNonce().ToString();
                string expires = (GetUnixTimeStamp() + 60).ToString();

                //string message = method + url + nonce + postData;

                string message = method + url + expires + postData;


                byte[] signatureBytes = hmacsha256(Encoding.UTF8.GetBytes(apiSecret), Encoding.UTF8.GetBytes(message));
                string signatureString = ByteArrayToString(signatureBytes);

                // webRequest.Headers.Add("api-nonce", nonce);
                webRequest.Headers.Add("api-expires", expires);
                webRequest.Headers.Add("api-key", apiKey);
                webRequest.Headers.Add("api-signature", signatureString);
            }`

**Comment by itriad** [comment]
this work also thanks:

**Comment by itriad** [comment]
`
 private long GetUnixTimeStamp()
        {
            long timestamp = (long)((DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds);

            return (timestamp);
        }
`
then
`
if (auth)
            {
                // string nonce = GetNonce().ToString();
                string expires = (GetUnixTimeStamp() + 60).ToString();

                //string message = method + url + nonce + postData;

                string message = method + url + expires + postData;


                byte[] signatureBytes = hmacsha256(Encoding.UTF8.GetBytes(apiSecret), Encoding.UTF8.GetBytes(message));
                string signatureString = ByteArrayToString(signatureBytes);

                // webRequest.Headers.Add("api-nonce", nonce);
                webRequest.Headers.Add("api-expires", expires);
                webRequest.Headers.Add("api-key", apiKey);
                webRequest.Headers.Add("api-signature", signatureString);
            }
`

**Comment by ryanfox** [comment]
This should be fixed in master.

**Comment by Juxanli** [comment]
Newtonsoft.Json.JsonSerializationException: "Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[BitMEX.Position]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.

To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.

Path 'error', line 1, position 9."



 public List<Position> GetOpenPositions(string symbol)
        {
            var param = new Dictionary<string, string>();
            string res = Query("GET", "/position", param, true);
            return JsonConvert.DeserializeObject<List<Position>>(res).Where(a => a.Symbol == symbol && a.IsOpen == true).OrderByDescending(a => a.TimeStamp).ToList();
        }


pls help me
