### ISSUE TITLE
Example script in Python fails with 403 Error

### ISSUE THREAD

**Issue by j0ma** [BitMEX/api-connectors#191]
### Problem

Even after trying with two separately created API keys (both active, I checked my account), and also with/without VPN, the following script fails, returning a 403 Forbidden error code.

### Setup

- Python version: 3.6.4
- Bitmex library version: 0.2.2

### Reproducible example

The script `test.py`:

```
from bitmex import bitmex
import simplejson as json

api_key = [redacted]
api_secret = [redacted]

client = bitmex(test=False, api_key=api_key, api_secret=api_secret)
all_results = client.Quote.Quote_get(symbol='XBTUSD').result()
print(all_results)
```

throws the following error:

```
bravado.exception.HTTPForbidden: 403 Forbidden: Response specification matching http status_code 403 not found for operation Operation(Quote_get). Either add a response specification for the status_code or use a `default` response.
```

Any help in fixing this would be greatly appreciated.

**Comment by studyquant** [comment]
same error happens, do not know how to solve it

**Comment by combstraight** [comment]
I am getting the same error.

**Comment by degoor1975** [comment]
Same error. Why did they close this?

**Comment by Sean-Copeland** [comment]
I also have this error. Has anyone found a fix yet?

**Comment by degoor1975** [comment]
Sean,
this means your IP has been banned.
What I did was to use VPN  (SoftEther VPN) to connect to the bitmex site. I
corrected the code that made me banned and after 2-3 I could use my own IP
but only I was sure I was not getting banned for the new version of the
code.
Kind regards,
Marin
