### ISSUE TITLE
csharp example does not work. "Signature not valid."

### ISSUE THREAD

**Issue by Ajes1337** [BitMEX/api-connectors#192]
gives me this response: {"error":{"message":"Signature not valid.","name":"HTTPError"}}

the only thing I have changed is the domain to: "https://bitmex.com" instead of "https://testnet.bitmex.com"

and then added my key and secret which works with other bitmex-api's..

**Comment by bendelo** [comment]
https://bitmex.com/ is not a valid hostname. Where in the documentation did you see this?

**Comment by Ajes1337** [comment]
I actually cannot find that info https://www.bitmex.com/app/restAPI so I wrongly assumed to just remove "testnet" :/

is https://www.bitmex.com/api/v1/ more correct?

**Comment by bendelo** [comment]
Yes

**Comment by Ajes1337** [comment]
It still comes with same error with "https://www.bitmex.com/api/v1/"

![image](https://user-images.githubusercontent.com/11885892/43780311-90049e34-9a5a-11e8-99db-ff5afe3b4327.png)

![image](https://user-images.githubusercontent.com/11885892/43780338-a1cdfe08-9a5a-11e8-96dc-f1a8b4476025.png)

**Comment by bendelo** [comment]
Remove the `/api/v1/`...

**Comment by Ajes1337** [comment]
yay! "https://www.bitmex.com" works! so I was missing the www. ! xD damnit, ty! :)
