### ISSUE TITLE
delta-server build issues

### ISSUE THREAD

**Issue by bjschnei** [BitMEX/api-connectors#2]
From a clean repo I am getting the following build errors when running npm install starting with:

osx 10.11.16

In file included from ../src/bufferutil.cc:16:
../../nan/nan.h:473:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback

**Comment by STRML** [comment]
Hey @bjschnei,

Sorry about that! That particular project was a little old and needed some updating. It should run out of the box now.

**Comment by bjschnei** [comment]
Is this the preferred way of integration, should I write my own websocket integration, or is there another library that is better?

**Comment by STRML** [comment]
That's the preferred way, but I'd recommend giving the code a read so that you understand it, in case you want to add your own custom functionality.
