### ISSUE TITLE
bitmex-realtime-api: Not getting any data from the "order" subscription.

### ISSUE THREAD

**Issue by Madward** [BitMEX/api-connectors#203]
On bitmex-realtime-api@0.4.0, subscribing to the "order" endpoint works, but never returns any data as orders get cancelled or amended.

```
let symbol="XBTUSD";		
client.addStream(symbol, 'order', function (data, symbol, tableName) {
	if (!data.length) return;
	
	console.log(data);
});
```

Snippet tried with both a real symbol, and "*" wildcard, over a period of time long enough to have a few amends and cancels.

The subscriptions still get confirmed in logs:
 ```
{"op":"subscribe","args":"order:XBTUSD"}
{"op":"subscribe","args":"order:ETHUSD"}
```

Is there some piece of information I missed about why no information would come through? 
After reading other issues, I even tried to subscribe after sending an order to make sure order book wasn't empty, but to no avail.

Thanks in advance,

MadWard.

**Comment by Madward** [comment]
Update: I tried to start the subscription 5 seconds after putting in the first order, and order data is coming through.

The issue thus seems to be: "order" stream doesn't send any data if started when the order book was empty.

I will keep my problem fixed like this until a fix for this comes up.

**Comment by smalljiny** [comment]
I was faced with it issue this morning.
It looks like a bug cause using 'reduce' function instead of 'for' statement.
I fixed the code for init value on 'nodejs/lib/createSocket.js' as below:
It looks like working well.

**v0.4.0**
```
function emitSplitData(emitter, data) {
  ...
  // Generate data by symbol
  const symbolData = data.data.reduce((accumulator, currentValue) => {
    if (accumulator.hasOwnProperty(currentValue[filterKey])) {
      accumulator[currentValue[filterKey]].push(currentValue);
    } else {
      accumulator[currentValue[filterKey]] = [currentValue];
    }
    return accumulator;
  }, {});
  ...
}
```

**fixed:**
```
function emitSplitData(emitter, data) {
  ...
  // Generate data by symbol
  const matchingStreams = emitter._listenerTree[table];
  const initValue = _.mapValues(matchingStreams, () => []);
  const symbolData = data.data.reduce((accumulator, currentValue) => {
    if (accumulator.hasOwnProperty(currentValue[filterKey])) {
      accumulator[currentValue[filterKey]].push(currentValue);
    }
    return accumulator;
  }, initValue);
  ...
}
```

**Comment by bretton** [comment]
> I was faced with it issue this morning.
> It looks like a bug cause using 'reduce' function instead of 'for' statement.
> I fixed the code for init value on 'nodejs/lib/createSocket.js' as below:

this works for me!
