### ISSUE TITLE
How to using api to know Long pay short or Shor pay Long in funding rate?

### ISSUE THREAD

**Issue by ndphuong** [BitMEX/api-connectors#204]
Hi,
I have using GET /instrument/active to get funding rate but don't know Long pay Short or Short pay Long

**Comment by Madward** [comment]
Hi @ndphuong ,

As you saw, you can get the "funding rate" value in /instrument or /instrument/active.
To know whether "Longs pay Shorts" or "Shorts pay Longs", it's relatively simple. Quote from Bitmex website:

> When the Funding Rate is positive, longs pay shorts. When it is negative, shorts pay longs. See examples.

**Source**: https://www.bitmex.com/app/perpetualContractsGuide#Funding

So just look at the sign of the value! If it's positive then "Longs pay shorts", if it's negative then "Shorts pay longs".

Best of luck,

MadWard.

**Comment by ryanfox** [comment]
Correct. Closing.
