### ISSUE TITLE
Failed to load - CORS error

### ISSUE THREAD

**Issue by architkshk** [BitMEX/api-connectors#206]
Failed to load https://testnet.bitmex.com/api/v1/user/walletHistory: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'localhost:3000/' is therefore not allowed access.
Please help.

**Comment by architkshk** [comment]
@STRML pls help.

**Comment by STRML** [comment]
We don't support running these queries directly in the browser as adding these CORS headers would be a security risk. If you need to access non-GET methods via the browser, proxy them with your local server.

**Comment by adam-hanna** [comment]
Would Bitmex possibly consider adding JSONP support? This wouldn't require any changes to CORS, and can be done safely with relative ease. It would allow front-end clients to consume the unsecured Bitmex endpoints without the need for a proxy.

**Comment by STRML** [comment]
JSONP would present significant XSS risk to all BitMEX customers while only providing very marginal benefit to a few who are unwilling to run a proxy or to use a proper webserver to host their application. I wouldn't recommend nor portend to support running code from a file:/// url.

Arguably this could be added for pricing info only but I don't believe the small benefit outweighs the cost of implementation, as the implementation would require significant test maintenance to ensure JSONP is not ever allowed for any sensitive endpoints.

**Comment by gapspt** [comment]
>If you need to access non-GET methods via the browser

@STRML it seems that the GET methods are also blocked now, right?
