### ISSUE TITLE
quote api returning 403 error - PLEASE FIX

### ISSUE THREAD

**Issue by pigslayer12** [BitMEX/api-connectors#219]
hello, why is nobody fixing this???

**Comment by STRML** [comment]
Please see #141 #196 #156

**Comment by beeflowers287** [comment]
> hello, why is nobody fixing this???

> as workaround, i am using OrderBook/L2

The #BitMEX API is fragmented at best, verging on broken. You can barely get a public price quote (they turned off that endpoint sometime in 2018) so I wanted to share an all in one I've hacked together from their api over the past 6 months for CT and my sanity:

1/ Price
Work around to get the current price is using another endpoint. orderBook/L2 python:

```
import requests, json
response = requests.get("https://www.bitmex.com/api/v1/orderBook/L2?symbol=eth&depth=1 …").json()
ether_bid_price = response[1]['price']
```

2/ Everything else
Digging thru the open Issues of the bitmex github repo this is the best resource I found to help you place/ammend/cancel orders without downloading their sorry excuse sample market maker bot: https://github.com/mazmex7/BitMEX-API-python … 
Thank you @mazmex7
