### ISSUE TITLE
How can I save the data in csv? 

### ISSUE THREAD

**Issue by Kalelv45** [BitMEX/api-connectors#233]
In the api explorer documentation page, I have seen this line: 
?_format=csv

That I implemented like this: 
BitMEXWebsocket(endpoint="https://testnet.bitmex.com/api/v1/format=csv"....

How can I save the data I request into a csv file? 
Thanks.

**Comment by ryanfox** [comment]
The `format` parameter described in the API explorer refers to the format the data in the HTTP response. The connectors all expect JSON responses.

If you want to save data in CSV format, various languages have support for that, for example python's [csv module.](https://docs.python.org/3/library/csv.html) Saving data to disk is beyond the scope of this repository though.
