### ISSUE TITLE
authentication problems

### ISSUE THREAD

**Issue by leogi222** [BitMEX/api-connectors#239]
I struggled a while with this signature problem so I thought I would share how I fixed it:

I was using curl command line to validate my authentication.

I typically would send the following command out:

curl -X POST --data "POST/api/v1/order?{\"symbol\":\"XBTUSD\",\"price\":6000.0,\"clOrdID\":\"Lionel01\",\"orderQty\":1}1538299706" https://testnet.bitmex.com/api/v1/ --header "api-expires:1538299706" --header "api-key:pH0grJYbGKEtyilYRd3H_pYz" --header "api-signature:ce05e4d83a8de0f46b08b090899f86085bd7c80428e35190468a05a3a5815767" --header "Content-Length:95" --header "Content-Type:multipart"

the response was invariably:  {"error":{"message":"Signature not valid.","name":"HTTPError"}}

There were several problems.

1 - the data portion has to have only the JSON string, the rest of the information required is included in headers
2- Once the data only had the JSON string, the content_Type could be set to application/json
3 - Content-Length is not necessary

hope that will help someone else

**Comment by ryanfox** [comment]
Thanks for the info. Closing, as this is not an issue.
