### ISSUE TITLE
Ruby config example

### ISSUE THREAD

**Issue by hakunin** [BitMEX/api-connectors#24]
Hi,
I am trying to figure out how to conntect to the API for the first time.

The readme says to use:
```
SwaggerClient.configure do |config|
  # Configure API key authorization: apiKey
  config.api_key['api-key'] = 'YOUR API KEY'

  # TODO
  # Configure API key authorization: apiNonce
  # config.api_key['api-nonce'] = 'YOUR API KEY'

  # Configure API key authorization: apiSignature
  config.api_key['api-signature'] = 'YOUR API KEY'

  # TODO
end
```

The docs say that signature is this:
```
 signature = HEX(HMAC_SHA256(apiSecret, verb + path + str(nonce) + data))
```

However, that doesn't look like something one puts in a config, just like the nonce that changes for each request. Can we get an example of config + making a an API request?

**Comment by ryanfox** [comment]
Swagger doesn't support BitMEX's authentication scheme out of the box. The [BitMEx documentation on authentication](https://testnet.bitmex.com/app/apiKeysUsage#Authenticating-with-an-API-Key) describes the auth process.

You can extend the adapter to support auth - [here is an example in C#.](https://github.com/BitMEX/api-connectors/blob/aaa6781f156ca97be56149d66cabae227fdfd9cb/official-http/csharp/BitMEXAPI.cs#L85-L95)

There are some endpoints that don't require authentication - you can connect to those without authenticating: [websockets](https://testnet.bitmex.com/app/wsAPI#Subscriptions) or [REST.](https://testnet.bitmex.com/api/explorer/)
