### ISSUE TITLE
Authentication Bug

### ISSUE THREAD

**Issue by chenyibo1029** [BitMEX/api-connectors#243]
api-connectors/official-ws/python/util/api_key.py

def generate_nonce():
    return int(round(time.time() * 1000))

This is the old version. According to the note in https://www.bitmex.com/app/apiKeysUsage  
Note: Previous versions of this document descripted an api-nonce value, which is a value that should increase between the bounds of 0 and 2^253. This scheme, while still supported, has significant problems with multithreaded clients and should not be used. Do not use it for new applications.

The old version should change to  

def generate_nonce():
    return int(time.time()) + 5

**Comment by ryanfox** [comment]
Thank you for the report. This should be fixed with the latest update to https://github.com/BitMEX/api-connectors/tree/master/official-ws
