### ISSUE TITLE
On C# code returns "Invalid API Key"

### ISSUE THREAD

**Issue by Sergey-A-Dvortsov** [BitMEX/api-connectors#25]
The example works well. It is necessary to change "https://testnet.bitmex.com" on
 "https://www.bitmex.com".

**Comment by ryanfox** [comment]
API keys are associated with either `testnet` or `www`. Depending on which you want to connect to, you need to create a key on the appropriate server and specify which in your url.

**Comment by VangYangPao** [comment]
I completed real-time data extract in Bitmex.com.
I will help everyone.
In the future, Help me very much.
moderndevgroup@gmail.com
Thank you for your project!
👍
