### ISSUE TITLE
How to get historical data for the Python client?

### ISSUE THREAD

**Issue by AkshaySapra** [BitMEX/api-connectors#263]
I want to be able to trade using RSI levels, using a Python client. It seems you can only access current data, such as current Quote. I want to be able to access historical data so that I can calculate RSI (or I want the current RSI). Is there a way I can do this? Or is there a way I can do this using another language other than Python?

**Comment by Madward** [comment]
"Quote" endpoint is unavailable for now but might come back in the future. See #141 #196 #156.

You can get still get BitMEX trade (not quote) data from the Trade endpoint.

**Comment by AkshaySapra** [comment]
This seemed to work for me:
client.Trade.Trade_getBucketed(symbol="XBTUSD", binSize="5m", count=10
