### ISSUE TITLE
Can't call tradeHistory API from node-js

### ISSUE THREAD

**Issue by aniketbehera** [BitMEX/api-connectors#27]
I'm trying to retrieve tradeHistory data. 

I've picked up straight from the provided nodejs example to authenticate API

I see "Signature not valid." error. What am I doing wrong?

```
var request = require('request');
var crypto = require('crypto');

var apiKey = "";
var apiSecret = "";

var verb = 'GET',
  path = '/api/v1/execution/tradeHistory',
  expires = new Date().getTime() + (60 * 1000), // 1 min in the future
  data = '';

// Pre-compute the postBody so we can be sure that we're using *exactly* the same body in the request
// and in the signature. If you don't do this, you might get differently-sorted keys and blow the signature.
//var postBody = JSON.stringify(data);

var signature = crypto.createHmac('sha256', apiSecret).update(verb + path + expires + postBody).digest('hex');

var headers = {
  'content-type' : 'application/json',
  'Accept': 'application/json',
  'X-Requested-With': 'XMLHttpRequest',
  // This example uses the 'expires' scheme. You can also use the 'nonce' scheme. See
  // https://www.bitmex.com/app/apiKeysUsage for more details.
  'api-expires': expires,
  'api-key': apiKey,
  'api-signature': signature
};

request.post({
    headers: headers,
    url:'https://www.bitmex.com'+path,
    method: verb//,
    //body: postBody
  },
  function(error, response, body) {
    if (error) { console.log(error); }
    console.log(body);
  }
);
```

**Comment by bendelo** [comment]
Are you setting apiKey and apiSecret?

**Comment by aniketbehera** [comment]
Yes

On Oct 24, 2017 05:31, "Ben Delo" <notifications@github.com> wrote:

Are you setting apiKey and apiSecret?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BitMEX/api-connectors/issues/27#issuecomment-338830867>,
or mute the thread

**Comment by bendelo** [comment]
The problem is that you are signing a `GET` but actually calling `request.post()` so sending a `POST`.

Here is a more generic function that handles GET/POST/PUT/DELETE:
https://github.com/bendelo/hedge-report/blob/master/index.js#L9

**Comment by aniketbehera** [comment]
Thanks for pointing that out Ben.

I updated the request section to

request({
    headers: headers,
    url:'https://www.bitmex.com'+path,
    method: verb//,
    //body: postBody
  },


I still get the same error though.

**Comment by bendelo** [comment]
What are you using as `postBody`?

**Comment by aniketbehera** [comment]
Not sending the body parameter (its commented out above)

**Comment by bendelo** [comment]
How are you calculating the signature then? This line would not compile:
```
var signature = crypto.createHmac('sha256', apiSecret).update(verb + path + expires + postBody).digest('hex');
```

Anyway, I have emailed you a working example with your API key.

**Comment by aniketbehera** [comment]
Ah, that was the problem. I was srtingifying an empty string. Thanks!
