### ISSUE TITLE
node-swagger API Example with Swagger 3.x

### ISSUE THREAD

**Issue by ecooperman** [BitMEX/api-connectors#278]
Is anyone planning on updating this example to use Swagger 3?  It seems to work properly in most cases but client.Order.Order_new doesn't work at all - I keep getting an exception about a "S" in an invalid location in the JSON that's sent to the Bitmex endpoint.  I will update this later when I test again to put the exact exception, but it should be fairly obvious rather quickly with a test.  Has anyone dealt with this or successfully gotten past it?  For now I'll probably downgrade to Swagger 2 but that seems silly.

In addition to the issue with client.Order.Order_new, there also a different mechanism for Swagger 3 to do authentication that's a little more complex, so it would be nice to have an example of that as well.  If I happen to continue messing around with it and get either of these issues resolved, I'll be sure to post here.

I realize the last update to the swagger-node example was almost exactly a year ago, but if anyone is watching these issues I'd greatly appreciate any insight.

Thanks in advance!

Edit: Just a quick note that I tried using Swagger 2 for the Order_new endpoint and that didn't even work as I have another call to retrieve the expiration for each symbol which started failing (I got an error about an authorization variable that couldn't be set).  I think I'm just going to use the Request package and start to build my own API since it doesn't seem like the Swagger spec is being followed properly at this point...

If anyone thinks I'm mistaken please let me know, I would love to understand what I'm doing wrong if I am, in fact, doing something wrong.

**Comment by taseenb** [comment]
The Swagger client seems broken and the example is not compatible with version 3. Last version is 3.8+! It'd be great if you could update the json and the example please!

**Comment by ecooperman** [comment]
FYI that I built my own API using standard Node requests and that worked well for me, all of my calls are working properly now. While using a standard spec like swagger would be nice, if it’s not maintained properly then it’s not a viable option.

**Comment by taseenb** [comment]
@ecooperman can you post the code you used to build the headers? I keep receiving a 401 error ("unauthorised") with and without Swagger.

**Comment by ecooperman** [comment]
Yeah, I used that example to do it, though it took me a minute to get the signature correct.   I wasn't able to get the signature correct using the example, so I looked at Bitmex's docs and their example, which worked properly: https://www.bitmex.com/app/apiKeysUsage

Here's some code I wrote that abstracts a lot of this and can be used with all API calls.  I didn't put all the config variables in here, but you ought to be able to figure them out, hope it helps:

```
let request = require('request');
let crypto = require('crypto');

let anonymousHeaders = {
    "Content-Type" : "application/json",
    "X-Requested-With": "XMLHttpRequest"
};

executeTrade: function(symbol, qty, price, callback) {
        let path = BitmexConfig.apiUrl + "order";
        let data = {
            symbol: symbol,
            orderQty: qty,
            price: price,
            ordType: "Limit",
            execInst: "ParticipateDoNotInitiate"
        };

        this.executePostAuth(data, path, function(json) {
            console.log(json);
            if (json.error !== undefined) {
                callback(false, json.error.message);
            } else {
                callback(true, json);
            }
        });
},

executeAuth: function(verb, data, path, callback) {
        // Pre-compute the postBody so we can be sure that we're using *exactly* the same body in the request
        // and in the signature. If you don't do this, you might get differently-sorted keys and blow the signature.
        let postBody = JSON.stringify(data);
        let headers = this.getAuthHeaders(verb, path, postBody);
        const requestOptions = {
            headers: headers,
            url: baseUrl + path,
            method: verb,
            body: postBody
        };

        console.log("executeAuth Request Options:");
        console.log(requestOptions);

        this.execute(requestOptions, callback);
},

getAuthHeaders: function(verb, path, postBody) {
        let headers = anonymousHeaders;
        let expires = this.getExpires();
        let signature = this.getSignature(verb, path, expires, postBody);
        headers['api-key'] = BitmexConfig.apiKey;
        headers['api-signature'] = signature;
        headers['api-expires'] = expires;
        headers['Content-Length'] = Buffer.byteLength(postBody);
        return headers;
},

getSignature: function(verb, path, expires, postBody) {
        return crypto.createHmac('sha256', BitmexConfig.apiSecret).update(verb + path + expires + postBody).digest('hex');
},

getExpires: function() {
        return Math.round(new Date().getTime() / 1000) + 60; // use seconds instead of milliseconds and round to nearest second
}
```

**Comment by STRML** [comment]
We have updated to node-swagger 3 in a145354.
