### ISSUE TITLE
 Exception: 400 Bad Request: Trailing Stop Format

### ISSUE THREAD

**Issue by cofibit** [BitMEX/api-connectors#282]
Need some help here I was trying to implement a trailing stop loss but I've been getting 

` Exception: 400 Bad Request: {'error': {'message': 'Invalid price', 'name': 'HTTPError'}}`

Here's my bulk order request for a buy limit order with trailing stop. Note I just use xxx for the price. 

`[{'clOrdID': clOrdID,
 'orderQty': 1000,
 'price': xxx,
 'side': 'Buy',
 'symbol': 'XBTUSD',
  'ordType': 'Limit',
 'execInst': 'ParticipateDoNotInitiate'},
 {'clOrdID': clOrdID,
 'symbol': 'XBTUSD',
 'orderQty': 1000,
 'ordType': 'StopLimit',
 'pegOffsetValue': -200,
 'pegPriceType': 'TrailingStopPeg',
 'execInst': 'LastPrice'}]`

TIA

**Comment by cofibit** [comment]
Figured it out closing this one

**Comment by addodelgrossi** [comment]
What was the solution ?
