### ISSUE TITLE
How to clear the memory of the Delta Server once in a while?

### ISSUE THREAD

**Issue by Johannnnes** [BitMEX/api-connectors#30]
As stated in the manual, the Delta Server "keeps a copy of all public exchange data in memory"

I would like to clear this memory when receiving new data. For example, every 5 minutes.

Can you please tell me how this should be done?

**Comment by Yoganesh** [comment]
Somehow related: adding parameters to the URL(anything after &) doesn't change what is returned:

http://localhost:4444/trade?symbol=XBTUSD&count=500&reverse=true

**Comment by wrhnks** [comment]
Have you found a workaround for this issue? I'm unable to clear the data, leading to memory overflow after few days.

**Comment by Yoganesh** [comment]
I have not. I guess the only way is by restarting the server.
