### ISSUE TITLE
AttributeError in config

### ISSUE THREAD

**Issue by klaasv12** [BitMEX/api-connectors#31]
`Traceback (most recent call last):
  File "\bitmex2.py", line 8, in <module>
    swagger_client.configuration.api_key['api-key'] = 'XXXXX'
AttributeError: module 'swagger_client.configuration' has no attribute 'api_key'`

Anyone any idea why it is not accepting this?

**Comment by tuerkasten** [comment]
got the same one!

**Comment by ryanfox** [comment]
This looks like the auto-generated python client. You should use the one in `official-http/`: https://github.com/BitMEX/api-connectors/tree/master/official-http/python-swaggerpy

It can also be installed via `pip install bitmex`.
