### ISSUE TITLE
What's Pegged order?

### ISSUE THREAD

**Issue by sunfu12** [BitMEX/api-connectors#314]
I see Pegged order in ordType instruction, but I cannot find what it is. What's Pegged order?

**Comment by STRML** [comment]
Pegged orders are a work-in-progress feature that is not ready for public use yet. We will make an announcement and document it when it is ready.

**Comment by developing-coder** [comment]
https://blog.bitmex.com/api_announcement/deprecation-of-lastpeg-and-midpricepeg-order-types-and-change-to-order-feed-messages/

This article seems to indicate that pegged orders are available by now. However, any attempt in creating one returns "Unsupported ordType".

Thanks

**Comment by STRML** [comment]
BitMEX will be releasing documentation on this soon.

In the meantime, you can test on Testnet by sending `ordType: "Pegged"`, `execInst: "Fixed"`, and a `pegPriceType` of `PrimaryPeg` or `MarketPeg`.
