### ISSUE TITLE
simple question

### ISSUE THREAD

**Issue by mrktmr** [BitMEX/api-connectors#315]
Looking at the GET /position request, what does the 'columns' field mean. The "For example, send ["columnName"]." is not very helpful.

**Comment by STRML** [comment]
`columns` refers to which columns (like columns in an Excel document) you want the endpoint to return. So if, say, you only are going to use one field, you can use this to reduce the payload size, which should make your app slightly faster and use less data.

Here's an example using a public endpoint: https://www.bitmex.com/api/v1/trade?symbol=XBTUSD&columns=size
