### ISSUE TITLE
API authentication problem

### ISSUE THREAD

**Issue by Denebulas** [BitMEX/api-connectors#32]
My code always receives "Signature not valid" Am I doing something wrong ?
I tested the encoding function using the example. no problem.
I used a simple JSON string to be sure I am signing the same string that is sent
I don't know what else to try !
I tested the request using httpbin.org. result:
-------------------------
{ "args": {}, "data": "{'symbol':'XBTUSD','orderQty':50}", "files": {}, "form": {}, "headers": { "Accept-Encoding": "gzip", "Api-Key": "vYL7jyiOSVuQ4VansuTSQpeB", "Api-Nonce": "1513088793216", "Api-Signature": "395ac5844b5de5e8147da21816195deea4c9fc0042a40d6a558326edf6fb2fbe", "Connection": "close", "Content-Length": "33", "Content-Type": "application/json; charset=utf-8", "Host": "httpbin.org", "User-Agent": "okhttp/2.7.5" }, "json": null, "origin": "93.37.83.198", "url": "http://httpbin.org/post" }
-------------------------

Here is my java code using OkHttp client:

OkHttpClient client = new OkHttpClient();
private long lastnonce;

public void orderjson() {
    String base_url = "http://www.bitmex.com";
    String path = "/api/v1/order";
    String json = "{\"symbol\":\"XBTUSD\",\"orderQty\":50,\"price\":219.0}";
    String response;
    String verb = "POST";
    lastnonce = System.currentTimeMillis();

    //////// TEST encode like on website
    //        String json = "";
    //        String response;
    //        String verb = "GET";
    //        String path = "/api/v1/instrument?filter=%7B%22symbol%22%3A+%22XBTM15%22%7D";
    //        lastnonce = 1429631577690L;
    //         bitmex_secret="chNOOS4KvNXR_Xq4k4c9qsfoKWvnDecLATCRlcBwyKDYnWgO";

    String signa = encode(bitmex_secret, verb + path + lastnonce + json);
    try{
        response = post(base_url + path, json, signa);
        System.out.println(response);
    }
    catch (IOException ex){
        ex.printStackTrace();
    }
}

String post(String url, String json, String signature) throws IOException {
    final MediaType JSON = MediaType.parse("application/json; charset=utf-8");
    RequestBody body = RequestBody.create(JSON, json);
    Request request = new Request.Builder().url(url).post(body).addHeader("api-key", bitmex_apikey)
            .addHeader("api-nonce", lastnonce + "").addHeader("api-signature", signature).build();

    Response response = client.newCall(request).execute();
    return response.body().string();
}

public static String encode(String key, String data) {
        try{
            Mac sha256_HMAC = Mac.getInstance("HmacSHA256");
            SecretKeySpec secret_key = new SecretKeySpec(key.getBytes("UTF-8"), "HmacSHA256");
            sha256_HMAC.init(secret_key);

            return Hex.encodeHexString(sha256_HMAC.doFinal(data.getBytes("UTF-8")));
        }
        catch (InvalidKeyException ex){
            ex.printStackTrace();
        }
        catch (NoSuchAlgorithmException ex){
            ex.printStackTrace();
        }
        catch (UnsupportedEncodingException ex){
            ex.printStackTrace();
        }
        catch (IllegalStateException ex){
            ex.printStackTrace();
        }
        return "";
    }

**Comment by ryanfox** [comment]
What are you trying to do when the error occurs? Do you have a way to reproduce the error?

**Comment by Denebulas** [comment]
Fixed. thank you

**Comment by Denebulas** [comment]
If I remember well I took the orderbook data and not the quote returned values.

**Comment by zhengmaohujima** [comment]
now I wrote the Java test according to the official instructions, can pass the verification when there is no parameter, and fail when adding parameters,Are you the same? Do you have a corresponding solution?

**Comment by Denebulas** [comment]
that api call is not working anymore by design.
use the other call. no other solution.

**Comment by zhengmaohujima** [comment]
Can you tell me what to do? Thank you.I also feel that there is a problem with "Full sample calculation".

**Comment by Denebulas** [comment]
that call was shut down by bitmex.
use 
https://www.bitmex.com/app/restAPI#OrderBookL2
or
https://www.bitmex.com/app/wsAPI
