### ISSUE TITLE
How to install on python 3?

### ISSUE THREAD

**Issue by matthewli1409** [BitMEX/api-connectors#33]
Hi,

What command do I use to install swagger_client? I have tried pip install swagger_client and it does not work.

Thanks

**Comment by STRML** [comment]
You probably want this README: https://github.com/BitMEX/api-connectors/tree/498fa7443a0cb3fb46b2bdb3befb8cdebd4164d7/official-http/python-swaggerpy

**Comment by pangjonny** [comment]
Try setup tools instead
Go to the directory where you have setup.py and then
`python setup.py install`
then
`import swagger_client`

**Comment by ryanfox** [comment]
You can now `pip install bitmex` as well.
