### ISSUE TITLE
How to get WebSockets Live stream data using PHP?

### ISSUE THREAD

**Issue by ragupathis** [BitMEX/api-connectors#330]
Hello Everyone,

We are trying to get a BitMex live stream data by using WebSocket through PHP. we can able to connect WebSocket but we can't able to get the live streamed data from BitMex. 

Is there any solution to get BitMex WebSocket live stream data using PHP ????

Here is snippet we are using to connect BitMex WebSocket.

```

<?php

require('../../../autoload.php');
use WebSocket\Client;
$client = new Client("wss://testnet.bitmex.com/realtime?subscribe=instrument:XBTUSD");
echo $client->receive();
Thanks in advance. 

```

Here is the screenshot, that says BitMex WebSocket is connected.
![bitmex-ws](https://user-images.githubusercontent.com/5587483/54992461-5a252680-4fe5-11e9-8634-855510d546d2.png)

**Comment by parmonov98** [comment]
Hey, dude. why did you close? Did you get worked? if yes, let me how did you do?
please.
