### ISSUE TITLE
Node-fetch POST request Signature not valid

### ISSUE THREAD

**Issue by Number16BusShelter** [BitMEX/api-connectors#335]
Hello,

So I've checked my key permissions and the way I make a signature.  Everything seems ok, but I can not make a request to the 'www.bitmex.com' as for 'testnet.bitmex.com' and keep getting 'Signature not valid' on my POST requests, therefore all GET requests are working fine.

I've doublechecked issues page but it didn't help. 

Here's how it create a signature:
```
  let query = '';
  let postBody = '';
  if (verb === 'GET') {
    query = '?' + qs.stringify(data);
  } else {
    postBody = JSON.stringify(data);
  }
 
const signature = crypto.createHmac('sha256', apiSecret)
    .update(verb + apiRoot + endpoint + query + expires + postBody).digest('hex');
```

And the URL is built this way:
```
  if (verb !== 'GET') requestOptions.body = postBody; 
  const url = req_url + apiRoot + endpoint + query;
```

What I'm thinking about is that crypto works incorrectly.

If there are any updates on this issue, please, let me know

**Comment by kitt-th** [comment]
have you set the headers?

signature = crypto.createHmac('sha256', apiSecret).update(verb + path + expires + postBody).digest('hex');

  var headers = {
    'content-type' : 'application/json',
    'Accept': 'application/json',
    'X-Requested-With': 'XMLHttpRequest',
    'api-expires': expires,
    'api-key': apiKey,
    'api-signature': signature
  };

  const requestOptions = {
    headers: headers,
    url: requestURL,
    method: verb,
    body: postBody
  };
