### ISSUE TITLE
Please republish node.js websocket connector to npm

### ISSUE THREAD

**Issue by andersea** [BitMEX/api-connectors#34]
I see there are some bugfixes in the git repository for the node.js ws connector (bitmex-realtime-api).

Specifically I need the expanded `const noSymbolTables` from the repo.

The published package only has

    const noSymbolTables = BitMEXClient.noSymbolTables = [
      'margin',
      'chat'
    ];

Could you republish when you get a round tuit?

**Comment by Bomper** [comment]
@STRML: pretty please. Normally we could just add

    "bitmex-realtime-api": "https://github.com/BitMEX/api-connectors/",

in `package.json`, but [npm doesn't support repos where package.json isn't in the root directory](https://github.com/npm/npm/issues/2974#issuecomment-285859377).

**Comment by STRML** [comment]
Published `0.2.4`.
