### ISSUE TITLE
Signature not valid (VBA)

### ISSUE THREAD

**Issue by Bouty25** [BitMEX/api-connectors#356]
Hi,

I have an issue when I try to use to retreive some data in excel throuh VBA code.
I used the following as basis: https://github.com/BitMEX/api-connectors/tree/master/official-http/vba
and it works, I can login and place an order (testnet).

I now try to retreive the orderbook but I always get "Signature not valid" as response.
Can you please help understand what's I am doing wrong?

Thanks in advance,

```
Sub getorderbook2()

Dim Json, httpObject As Object
Dim nonce As Double
Dim verb, apiKey, apiSecret, Signature, symbol, url, getdata, replytext, depth As String
Dim nonceStr As String
Dim jsoncount As Long

' Set monotonically (w time) increasing nonce
nonce = DateDiff("s", "1/1/1970", Now)

' Set api key and secret
apiKey = "aaa"
apiSecret = "bbb"

' Build query
symbol = "XBTUSD"
depth = 3

verb = "GET"
url = "/api/v1/orderbook/L2"
getdata = "symbol=" & symbol & "&depth=" & depth

' Stringize nonce
nonceStr = nonce

' Compute signature using hexhash script
Signature = HexHash.HexHash(verb + url + nonceStr + getdata, apiSecret, "SHA256")

' Set up HTTP req with headers
Set httpObject = CreateObject("MSXML2.XMLHTTP")
httpObject.Open "GET", "https://testnet.bitmex.com" & url, False
httpObject.setRequestHeader "Content-Type", "application/application/x-www-form-urlencoded"
httpObject.setRequestHeader "api-nonce", nonceStr
httpObject.setRequestHeader "api-key", apiKey
httpObject.setRequestHeader "api-signature", Signature
httpObject.Send (getdata)

' Catch response
replytext = httpObject.ResponseText
MsgBox (replytext)

```

**Comment by tanevanwifferen** [comment]
```
Signature = HexHash.HexHash(verb + url + nonceStr + getdata, apiSecret, "SHA256")
```

For GetOrders in the library (which probably uses the same signature check as getorderbook) I removed the GET parameters from the signature. This seemed to solve the problem for me.

```
Signature = HexHash.HexHash(verb + url + nonceStr, apiSecret, "SHA256")
```

**Comment by tanevanwifferen** [comment]
Actually, ignore my posts, my issue seems to be totally unrelated (something with the c# httpclient rewriting my URL) and the fix works, but isn't supposed to work..

**Comment by tanevanwifferen** [comment]
Actually, ignore my posts, my issue seems to be totally unrelated (something with the c# httpclient rewriting my URL) and the fix works, but isn't supposed to work..

**Comment by Bouty25** [comment]
Hi,
thanks for you answer and idea.
Issue fixed with this answer:
https://stackoverflow.com/questions/56405195/signature-not-valid-when-getting-api-data-vba-excel
