### ISSUE TITLE
User_logout not working

### ISSUE THREAD

**Issue by pigslayer12** [BitMEX/api-connectors#365]
Hello, I havent had any problems with any other commands but for some reason user_logout (User.User_logout()) doesn't seem to do anything.

I am not getting any errors and it returns None.

I assumed this would log me out of any browser sessions but nothing seems to happen.

Thanks in advance for any help!

**Comment by STRML** [comment]
Logout does not have any affect when sent via API key, it invalidates the current session from which the request is sent, which only applies to login sessions.

User.logoutAll(), however, will invalidate all non-API sessions.
