### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by aadon94** [BitMEX/api-connectors#366]
Seems there might be a memory leak in here somewhere. My programs been crashing, checked the memory usage and it increases with every loop. After testing it a bit I've realised the culprit is
 `api = bitmex.bitmex(api_key, api_secret)`.

If this line in commented out the memory usage is fine, if not it keeps climbing.

**Comment by STRML** [comment]
I'm sorry, but we can't reconstruct this without much more data about your application and specifically about which adapter you are using.

Please re-open if you have this information.
