### ISSUE TITLE
Incorrect comment official nodejs-ws client for addStream method

### ISSUE THREAD

**Issue by bvdaakster** [BitMEX/api-connectors#369]
Hi,

I believe there's an error in the comment above the addStream method:
https://github.com/BitMEX/api-connectors/blob/master/official-ws/nodejs/index.js#L122
```js 
  *
  * If no tableName is passed, will subscribe to all public tables.
  *
```
Reading this it sounds like it'd be possible to not pass any `tableName`. Further down the code however I came across this:
```js
  else if (client.streams.all.indexOf(tableName) === -1) {
    throw new Error('Unknown table for BitMEX subscription: ' + tableName +
      '. Available tables are ' + client.streams.all + '.');
  }
```
Wouldn't a call to `indexOf` for `undefined` or `null` return `-1` here, making it impossible to pass nothing for the `tableName` argument?

Kr,
Bas

**Comment by AdamFeher2400** [comment]
You can use * for tableName to subscribe to all tables.

**Comment by STRML** [comment]
Thanks, we've fixed the comment.
