### ISSUE TITLE
NodeJS Swagger throws 400 on seemingly valid syntax

### ISSUE THREAD

**Issue by Rainbow-Unicorn-Oo** [BitMEX/api-connectors#372]
Hey, I'm trying to get the Swagger implementation to work for a client. Wee bit of a problem is that the official docs all reference a very old version of Swagger. Now with the latest package, I have tried to test a simple market order:

```
    const _ = require('lodash') //fyi
    const SwaggerClient = require("swagger-client");
    const BitMEXAPIKeyAuthorization = require('./lib/BitMEXAPIKeyAuthorization');

    new SwaggerClient({
      url: 'https://www.bitmex.com/api/explorer/swagger.json',
      usePromise: true,
       authorizations: {
      //   // Type of auth, is inferred from the specification provided
         apiKey: new BitMEXAPIKeyAuthorization(_.pick(config,'apiKeyID', 'apiKeySecret'))
       }
    })
    .then(function(sClient) {
      // Print client capabilities, works fine and returns all the available methods
      console.log(sClient);
     
       // set simple sell order
      sClient.apis.Order.Order_new({symbol: 'XBTUSD', ordType: 'Market', side: "Sell", orderQty: "250"})
      .then(function(response) {
        console.log(response);
      })
      .catch(function(e) {
        // Error handling...
        // this is where I end up with a 400 
        console.log('Error:', e.statusText);
        console.log(e);
      })
```

The error that the log dumps is:
` status: 400,
  statusCode: 400,
  response:
   { ok: false,
     url: 'https://www.bitmex.com/api/v1/order',
     status: 400,
     statusText: 'Bad Request',
     headers:
      { date: 'Mon, 15 Jul 2019 13:47:14 GMT',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '85',
        connection: 'close',
        'set-cookie':LOTS_OF_BASE64_CENSORED; Expires=Mon, 22 Jul 2019 13:47:14 GMT; Path=/',
        etag: 'LOTS_OF_BASE64_CENSORED"',
        'strict-transport-security': 'max-age=31536000; includeSubDomains' },
     text:
      '{"error":{"message":"Unexpected token s in JSON at position 0","name":"SyntaxError"}}',
     data:
      '{"error":{"message":"Unexpected token s in JSON at position 0","name":"SyntaxError"}}',
     body: { error: [Object] },
     obj: { error: [Object] } } }`

**Comment by Rainbow-Unicorn-Oo** [comment]
So there seems to be something wrong with the auth, when I try 

```
sClient.apis.User.User_getMargin()
      .then(function(response) {
        var margin = JSON.parse(response.data.toString());
        var marginBalance = (margin.marginBalance / 1e8).toFixed(4);
        console.log('\nMargin Balance:', marginBalance, 'XBT');
      })
      .catch(function(e) {
        // Error handling...

        console.log('Error:', e.statusText);
        console.log(e);
      })
```

I get a 401, authorization required

**Comment by onurgunan** [comment]
Got, same problem.  Any solution?

**Comment by amigoni** [comment]
I am still having this issue. Anyone here that has got this working?

**Comment by STRML** [comment]
Hi. We've updated the example to node-swagger v3 in 2ff224b.
