### ISSUE TITLE
What does the response string look like if Bitmex is overloaded?

### ISSUE THREAD

**Issue by HollandRisley** [BitMEX/api-connectors#374]
Using the C# BitMex API class provided. If I call for a response what does the response string look like if the exchange is overloaded? If I check if it contains "overloaded" will it catch it? I can't recreate overloaded error on Testnet, so need help!

```
string response = BitmexAPI.PostOrder(orderToPost);

if (response.ToLower().Contains("overloaded"))
{
     // WILL THIS CATCH THE OVERLOADED ERROR?
}
```

**Comment by itriad** [comment]
![git](https://user-images.githubusercontent.com/19691968/61590394-d9ec8780-abb8-11e9-90c1-2594a2e93b6f.PNG)

**Comment by itriad** [comment]
if you catch "error",it will do the job

**Comment by HollandRisley** [comment]
Thanks @itriad, that's just what I needed.

**Comment by itriad** [comment]
hello,
do you have an authenticated websocket example in c#?

**Comment by HollandRisley** [comment]
Sure @itriad, this is the one I am using, it works out of the box, I got it from the official Bitmex Github but can't find it again right now, otherwise I'd just link you there. I create it like this.

` BitmexAPI = new BitMEXApi(_apiAccount.Public, _apiAccount.Secret);`

Then call it like this:

`string response = await BitmexAPI.PostBulkOrder(bitmexOrdersList);`

[BitMexAPI.zip](https://github.com/BitMEX/api-connectors/files/3414529/BitMexAPI.zip)

I have made a couple of the methods sort of async like this, but I'm not sure how useful this is, I am still getting my application end to end asynchronous, so you can just remove the returned Task and just return a string like the other methods:

```
 public async Task<string> PostMarketOrder(BitmexOrder orderToPost)
        {

            -----
            string rspns = await Task.Run(() => Query("POST", "/order", param, true));

            return rspns;
        }
```

You can remove the Task and just use it as it came like this:

```
 public string PostMarketOrder(BitmexOrder orderToPost)
        {

            -----
            string rspns = Query("POST", "/order", param, true);

            return rspns;
        }
```

**Comment by itriad** [comment]
thanks,
