### ISSUE TITLE
How can I get authenticated data through WebSocket in C#? 

### ISSUE THREAD

**Issue by itriad** [BitMEX/api-connectors#375]
Hello,
Any examples(**C#**) for authenticated data via WebSocket is Welcome.
"position", "wallet" .....etc etc 
Thanks

**Comment by Paulito123** [comment]
Check out what MKotas has done. I love his work. 
https://github.com/Marfusios/bitmex-client-websocket
Check his example projects.

**Comment by itriad** [comment]
Perfect,
Thanks
