### ISSUE TITLE
Upgrade required not described

### ISSUE THREAD

**Issue by enriquejr99** [BitMEX/api-connectors#379]
I'm trying to open a streaming channel using a lighter low-level socket client. However, I get a 426 status with a not very useful description. It would be great to get a more detailed description of the upgrades I require.

Note: This is a server-side issue.

Specification:

> The server MUST send an Upgrade header field in a 426 response to indicate the required protocol(s).

https://tools.ietf.org/html/rfc7231#section-6.5.15

Sample code:
(Python 3.7)

```
import socket
import ssl

host = 'testnet.bitmex.com'
port = 443

context = ssl.SSLContext(ssl.PROTOCOL_TLS)
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock = context.wrap_socket(sock, server_hostname=host)
sock.connect((host, port))

message = 'GET /realtime HTTP/1.1\r\nHost: testnet.bitmex.com\r\n\r\n'
sock.sendall(message.encode())
response = sock.recv(4096).decode()

print(response)
```
Response:
```
HTTP/1.1 426 Upgrade Required
Date: Thu, 08 Aug 2019 00:52:31 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
cache-control: no-store, no-cache, must-revalidate, max-age=0
pragma: no-cache
X-RateLimit-Limit: 40
X-RateLimit-Remaining: 38
X-RateLimit-Reset: 1565225552
Strict-Transport-Security: max-age=31536000; includeSubDomains

10
Upgrade Required
```
Expected response:
```
HTTP/1.1 426 Upgrade Required
Date: Thu, 08 Aug 2019 00:52:31 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
cache-control: no-store, no-cache, must-revalidate, max-age=0
pragma: no-cache
X-RateLimit-Limit: 40
X-RateLimit-Remaining: 38
X-RateLimit-Reset: 1565225552
Strict-Transport-Security: max-age=31536000; includeSubDomains

Example: This service requires use of the HTTP/X.Y protocol
```

**Comment by STRML** [comment]
The server is expecting you to connect a WebSocket, not a raw TCP socket. This is not a server-side issue, this is the server behaving according to the WebSocket spec.

This is expected and normal. We have functioning examples at https://github.com/BitMEX/api-connectors/tree/master/official-ws/python, please use them.
