### ISSUE TITLE
AttributeError: module 'swagger_client' has no attribute 'OrderBookApi'

### ISSUE THREAD

**Issue by SL33303** [BitMEX/api-connectors#381]
Hello,

Disclaimer: programming novice

Python 3, I downloaded swagger_py using the following method here:

https://stackoverflow.com/questions/50597854/problems-with-future-and-swagger-client-in-python#comment88366290_50608122

When I run the example code, I get the following message:

< AttributeError: module 'swagger_client' has no attribute 'OrderBookApi'>

Am I missing files? What are next steps to resolve this?

Thanks all,

S

**Comment by STRML** [comment]
The path would be `client.OrderBook`. Please see the extensive README for more usage information.

https://github.com/BitMEX/api-connectors/blob/master/official-http/python-swaggerpy/README.md
