### ISSUE TITLE
orderNewBulk example

### ISSUE THREAD

**Issue by ingyukoh** [BitMEX/api-connectors#383]
Bulk orders (first one order, and then expand to list of orders) are constructed from working single order,
orders=self.bitmex_cli.Order.Order_new(symbol=self.symbol, orderQty=qty, price=fPrSel,clOrdID=sMyON,execInst='ParticipateDoNotInitiate').result()
as 
 
orders=self.bitmex_cli.Order.Order_newBulk(["symbol=self.symbol, orderQty=qty, price=fPrSel,clOrdID=sMyON"]).result()
.
I got error message
builtins.TypeError: __call__() takes 1 positional argument but 2 were given

**Real explicit working code snippet** of one and two orders through orderNewBulk would be greatly appreciated.
Best regards,
Ingyu Koh

**Comment by verata-veritatis** [comment]
Are you using Python? You can initiate a list, and append orders like so:

```python
orders.append({'symbol': self.symbol, 'orderQty': qty, 'price': fPrSel, 
    'clOrdID': sMyON, 'execInst': 'ParticipateDoNotInitiate'})
```

When you've appended all your orders, you'll need to convert your list into a JSON string so it's readable by the API. Import the `json` library. You can then send your orders in bulk like so:
```python
orders = self.bitmex_cli.Order.Order_newBulk(orders=json.dumps(orders)).result()
```

**Comment by STRML** [comment]
Thanks for the great answer @verata-veritatis, this is correct.
