### ISSUE TITLE
What is the difference between table, stream, and subscription?

### ISSUE THREAD

**Issue by Bomper** [BitMEX/api-connectors#39]
I'm having trouble understanding from [the Node.js web socket README](https://github.com/BitMEX/api-connectors/blob/master/official-ws/nodejs/README.md) what exactly are "tables", "streams" and "subscriptions". If I understand correctly,

* tables are flat data sources like `orderBookL2`, `trade` or `order`.
* a "stream" is
  * incoming data for a symbol (e.g. everything about `XBTUSD`),
  * or a table (`trade`s for all symbols)
  * or a table within a symbol (e.g. all `trade`s for `XBTUSD`).
* You can "subscribe" to a "stream".

Is that correct?

Asking because https://github.com/BitMEX/api-connectors/blob/master/official-ws/nodejs/README.md#available-public-streams lists tables, but calls them "streams", and the https://www.bitmex.com/app/wsAPI links to "any [available table](https://www.bitmex.com/app/wsAPI#Subscriptions)" as "Subscriptions".

**Comment by STRML** [comment]
You're correct; you subscribe to a table; that subscription object is a stream of data (in the case of Node, often an actual `Stream` object) so the terms are more or less interchangeable.

On the backend, each table is an actual table, and we allow opening a change stream to that table, or filtering that stream (by symbol).

You're correct that we should standardize the language. In the wsAPI page we also use the term `topic`.
