### ISSUE TITLE
Detail of order parameter

### ISSUE THREAD

**Issue by skynet0590** [BitMEX/api-connectors#396]
Hi there. I am trying to use BitMEX api to do a small app. Now I am discovering order api. But not sure how to use some field in order struct

Can someone let me know the value of order quantify. I see we have `orderQty`, `displayQty`, `simpleOrderQty`, `leavesQty`, `simpleCumQty` and `cumQty`.

Thank you

**Comment by STRML** [comment]
Many of those fields (such as `cumQty`) are not used for input. See https://www.bitmex.com/api/explorer/#!/Order/Order_new for the latest documentation.
