### ISSUE TITLE
How much data does the Node WS connector keep in memory?

### ISSUE THREAD

**Issue by Bomper** [BitMEX/api-connectors#40]
Am I missing something, or is this just not [documented](https://github.com/BitMEX/api-connectors/blob/master/official-ws/nodejs/README.md)? How do I prevent a long-running script from running out of memory? Is `client._data` a FIFO queue? How long?

**Comment by STRML** [comment]
That adapter is a starting point. Happy to accept PRs.

**Comment by Bomper** [comment]
Sent a [PR](https://github.com/BitMEX/api-connectors/pull/42) to keep the latest data in the table, rather than the oldest.

How did others manage to use this adapter for more than a few hours at a time without this OOM protection?

**Comment by andersea** [comment]
@Bomper it needs work.

**Comment by STRML** [comment]
It certainly does. I'm sorry for the relatively poor quality of this adapter - it was put together a few years ago and we've had other development priorities since then. It's meant more of a "start hacking here" project rather than a reliable standalone component.

**Comment by andersea** [comment]
@STRML and @Bomper  I'd like to start removing 1-liner if-statements, as I think they are very unfriendly for debugging. You can't put breakpoints on the branch, if the if-statement is a single line.

**Comment by STRML** [comment]
Actually you should have no issue doing that in later Chrome versions; start with `--inspect-brk` then go to `chrome://inspect`. Like so:

<img width="320" alt="screen shot 2017-12-21 at 11 16 10 am" src="https://user-images.githubusercontent.com/1197375/34264287-61a2913c-e640-11e7-9226-a88b3fe9f848.png">

**Comment by andersea** [comment]
What if you are using vscode, will it still work?
