### ISSUE TITLE
Websocket does not send position update when http post request is timed out.

### ISSUE THREAD

**Issue by satyapravin** [BitMEX/api-connectors#400]
Hi All,

I have an HFT bot that encountered this issue and wanted to highlight it.

Language: C#.NET

Problem:

Sometimes during periods of intense market activity, my client Http POST request times out and I receive a cancellation.

Here is my code for posting orders: `var response = await _httpClient.SendAsync(request);`
where `_httpClient` is the default C#.NET system class `System.Net.Http.HttpClient`.

The await times out with a thrown `TaskCanceledException` and my bot does not know if the operation succeeded or failed.

However, I noticed that these orders are subsequently filled and are successful from the log file. 

I am also listening to position updates on the WebSocket and here lies the problem. When my Http post is canceled due to timeout, the order is still filled on the exchange but I never received a position update from WebSocket. This creates a problem because my bot believes that the order has failed and keeps trying but the WebSocket never updates positions for Http timed out requests (they are filled though on the exchange).

**Comment by STRML** [comment]
Hi - if you are getting a `TaskCanceledException` then your timeouts are too low. Try adjusting them higher.

If the order fills, then a position update will always come through the websocket. If you can reproduce a case where it does not, then there is certainly an exchange-side bug, but that would be fairly serious and we have not heard any such thing from others. More likely, there is an issue with processing position updates in your code when such a timeout event occurs.

I realize the age of this ticket, so I'm going to close it for now - but please reopen if you continue to have issues, or email the team directly at support@bitmex.com with specific data and timestamps if you believe there is a server-side issue.
