### ISSUE TITLE
Need help setting up the API

### ISSUE THREAD

**Issue by rctrader** [BitMEX/api-connectors#401]
I am new trying to pull raw ohlc data from bitmex, and am following this package: https://github.com/BitMEX/api-connectors/tree/master/official-ws/python

I have installed it succesfully but cannot 'instantiate a connection' using:
from bitmex_websocket import BitMEXWebsocket ws = BitMEXWebsocket(endpoint=”https://testnet.bitmex.com/api/v1”, symbol=”XBTUSD”, api_key=None, api_secret=None)

This is the error I get:
>from bitmex_websocket import BitMEXWebsocket ws = BitMEXWebsocket(endpoint="https://testnet.bitmex.com/api/v1", symbol="XBTUSD", api_key=None, api_secret=None)
'from' is not recognized as an internal or external command,
operable program or batch file.

I am quite new to this so I am hoping this is a really easy fix and would appreciate any help.

**Comment by STRML** [comment]
Hi, I'm sorry. This looks like you are trying to run the Python application on Windows, but you are making a very basic error. It appears you are pasting raw Python code into your terminal, which certainly will not work.

Please take a look at https://wiki.python.org/moin/BeginnersGuide for how to get started with Python on Windows.
