### ISSUE TITLE
NodeJS /position RESTful endpoint problem

### ISSUE THREAD

**Issue by jeuxdemains** [BitMEX/api-connectors#403]
Hello,
We are facing a problem when calling the /position endpoint of the BitMEX API on both testnet and real account.

The first few days it was working properly and was returning the results of our open positions.
After that suddenly stopped working -- it started returning empty JS array []

Did anyone face the same issue?

Here is our NodeJS backend code related to the issue:

//CALLED LAST
//this is the MakeRequest function in one of your examples
function passiveApi(verb, endpoint, data = {}) {
const apiRoot = '/api/v1/';
const expires = Math.round(new Date().getTime() / 1000) + 60; // 1 min in the future

let query = '', postBody = '';
if (verb === 'GET')
query = '?' + qs.stringify(data);
else
postBody = JSON.stringify(data);

const signature = crypto.createHmac('sha256', apiSecret)
.update(verb + apiRoot + endpoint + query + expires + postBody)
.digest('hex');

const headers = {
'content-type'    : 'application/json',
'accept'        : 'application/json',
'api-expires'    : expires,
'api-key'        : apiKey,
'api-signature'    : signature,
};

const requestOptions = {
method: verb,
headers,
};
if (verb !== 'GET') requestOptions.body = postBody; // GET/HEAD requests can't have body

const url = serviceURL + apiRoot + endpoint + query;

return fetch(url, requestOptions).then(response => response.json()).then(
response => {
if ('error' in response) throw new Error(response.error.message);
return response;
},
error => console.error('Network error', error),
);
}

//CALLED SECOND
async function getStatus()
{
try {
const result = await passiveApi('GET', 'position', 
{
filter: { symbol : "XBTUSD" },
columns: ["timestamp"]
});
return result;
} catch (e) {
return e;
};
};

//CALLED FIRST
//this is the route we are calling from our frontend
server.post('/api/getcurstatus', async (req, res) => {
    logRequest(req.url);
    
    var status = await getStatus(); // this call returns [] (empty array) after the first day of development; initially it was working correctly
    var time = getTime();

    var currencies = req.body.symbol.split(",");
    var curr = {};

    for (cur in currencies)
    {
        var data = await getCurrencyStatus(currencies[cur], status[0].currentTimestamp);
        if (data.length == 0)
            data.push({ open : "network error"});

        curr[currencies[cur]] = { "price": data[0].open };
    }

    var result = 
        { 
            "currencies" : curr, 
            "timestamp" : status[0].currentTimestamp 
        }

    res.json(result);
});

**Comment by gnwankpa** [comment]
Hi, why did you close this? was it fixed? If fixed please let me know how, i am experiencing a similar issue.
