### ISSUE TITLE
405 Method Not Allowed using Request to Post Order

### ISSUE THREAD

**Issue by SolomonWilde** [BitMEX/api-connectors#404]
Using api-connectors/official-http/node-request/index.js works fine in testnet.
I then modify the API key & secret and amend "https://testnet.bitmex.com" to "https://bitmex.com"

But this gets the response:
<html>
<head><title>405 Method Not Allowed</title></head>
<body>
<h1>405 Method Not Allowed</h1>
<ul>
<li>Code: MethodNotAllowed</li>
<li>Message: The specified method is not allowed against this resource.</li>
<li>Method: POST</li>
<li>ResourceType: OBJECT</li>
<li>RequestId: EB3404E54094D337</li>
<li>HostId: qKFKocE11Y3mxL5mC0i55pvATe7HGFSJtRdVMWk5BztT706iZmMXSHd9WYuuBfDHBVcqRk6236k=</li>
</ul>
<hr/>
</body>
</html>

My keys were set up with the same permissions in Testnet and Live
Any help greatly appreciated

**Comment by SolomonWilde** [comment]
Wow so dumb. Turns out the correct URL to use is:
https://www.bitmex.com

**Comment by wesboyt** [comment]
thanks, i was running into the same issue moving from testnet to the main one.
