### ISSUE TITLE
How can I use Nodejs socket to order ( insert/update/delete)

### ISSUE THREAD

**Issue by hagilani** [BitMEX/api-connectors#409]
Hi masters.

I couldn't find any detailed socument to create/update/delete an order in a position
Could you please help me?

**Comment by verata-veritatis** [comment]
If you are looking to execute orders through websockets, this is not doable. The only thing you can do is cancel all orders via `cancelAllAfter`.

**Comment by STRML** [comment]
This is correct. All order management operations are through http.
