### ISSUE TITLE
Node.js client on 'data' event

### ISSUE THREAD

**Issue by eugestarr** [BitMEX/api-connectors#41]
Hi, I successfully connected to the data stream, which is confirmed by:

```js
client.addStream('XBTUSD', 'trade', (data) => { console.log(data) });
```

But when the app is subscribed to an event nothing happens:

```js
client.addStream('XBTUSD', 'trade', () => {});
client.on('data', function(data) {
    console.log(data);
});
```

Please advise.
Thank you.

**Comment by andersea** [comment]
That part of the documentation looks out of date. The event names are based on the table, action and symbol values.

See - 

https://github.com/BitMEX/api-connectors/blob/master/official-ws/nodejs/lib/createSocket.js

    // Fires events as <table>:<action>:<symbol>, such as
    // instrument:update:XBTUSD.
    // Consumers may be listening on:
    // * action filter   (e.g. `instrument:partial:*`)
    // * symbol filter   (e.g. `instrument:*:XBTUSD`)
    // * table filter    (e.g. `instrument:*:*`)
    emitSplitData(bmexClient, data);

    // For no-symbol tables, emit a '*' event.
    const tableNoSymbol = _.includes(bmexClient.constructor.noSymbolTables, data.table);
    if (tableNoSymbol) {
      emitFullData(bmexClient, data);
    }

**Comment by Bomper** [comment]
[This PR](https://github.com/BitMEX/api-connectors/pull/47) removes the "data" event from the README but please add the actual events emitted.

**Comment by eugestarr** [comment]
> That part of the documentation looks out of date. The event names are based on the table, action and symbol values.
> 
> See -
> 
> https://github.com/BitMEX/api-connectors/blob/master/official-ws/nodejs/lib/createSocket.js
> 
> // Fires events as <table>:<action>:<symbol>, such as
> // instrument:update:XBTUSD.
> // Consumers may be listening on:
> // * action filter   (e.g. `instrument:partial:*`)
> // * symbol filter   (e.g. `instrument:*:XBTUSD`)
> // * table filter    (e.g. `instrument:*:*`)
> emitSplitData(bmexClient, data);
> 
> // For no-symbol tables, emit a '*' event.
> const tableNoSymbol = _.includes(bmexClient.constructor.noSymbolTables, data.table);
> if (tableNoSymbol) {
>   emitFullData(bmexClient, data);
> }

Is there a list of all available combinations or at least actions to use when hooking into the stream?

**Comment by Bomper** [comment]
@eugestarr: https://www.bitmex.com/app/wsAPI#All-Commands ? Are you looking for the list of streams? You can get that with [client.streams()](https://github.com/BitMEX/api-connectors/tree/master/official-ws/nodejs#clientonstring-eventname-function-callback).

**Comment by eugestarr** [comment]
@Bomper yes, this is what I'm looking for, thank you.
