### ISSUE TITLE
C# Where is the signature string created?

### ISSUE THREAD

**Issue by Paulito123** [BitMEX/api-connectors#414]
Hi there
After generating the C# code from the Swagger JSON, I'm trying to put a simple order on the exchange, without success. After digging into the code I am wondering where the api-signature is created in the generated code. Either I'm blind or I need to add the code to generate the signature myself. (it's probably the first :) )
Thanks in advance

**Comment by STRML** [comment]
Hi - unfortunately the swagger codegen does not support our authentication scheme. We are looking into alternative options. 

There is a working implementation at https://github.com/BitMEX/api-connectors/blob/master/official-http/csharp/BitMEXAPI.cs#L75. You can also find the documentation for our auth at https://www.bitmex.com/app/apiKeysUsage.
