### ISSUE TITLE
NODEJS - Why don't get new data when run example.js

### ISSUE THREAD

**Issue by tuananh3988** [BitMEX/api-connectors#416]
`node example.js

Client initialized, data is flowing.
WebSocket [INFO]: Connected.
Connection opened.
Got update for quote:XBTUSD. Current state:
[{"timestamp":"2020-01-17T09:53:15.040Z","symbol":"XBTUSD","bidSize":1700296,"bidPrice":8960,"askPri...
Got update for quote:XBTUSD. Current state:
[{"timestamp":"2020-01-17T09:53:15.040Z","symbol":"XBTUSD","bidSize":1700296,"bidPrice":8960,"askPri...
Got update for quote:XBTUSD. Current state:
[{"timestamp":"2020-01-17T09:53:15.040Z","symbol":"XBTUSD","bidSize":1700296,"bidPrice":8960,"askPri...`

When i run example.js, data not change on real time. how to get data from subscription topic?

**Comment by STRML** [comment]
There is more data, we're just not printing all of it. Modify `example.js` to sort or print the full table, if you like.
