### ISSUE TITLE
Can I connect multiple clients to server using the same API key + secret ?

### ISSUE THREAD

**Issue by GrandadsJumper** [BitMEX/api-connectors#417]
e.g.

Say i want to split the stream of information between two websocket connections, position through one websocket and instrument updates through the other to avoid losing position data due to high volume of price updates. 

Could I connect to the position URI and instrument URI separately but using the same API key and secret without there being a negative effect such as one connection dropping?

**Comment by SebastianLuebke** [comment]
Which language are you using? Python?

**Comment by GrandadsJumper** [comment]
Yes python

**Comment by SebastianLuebke** [comment]
You can always connect to the instrument data without an api key and open a extra socket with an api key for the account data.
about next week im going to release a bitmex websocket package here on github which automaticly does that and it will also be possible to use multiple different accounts/api-keys

**Comment by verata-veritatis** [comment]
You can definitely have multiple websocket streams going through the same API keys. Just remember to use a different port.

**Comment by STRML** [comment]
Yes - multiple clients for a single key is supported, but for safety reasons we always suggest multiple keys with least permissions.
