### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by EdixonAlberto** [BitMEX/api-connectors#418]
What happened to the support for **TypeScript** ? 😐

**Comment by STRML** [comment]
It is still at https://github.com/BitMEX/api-connectors/blob/master/auto-generated/typescript-node/api.ts. It hasn't been removed.

**Comment by EdixonAlberto** [comment]
Thanks, so this link should be fixed
![image](https://user-images.githubusercontent.com/40126214/83357549-0295ef80-a33b-11ea-8a42-7f2626bfa32e.png)
