### ISSUE TITLE
Profit, liquidation, etc idea

### ISSUE THREAD

**Issue by Baael** [BitMEX/api-connectors#428]
Would be nice if you can include/create new repo with functions to calculate all necessary stuff for paper trading. There is a lot resources on the web, however every single of it is different, also real trading is different so there is also a lot of confusion. 

If there is any valid and trustworthy source for such formulas (real ones, not synthetic that later appears wrong), I would be thankful for info.

**Comment by verata-veritatis** [comment]
> to calculate all necessary stuff for paper trading...if there is any valid and trustworthy source for such formulas (real ones, not synthetic that later appears wrong), I would be thankful for info.

This is extremely vague. What do you mean "all necessary stuff"? What stuff?

**Comment by Baael** [comment]
API should include paper trading functions to calculate (based on WS/REST real values)
- liquidation price
- market to market pnl
- market to limit pnl
- limit to limit pnl
- profit, loss

There are multiple calcs and formulas available, yet most of them have different results, are not clear where to use markPrice, lastPrice or fairPrice. 

Would be great to have it included in API by bitmex to cut off all speculations and multiple different formulas.

**Comment by verata-veritatis** [comment]
It's all quite simple and most of the information is already provided for you. It just takes a little research.

I suggest you look through the API explorer, since most of the information you want is provided in the get position response.
https://www.bitmex.com/api/explorer/#!/Position/Position_get

Liquidation price, value based on last price, value based on mark price, it's all there.

**Comment by STRML** [comment]
Hi @Baael. We are looking into making the formulas interactive on the website, which should help in understanding these calculations. They are correct, however, and you should be able to use them as written. Please re-open if you have a specific formula you are having issue with.
