### ISSUE TITLE
Websocket disconnects when subscribed to transact:*

### ISSUE THREAD

**Issue by andersea** [BitMEX/api-connectors#43]
If I subscribe to the transact:* table, I get disconnected after 1 minute. The websocket will then automatically reconnect and stay connected for one more minute, then it will disconnect again, throw an exception and exit.

Sample code:

    const BitMEXClient = require('bitmex-realtime-api')

    const client = new BitMEXClient({
        apiKeyID: 'yourtestnetkeyid',
        apiKeySecret: 'suchsecretmuchsecure',
        testnet: true,
    })

    client.addStream('*', 'transact', function (data, symbol, tableName) {
        console.log(`${tableName}:${symbol} - ${JSON.stringify(data)}`)
    });

Output:

    WebSocket [INFO]: Connected.    ReconnectingSocket.js:85
    {"op":"subscribe","args":"transact:*"}    index.js:179
    transact:* - []    index.js:10
    transact:* - []    index.js:10
    WebSocket [ERROR]: Websocket closed.    ReconnectingSocket.js:90
    WebSocket [INFO]: Retry in 1000 ms    ReconnectingSocket.js:85
    WebSocket [INFO]: Reconnecting...    ReconnectingSocket.js:85
    WebSocket [INFO]: Connected.    ReconnectingSocket.js:85
    {"op":"subscribe","args":"transact:*"}    index.js:179
    transact:* - []    index.js:10
    transact:* - []    index.js:10
    WebSocket [ERROR]: Websocket closed.    ReconnectingSocket.js:90
    WebSocket [INFO]: Retry in 1000 ms    ReconnectingSocket.js:85
    WebSocket [INFO]: Reconnecting...    ReconnectingSocket.js:85
    WebSocket [ERROR]: Unexpected response from server [400]: {"error":"Nonce is not increasing. This nonce: 1513803028187, last nonce: 1513803028187"}    ReconnectingSocket.js:90
    WebSocket [INFO]: The WebSocket will terminate. Please manually reconnect.    ReconnectingSocket.js:85
    WebSocket [ERROR]: Closing Websocket    ReconnectingSocket.js:90

**Comment by andersea** [comment]
Looks like there is a side issue with the reconnection routine trying to reuse the nonce.

**Comment by andersea** [comment]
A fix for the nonce reuse issue can be found in #50.

**Comment by STRML** [comment]
Thanks for our fix @andersea.
