### ISSUE TITLE
[Nodejs] [WebSocket] Table "connected" don't work 

### ISSUE THREAD

**Issue by Dkdaniz** [BitMEX/api-connectors#430]
Hi guys, 

I'm development an Api for my system, but when i'm doing an request in Websocket dont receive nothing result,

My codes:

`
client.addStream('connected', async function(data, symbol, tableName) {
  console.log('\x1b[32m', `v:`);
  console.log('\x1b[0m');
  console.log(data);
  console.log(symbol);
  console.log(tableName);
  console.log('\n');
});
`
.....
....

`client.addStream('XBTUSD', 'connected', async function(data, symbol, tableName) {
  console.log('\x1b[32m', `v:`);
  console.log('\x1b[0m');
  console.log(data);
  console.log(symbol);
  console.log(tableName);
  console.log('\n');
});`

this two call form return Empty: []

i already did doing this two methods, can somebody help me?

**Comment by STRML** [comment]
`connected` is not the name of a stream. Please try the example code exactly as written on https://github.com/BitMEX/api-connectors/tree/master/official-ws/nodejs.
