### ISSUE TITLE
how to stop websocket

### ISSUE THREAD

**Issue by canerd7u** [BitMEX/api-connectors#431]
How can I close the class after opening the websocket ?

**Comment by STRML** [comment]
Which project?

**Comment by ian-collab** [comment]
You can close the instantiated object from the BitMEX websocket class using the exit method.

For example,
if your websocket object is named "ws" as in the case of some examples I have seen, you would use

ws.exit()

**Comment by STRML** [comment]
Thanks @ian-collab, that is correct. @canerd7u please re-open if you have further questions.
