### ISSUE TITLE
Python WS orderbook L2 issue

### ISSUE THREAD

**Issue by pavs94** [BitMEX/api-connectors#435]
The current url in main.py is https://testnet.bitmex.com replace it with live url wss://www.bitmex.com/realtime and subscribe to market_depth(). This gives an error: 
`
return self.data['orderBookL2']
KeyError: 'orderBookL2'
`

**Comment by ian-collab** [comment]
I use a different endpoint in my live Python project for WS;
https://www.bitmex.com/api/v1

No problems yet, though I have not tried orderBookL2

It might help to try the different endpoint.

**Comment by STRML** [comment]
I can't reproduce your initial problem with the few details you've given us. However, we've made some recent updates to that project. Please try it again.
