### ISSUE TITLE
Open_Orders problem

### ISSUE THREAD

**Issue by ian-collab** [BitMEX/api-connectors#437]
I am successfully using Open_Orders to return an order object but I am missing how to access the order object values.

For example
o = ws.open_orders("Entry")
returns
[{'orderID': 'ec166903-c0c6-22ef-4ba2-de360670f3e7', 'clOrdID': 'Entry2', 'clOrdLinkID': '', 'account': ..., 'symbol': 'XBTUSD', 'side': 'Sell', 'simpleOrderQty': None, 'orderQty': 10, 'price': 9000, 'displayQty': None, 'stopPx': None, 'pegOffsetValue': None, 'pegPriceType': '', 'currency': 'USD', 'settlCurrency': 'XBt', 'ordType': 'Limit', 'timeInForce': 'GoodTillCancel', 'execInst': '', 'contingencyType': '', 'exDestination': 'XBME', 'ordStatus': 'Filled', 'triggered': '', 'workingIndicator': False, 'ordRejReason': '', 'simpleLeavesQty': None, 'leavesQty': 0, 'simpleCumQty': None, 'cumQty': 10, 'avgPx': 9000, 'multiLegReportingType': 'SingleSecurity', 'text': 'Submitted via API.', 'transactTime': '2020-05-11T00:34:01.179Z', 'timestamp': '2020-05-11T11:53:44.149Z'}]

Yet, I can't seem to find a way to access the price value.

Help please? Am I being dense or is there something amiss in the implementation?

**Comment by ian-collab** [comment]
Okay, found a workaround. Its a little ugly, so suggestions please...

I noticed that the returned object is a little bit dictionary, a little bit list, then bingo, its a dictionary sitting in a list of 1 item length.

Take the list
Assign it to a dictionary object
Get the values

e.g.
o = ws.open_orders('Entry')
OrdersDic = o[0]
OrdersDic.get('price')

**Comment by STRML** [comment]
That's what it is. All of these return values are lists, some are 0-length or 1-length lists, but it's always a list. You're accessing it properly in your code sample.
