### ISSUE TITLE
Python websocket 100% CPU utilisation

### ISSUE THREAD

**Issue by ian-collab** [BitMEX/api-connectors#438]
With the Python websocket project....

I have a host on which an open websocket object uses 100% of CPU. The Testnet websocket object uses only 3% - implying masses and masses of data on the live object.. I could ramp up the CPU capacity on this paid service, but obviously it costs.  

Also, a more elegant solution is appealing given that from the websocket, I essentially need only a limited range of data.

Is there a means by which we can limit the amount of data hosing down from the websocket?

As a simple example, is it possible to have the websocket object populated only by the order data?

**Comment by STRML** [comment]
Yes, you can.

There are two things you can tweak. One is that now, there is an optional parameter that determines which subscriptions you open:

https://github.com/BitMEX/api-connectors/blob/3cf93b732354d7722c4a32dcaa8325fef7948d33/official-ws/python/bitmex_websocket.py#L25

You could pass, say, `subscriptions=['order']` if that's all you want.

Second, you can adjust this parameter downward to store less data:

https://github.com/BitMEX/api-connectors/blob/3cf93b732354d7722c4a32dcaa8325fef7948d33/official-ws/python/bitmex_websocket.py#L22-L23

All of that said, the production application emits much more data than testnet, so if you are parsing `orderBookL2` or `trade` data there will be much more CPU usage.

I hope that helps.

**Comment by ian-collab** [comment]
Thanks very much.

I will put those to the test.

**Comment by ian-collab** [comment]
Testing completed.

Got rid of orderBookL2, reduced table size to 50.  CPU utilisation on that VPS down to about 3% just holding the websocket connector open.  Hooray.

Notes for the next person with the issue:
This also solved an issue that I had on a well provisioned machine which was not visibly struggling.  That issue was that the websocket was taking 2 minutes to report an updated order price change.  I don't understand how a machine that appears to be coping with the full data feed gets that sort of delay but the solution was; pare that data feed.

On that topic of paring the feed; orderBookL2 was populated with some 12,000 objects when I looked, all being updated in realtime.  That's what was pared.  I estimate orderBookL2 to be greater than 90% of the data feed.

On a fresh pip install of the websocket connector, I didn't receive that updated __init__ method that STRML mentioned; no subscription key.  So instead....

Here is a copy of my edited __init__ method for the BM websocket class;
    def __get_url(self):
        '''
        Generate a connection URL. We can define subscriptions right in the querystring.
        Most subscription topics are scoped by the symbol we're listening to.
        '''

        # You can sub to orderBookL2 for all levels, or orderBook10 for top 10 levels & save bandwidth
        # symbolSubs = ["execution", "instrument", "order", "orderBook10", "position", "quote", "trade"]
        symbolSubs = ["execution", "instrument", "order", "position", "quote", "trade"]
        genericSubs = ["margin"]

        subscriptions = [sub + ':' + self.symbol for sub in symbolSubs]
        subscriptions += genericSubs

        urlParts = list(urllib.parse.urlparse(self.endpoint))
        urlParts[0] = urlParts[0].replace('http', 'ws')
        urlParts[2] = "/realtime?subscribe={}".format(','.join(subscriptions))
        return urllib.parse.urlunparse(urlParts)

BEWARE;
The wait methods for connection.
    def __wait_for_account(self):
    def __wait_for_symbol(self, symbol):

Edit them so that they are not waiting on subscriptions that you have not requested.  Otherwise you will never get your weboscket object.
