### ISSUE TITLE
addStream(symbol, callback) without table doesn't receive data

### ISSUE THREAD

**Issue by Bomper** [BitMEX/api-connectors#44]
The README says the tableName is [optional](https://github.com/BitMEX/api-connectors/blob/master/official-ws/nodejs/README.md#clientaddstreamstring-symbol-string-tablename-function-callback) and [the code](https://github.com/BitMEX/api-connectors/blob/master/official-ws/nodejs/index.js#L139) uses a '*' if no tableName is given. But if you don't pass one, you get this error **as data** [in the callback](https://github.com/BitMEX/api-connectors/blob/b734252a6500aa25514fca525594111d1c061ce4/official-ws/nodejs/index.js#L147) (not as a proper error):

> Error: Unknown table for BitMEX subscription: *. Available tables are announcement,connected,chat,publicNotifications,instrument,settlement,funding,insurance,liquidation,orderBookL2,orderBook10,quote,trade,quoteBin1m,quoteBin5m,quoteBin1h,quoteBin1d,tradeBin1m,tradeBin5m,tradeBin1h,tradeBin1d,privateNotifications,account,wallet,affiliate,margin,position,transact,order,execution.

```js
client.addStream('XBTUSD', data => {
  console.log(data);
});

**Comment by STRML** [comment]
Ah yes. That's an actual error from the socket. We'll have to look for it
and throw.

**Comment by Bomper** [comment]
How can I subscribe to several tables in one addStream call? Or must I make a separate call for each?

**Comment by STRML** [comment]
You can't; will have to e.g.:

```js
function onData(data) {...}
['trade:XBTUSD', 'orderBookL2:XBTUSD', 'liquidation:XBTUSD'].forEach((table) => client.addStream(table, onData));
```

**Comment by ryanfox** [comment]
Not supplying a table name now raises an actual error.
