### ISSUE TITLE
Is it possible to have "PositionId" or "createdAtTimestamp" on the Position details?

### ISSUE THREAD

**Issue by hems** [BitMEX/api-connectors#441]
Currently, when fetching `Orders` we have a unique identifier for an `Order` ( `orderID` ) but we don't have the counter-party for `Positions`.

[The documentation](https://www.bitmex.com/api/explorer/#!/Position/Position_get) states "The fields account, symbol, currency is unique to each position and form its key." but in reality, if Positions are stored in a database that key won't be unique.

For instance, by opening and closing multiple positions on the same market a user will end up with several positions opened and closed and all of them will have the same "unique id".

Is it possible to somehow ensemble a unique id per position currently?

I was expecting to use `symbol` + `openingTimestamp` but just recently discovered through Bitmex support ( and @bendelo 's comment [on this issue](https://github.com/BitMEX/api-connectors/issues/295) ) that this is not possible.

On my specific application, it would be very useful to have `createdAtTimestamp` as a way to facilitate and simplify tracking open and closed positions and also as a way of uniquely identified multiple positions. 

It would also make easy to "Fetch all Trades for this position" by knowing the timestamp the position was opened.

**Comment by bendelo** [comment]
Your concept of historical positions, which is trades being grouped into batches that occur between `currentQty==0` and `currentQty==0` i.e. the opening and closing of a net-long or net-short position, does not exist inside the trading engine. However you may find that `GET /execution/tradeHistory` gives you the historical average entry and realisedPNL of each 'position'.

https://www.bitmex.com/api/explorer/#!/Execution/Execution_getTradeHistory

**Comment by hems** [comment]
> Your concept of historical positions, which is trades being grouped into batches that occur between `currentQty==0` and `currentQty==0` i.e. the opening and closing of a net-long or net-short position, does not exist inside the trading engine. However you may find that `GET /execution/tradeHistory` gives you the historical average entry and realisedPNL of each 'position'.
> 
> https://www.bitmex.com/api/explorer/#!/Execution/Execution_getTradeHistory

Are there any plans of adding documentation for that endpoint?

There are several fields with `Qty" suffix, it would be great to know the difference between them

````
    "displayQty": 0,
    "lastQty": 0,
    "simpleOrderQty": 0,
    "orderQty": 0,
    "simpleLeavesQty": 0,
    "leavesQty": 0,
    "simpleCumQty": 0,
    "cumQty": 0,
````

**Comment by hems** [comment]
> Your concept of historical positions, which is trades being grouped into batches that occur between `currentQty==0` and `currentQty==0` i.e. the opening and closing of a net-long or net-short position, does not exist inside the trading engine.

What about "Open Positions", once a trade is executed and currentQty goes from 0 to negative or 0 to position?

Don't you create an "Open Position" ( which has a liquidation price, and is rollover every hour ) or every time a request is made to issue to the API requesting "Open Positions" you have to check the Trade History for each market and reconstruct the Open Positions?

I'm interested in the timestamp an open position was initiated ( first trade that happens after currentQty = 0 ), I don't particularly care for "Historical Positions".

**Comment by bendelo** [comment]
> https://www.bitmex.com/api/explorer/#!/Execution/Execution_getTradeHistory

Ooops, I meant to link to this endpoint, it has `currentQty` on it:
https://www.bitmex.com/api/explorer/#!/User/User_getExecutionHistory

**Comment by hems** [comment]
> Ooops, I meant to link to this endpoint, it has `currentQty` on it:
> https://www.bitmex.com/api/explorer/#!/User/User_getExecutionHistory

Thanks, I'll do some tests on my side and try it out.

BTW, Currently, the documentation for that endpoint on the REST EXPLORER is empty, is it available anywhere else? it would be great to have it updated on the REST EXPLORER.

Not sure how feasible it is, but might make sense to move the documentation to an open-source GitHub repository so more people could contribute?

![image](https://user-images.githubusercontent.com/27327/83471407-84d9fd00-a47c-11ea-80cb-ab4abc37d220.png)

![image](https://user-images.githubusercontent.com/27327/83471414-8acfde00-a47c-11ea-8422-bb9656baaf48.png)

**Comment by STRML** [comment]
We're looking into just that, as we want to document the columns in a way that is not possible within `swagger-`ui. We will likely introduce a new folder into this repository and link to it prominently from within the API documentation in the site, the Swagger Explorer, and the README here.

**Comment by hems** [comment]
> We're looking into just that, as we want to document the columns in a way that is not possible within `swagger-ui`. We will likely introduce a new folder into this repository and link to it prominently from within the API documentation in the site, the Swagger Explorer, and the README here.

Thanks for the update, i created an [issue here](https://github.com/BitMEX/api-connectors/issues/443) so hopefully i'll be notified as soon as the documentation is updated.

Thank You

**Comment by hems** [comment]
Also i found this issue ( https://github.com/BitMEX/api-connectors/issues/280 )  from 2018  regarding User_getExecutionHistory which is probably solved but not yet closed on this repository?

**Comment by STRML** [comment]
Thanks for highlighting that @hems, I've closed that ticket out.

**Comment by enriquepiatti** [comment]
I'm receiving always an empty array when using User_getExecutionHistory, what could be causing that?  (other endpoints are working fine, I can get my trades etc, and I'm not receiving an error, just an empty array as result)

**Comment by bendelo** [comment]
Put in the timestamp of a RealisedPNL entry (at 12:00 UTC).

On Sat, 20 Jun 2020 at 21:43, Enrique Piatti <notifications@github.com>
wrote:

> I'm receiving always an empty array when using User_getExecutionHistory,
> what could be causing that? (other endpoints are working fine, I can get my
> trades etc, and I'm not receiving an error, just an empty array as result)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_BitMEX_api-2Dconnectors_issues_441-23issuecomment-2D646996330&d=DwMCaQ&c=o2Rg2hCP31Es1DdrOYH75Q&r=XDW73b-_jvZBy7m5lDNX4Q&m=JOPyFRNpZVDC7UCtQKFQw2jLZ120L-ATehYTVTBwxhY&s=PKkUSYUv8q2_kZOwDXVA3VEZgXywT1A7Dk-ZJ23dTdw&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABSAFS356C3B2TRWMW2K3XLRXS4GHANCNFSM4NM2THIA&d=DwMCaQ&c=o2Rg2hCP31Es1DdrOYH75Q&r=XDW73b-_jvZBy7m5lDNX4Q&m=JOPyFRNpZVDC7UCtQKFQw2jLZ120L-ATehYTVTBwxhY&s=PeZrbUbMEmGcP22Vaqjo4bmYYq1XriaqML1mh-Kut0M&e=>
> .
>

-- 


This e-mail and all information in, attached to, or linked via this 
e-mail (together the ‘e-mail’) is confidential and may be legally 
privileged. It is intended solely for the intended addressee(s). Access to, 
or any onward transmission, of this e-mail by any other person is not 
authorised. If you are not the intended recipient, you are requested to 
immediately alert the sender of this e-mail and to immediately delete this 
e-mail. Any disclosure in any form of all or part of this e-mail, or of any 
the parties to it, including any copying, distribution or any action taken 
or omitted to be taken in reliance on it, is prohibited and may be 
unlawful. 




Transacting on BitMEX is not permitted for, or offered or 
available to, any person(s) located in or being resident(s) of (i) the 
United States of America or Québec (Canada). Additionally, transacting on 
BitMEX is not permitted for, or offered or available to, any person(s) 
located in or being resident(s) of (i) Cuba, Crimea and Sevastopol, Iran, 
Syria, North Korea, or Sudan, (ii) any other sanctioned jurisdiction, or 
(iii) any jurisdiction where the services offered by BitMEX are restricted. 





This e-mail is not, and is not intended to be, and should not be 
construed as being, (a) any offer, solicitation, or promotion of any kind; 
(b) the basis of any investment or other decision(s);  (c) any 
recommendation to buy, sell or transact in any manner any good(s), 
product(s) or service(s), nor engage in any investment(s) or other 
transaction(s) or activities;  or (d) the provision of, or related to, any 
advisory service(s) or activities, including regarding any investment, tax, 
legal, financial, accounting, consulting or any other related service(s).

**Comment by enriquepiatti** [comment]
So timestamp is the exact timestamp for a realized PNL? we cannot get the full execution history?
Do we need to scan first all the trades and then for every (!) trade make a new request to get the execution history of that trade?

**Comment by bendelo** [comment]
There's only one RealisedPNL transact entry per day

On Sat, 20 Jun 2020 at 22:27, Enrique Piatti <notifications@github.com>
wrote:

> So timestamp is the exact timestamp for a realized PNL? we cannot get the
> full execution history?
> Do we need to scan first all the trades and then for every (!) trade make
> a new request to get the execution history of that trade?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_BitMEX_api-2Dconnectors_issues_441-23issuecomment-2D647002604&d=DwMCaQ&c=o2Rg2hCP31Es1DdrOYH75Q&r=XDW73b-_jvZBy7m5lDNX4Q&m=TbGT0TEMbZix1tGInSf0jW-XYnr9J-gA_4SYQ3xXvhQ&s=DB9kgT_NGz4KRVuLhZCU7WEfFOcx7xXhbHPC7db-cUk&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABSAFS5CTD4VXVRZVDK5WLDRXTBMDANCNFSM4NM2THIA&d=DwMCaQ&c=o2Rg2hCP31Es1DdrOYH75Q&r=XDW73b-_jvZBy7m5lDNX4Q&m=TbGT0TEMbZix1tGInSf0jW-XYnr9J-gA_4SYQ3xXvhQ&s=pcsF5_bU6rMEhIiY0ew-5B0zwbsMYREsASwEajA3WCs&e=>
> .
>

-- 


This e-mail and all information in, attached to, or linked via this 
e-mail (together the ‘e-mail’) is confidential and may be legally 
privileged. It is intended solely for the intended addressee(s). Access to, 
or any onward transmission, of this e-mail by any other person is not 
authorised. If you are not the intended recipient, you are requested to 
immediately alert the sender of this e-mail and to immediately delete this 
e-mail. Any disclosure in any form of all or part of this e-mail, or of any 
the parties to it, including any copying, distribution or any action taken 
or omitted to be taken in reliance on it, is prohibited and may be 
unlawful. 




Transacting on BitMEX is not permitted for, or offered or 
available to, any person(s) located in or being resident(s) of (i) the 
United States of America or Québec (Canada). Additionally, transacting on 
BitMEX is not permitted for, or offered or available to, any person(s) 
located in or being resident(s) of (i) Cuba, Crimea and Sevastopol, Iran, 
Syria, North Korea, or Sudan, (ii) any other sanctioned jurisdiction, or 
(iii) any jurisdiction where the services offered by BitMEX are restricted. 





This e-mail is not, and is not intended to be, and should not be 
construed as being, (a) any offer, solicitation, or promotion of any kind; 
(b) the basis of any investment or other decision(s);  (c) any 
recommendation to buy, sell or transact in any manner any good(s), 
product(s) or service(s), nor engage in any investment(s) or other 
transaction(s) or activities;  or (d) the provision of, or related to, any 
advisory service(s) or activities, including regarding any investment, tax, 
legal, financial, accounting, consulting or any other related service(s).

**Comment by enriquepiatti** [comment]
only one per day? but then how can I separate the different entry and close?
I mean, if I open and close a position 5 times in a day, this is normal in scalping, then how can I get them? I want to join the multiple trades/orders which belong to the same open position

**Comment by enriquepiatti** [comment]
OK, so the timestamp is always 12:00 UTC and we need to make one request for every day?

**Comment by bendelo** [comment]
Yes, and that request will return all the trades within the 24 hour period
and each amount realised from each trade.

On Sat, 20 Jun 2020 at 22:51, Enrique Piatti <notifications@github.com>
wrote:

> OK, so the timestamp is always 12:00 UTC and we need to make one request
> for every day?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_BitMEX_api-2Dconnectors_issues_441-23issuecomment-2D647005443&d=DwMCaQ&c=o2Rg2hCP31Es1DdrOYH75Q&r=XDW73b-_jvZBy7m5lDNX4Q&m=psDDbgawv_oe1RZqi7V_-ro2Nlqnyj1OZRpFAr-53wE&s=VZXcPXh9T3SulkEbPM9htUuWyZ_gGqeJ72tKuOmkRa0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABSAFS6ZAICAS7H6QHSJBR3RXTEIVANCNFSM4NM2THIA&d=DwMCaQ&c=o2Rg2hCP31Es1DdrOYH75Q&r=XDW73b-_jvZBy7m5lDNX4Q&m=psDDbgawv_oe1RZqi7V_-ro2Nlqnyj1OZRpFAr-53wE&s=w6sVRll7doO7SJ-VJgXqgwGhdC-Gc_D7FZJXTddHkCc&e=>
> .
>

-- 


This e-mail and all information in, attached to, or linked via this 
e-mail (together the ‘e-mail’) is confidential and may be legally 
privileged. It is intended solely for the intended addressee(s). Access to, 
or any onward transmission, of this e-mail by any other person is not 
authorised. If you are not the intended recipient, you are requested to 
immediately alert the sender of this e-mail and to immediately delete this 
e-mail. Any disclosure in any form of all or part of this e-mail, or of any 
the parties to it, including any copying, distribution or any action taken 
or omitted to be taken in reliance on it, is prohibited and may be 
unlawful. 




Transacting on BitMEX is not permitted for, or offered or 
available to, any person(s) located in or being resident(s) of (i) the 
United States of America or Québec (Canada). Additionally, transacting on 
BitMEX is not permitted for, or offered or available to, any person(s) 
located in or being resident(s) of (i) Cuba, Crimea and Sevastopol, Iran, 
Syria, North Korea, or Sudan, (ii) any other sanctioned jurisdiction, or 
(iii) any jurisdiction where the services offered by BitMEX are restricted. 





This e-mail is not, and is not intended to be, and should not be 
construed as being, (a) any offer, solicitation, or promotion of any kind; 
(b) the basis of any investment or other decision(s);  (c) any 
recommendation to buy, sell or transact in any manner any good(s), 
product(s) or service(s), nor engage in any investment(s) or other 
transaction(s) or activities;  or (d) the provision of, or related to, any 
advisory service(s) or activities, including regarding any investment, tax, 
legal, financial, accounting, consulting or any other related service(s).

**Comment by enriquepiatti** [comment]
that's a bit slow, I will probably need to make 365 requests just to get one year, but well, thanks for the clarification !
