### ISSUE TITLE
Socket Nodejs. what is the best way to see the position of 2 or more accounts in bitmex?

### ISSUE THREAD

**Issue by LukasHere** [BitMEX/api-connectors#447]
hello, to see the position of 2 accounts for example I need to open 2 client each in a different port? or is there a way to do this by opening only 1 client?
realtimemd , Multiplexing , would solve this problem? if it solves could someone give a simple example?

**Comment by STRML** [comment]
The easiest way to do this is to open multiple connections. The better way to do this, which will scale more easily, is to use the [multiplexing API](https://testnet.bitmex.com/app/wsAPI#Multiplexing).
