### ISSUE TITLE
Delays on python websocket

### ISSUE THREAD

**Issue by ian-collab** [BitMEX/api-connectors#449]
Place an order by Rest client

Move it in bitmex.com by hand

Check that order price every 2 seconds with the python ws object.

2 minutes until the updated price is reported.

Why might that be?

When I do this in Testnet, there is no delay.

**Comment by ian-collab** [comment]
Additionally, there is a 16 second delay between placing the order and the order being reported via the python websocket.

**Comment by ian-collab** [comment]
Sorted.
Don't use orderBookL2 in websocket.
Strange it looked okay except for order delay.

**Comment by Nijasio** [comment]
Hey @ian-collab I am facing the same latency issue. Can you be more especific on how to solve it? What do you mean by "do not use orderBookL2 in websocket"?
What I do is place an order by REST and then constantly ask for the active orders with WS, but there is a big delay untill I receive the real info.
