### ISSUE TITLE
How do I add a Keep-Alive connection to a BitMEX-Python-client?

### ISSUE THREAD

**Issue by andant7** [BitMEX/api-connectors#488]
**The manual says:**

"Our servers support HTTP Keep-Alive and cache SSL sessions. If you keep a connection alive, you will get websocket-like latency, obviating the need to use the websocket for transactional communication."

**What needs to be changed in this client to add Keep-Alive there?**
[https://github.com/BitMEX/api-connectors/tree/master/official-http/python-swaggerpy](https://github.com/BitMEX/api-connectors/tree/master/official-http/python-swaggerpy)

**Or does this client already have Keep-Alive?**

**Comment by STRML** [comment]
See https://bravado.readthedocs.io/en/stable/configuration.html#customizing-the-http-client for how you can add options. The docs for [requests](https://docs.python-requests.org/en/master/) say:

> Keep-alive and HTTP connection pooling are 100% automatic, thanks to urllib3.

So you should be fine. You can turn on debug logging to be sure.
