### ISSUE TITLE
nodejs/ws - can't run in the browser

### ISSUE THREAD

**Issue by Bomper** [BitMEX/api-connectors#52]
I wanted to build an alternative front-end for BitMEX with a few custom trading features (and get [free trading](https://blog.bitmex.com/free-trading-for-bitmex-integrations/)) but I can't get `bitmex-realtime-api` to work in the browser. Here's the webpack config:

```js
module.exports = {
  entry: './index.js',
  output: {
    filename: 'bundle.js',
  },
  node: {
    fs: 'empty',
  },
  devtool: 'source-map',
};
```

Webpack is missing modules (`bufferutil`, `utf-8-validate`) and adding separately them leads to "WARNING in ./node_modules/bindings/bindings.js - 81:22-40 Critical dependency: the request of a dependency is an expression"

In the browser console, I get

```
request.js:132 GET https://www.bitmex.com/realtime 426 (Upgrade Required)
ReconnectingSocket.js:90 WebSocket [ERROR]: Unexpected response from server [426]: Upgrade Required
ReconnectingSocket.js:85 WebSocket [INFO]: The WebSocket will terminate. Please manually reconnect.
```

and a CORS error,

```
Failed to load https://www.bitmex.com/api/v1/schema/websocketHelp: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 403.
```

followed by an exponential backoff trying to reconnect.

**Comment by STRML** [comment]
Yes; we don't serve CORS headers on the API as it could be potentially used to exfiltrate information using a logged-in session's cookies.

Don't worry about the bufferutil/utf-8-validate errors, those are common and don't affect the bundle. 

The 426 you're getting; you're making an HTTP request to /realtime when you should be using a `new WebSocket()` object. You may have to write a shim for the so that `ReconnectingSocket` loads the browser WebSocket and not the Node one (been down [this road before](https://github.com/websockets/ws/pull/661) - a [possible solution](https://github.com/websockets/ws/pull/1066#issuecomment-291912387)).

**Comment by STRML** [comment]
@Bomper That's not at all the way to address it. A shim can be written pretty easily. That ship sailed a long time ago. No need to mention a particular service or need whatsoever, and offering money makes no difference as it's not the code that needs to be written, it's agreement on whether or not it's `ws`'s job to provide a shim.

**Comment by Bomper** [comment]
Sorry, deleted my comment

**Comment by Bomper** [comment]
Using a new `WebSocket()` object as you suggested worked, and I wrote a minimalist in-browser client (only handles `insert` and `partial`, doesn't handle reconnecting). Maybe worth posting as a separate example since it's not library-quality?

```js
const ws = new WebSocket('wss://www.bitmex.com/realtime?subscribe=trade:XBTUSD');

ws.onopen = function wsOpenHanlder(event) {
  const nonce = Date.now();
  const signature = crypto.createHmac('sha256', bitmex.apiKeySecret).update('GET/realtime' + nonce).digest('hex');
  ws.send(JSON.stringify({ op: 'authKey', args: [bitmex.apiKeyID, nonce, signature] }));
  ws.send(JSON.stringify({ op: 'subscribe', args: ['execution'] }));
};

ws.onmessage = function wsMessageHandler(event) {
  const data = JSON.parse(event.data);
  if (!data || !data.data) return null;

  if (data.table === 'trade') {
    if (['insert', 'partial'].includes(data.action))
      return handleTrades(data.data);
    return console.error('Implement handling non-insert/partial trade messages with data:', data);
  }

  // Handle other table types...
}
```
