### ISSUE TITLE
Swagger spec on Testnet suddenly failing validation

### ISSUE THREAD

**Issue by chrism2671** [BitMEX/api-connectors#53]
As a follow up to https://github.com/BitMEX/api-connectors/issues/7

Code to reproduce (note I explicitly disable validation too) (bravado version 9.2.2):
```
from bravado.client import SwaggerClient
client = SwaggerClient.from_url('https://testnet.bitmex.com/api/explorer/swagger.json',
                                config={'validate_swagger_spec': False})
client.Quote.Quote_get(symbol='XBTUSD').result()

```
Seems to be OK on live, have there been some recent schema changes rolled out on testnet?

**Comment by STRML** [comment]
Thanks @chrism2671. I've fixed the bug in Testnet and introduced independent swagger.json validation into our test suite so we'll fail the build if the autogenerated spec doesn't validate. The updated JSON will hit Testnet in just a few minutes
