### ISSUE TITLE
How can i pass count parameter to below code to get 15 object 

### ISSUE THREAD

**Issue by sutharkiran** [BitMEX/api-connectors#59]

**Comment by sutharkiran** [comment]
hello
Please can you give me modified that contain "count" and "startTime" and "endTime" parameter. because i don't know much more about nodejs syntax .

**Comment by bendelo** [comment]
What 'below code'?

**Comment by sutharkiran** [comment]
This code of Node Js example.js file I want add "count" parameter that give me only 15 object result. what i have to modify to below code and index.js file

`client.addStream('XBTUSD','quote',function(data, symbol, table) {  	
	console.log(data.slice(0, 15));
});`

**Comment by bendelo** [comment]
That is a realtime feed, if you want historical data you will have to use the REST API.

**Comment by sutharkiran** [comment]
can you know about which api i have to use for find RSI means which api and which parameter

**Comment by sutharkiran** [comment]
i have found some solution from bitmex they give me instrument,quote api to find RSI

**Comment by bendelo** [comment]
https://www.bitmex.com/api/explorer/#/Quote
