### ISSUE TITLE
Unable to connect clientAuthorizations

### ISSUE THREAD

**Issue by leoplct** [BitMEX/api-connectors#60]
I am getting this error when I connect with APikey/secret.
**Unable to connect: TypeError: Cannot read property 'add' of undefined**

```js
'use strict';
var SwaggerClient = require("swagger-client");
var _ = require('lodash');
var BitMEXAPIKeyAuthorization = require('./lib/BitMEXAPIKeyAuthorization');

require('dotenv').config();

new SwaggerClient({
  // Switch this to `www.bitmex.com` when you're ready to try it out for real.
  // Don't forget the `www`!
  url: 'https://testnet.bitmex.com/api/explorer/swagger.json',
  usePromise: true
})
.then(function(client) {
  //console.log(client);
  // Comment out if you're not requesting any user data.
  client.clientAuthorizations.add("apiKey", new BitMEXAPIKeyAuthorization(process.env.BITMEX_API_KEY, process.env.BITMEX_API_SECRET));

  // Print client capabilities
  //

})
.catch(function(e) {
  console.error("Unable to connect:", e);
})



```

**Comment by andersea** [comment]
Halt the script on this line in your debugger:

    client.clientAuthorizations.add("apiKey", new BitMEXAPIKeyAuthorization(process.env.BITMEX_API_KEY, process.env.BITMEX_API_SECRET));

Inspect the client variable. Does it have an object 'clientAuthorizations'?

**Comment by ryanfox** [comment]
This sounds like it might be an installation issue. You might try re-installing the `swagger-client` module. Are there any steps you go through to reproduce the problem?
