### ISSUE TITLE
api-connectors/official-http/node-request/index.js

### ISSUE THREAD

**Issue by pabx06** [BitMEX/api-connectors#62]
example not working:

`{"error":{"message":"Invalid API Key.","name":"HTTPError"}}`

**Comment by bendelo** [comment]
Have you considered using a valid API key?

**Comment by pabx06** [comment]
Hello. Thanks for reply. I have used a fresh valid api key with orders
available.

**Comment by pabx06** [comment]
This is the key i used in the example
