### ISSUE TITLE
c# client - don't use

### ISSUE THREAD

**Issue by cemdev** [BitMEX/api-connectors#63]
This client is awful. I'll save you some time now, because I wish someone had for me. The authentication doesn't work because they've done it in a way where the parameters can be reordered so you can sign the message properly without rewriting every. single. function. And the functions are terrible. So much code duplication it's embarrassing.

And despite the readme promising a websocket client -there isn't one. 

Just don't use the autogenned swagger library at all, it's actually horrific. Code from scratch using the actual bitmex c# client.  (not the autogenned c# client)

**Comment by joggerjoel** [comment]
I wrote mine in java connecting to wss. I’ve recorded close to half month
with little dropping. If anyone want to send me eth/btc,  then I can assist.

**Comment by STRML** [comment]
The code is autogenerated. Expect duplication because it's literally generated from a template. If you think the template is wrong or has bugs please contribute to https://github.com/swagger-api/swagger-codegen.
