### ISSUE TITLE
WS API: Being able to differentiate between insert / update / delete messages for different filter values (symbols)

### ISSUE THREAD

**Issue by Palmik** [BitMEX/api-connectors#67]
The partial message has "filter" message attached, but the "insert", "update" and "delete" messages don't. This means one has to assume that "insert", "update" and "delete" has non-empty data to be able to extract the symbol. This still does not address filtering by account though.

**Comment by ryanfox** [comment]
You can use [multiplexing](https://testnet.bitmex.com/app/wsAPI#Multiplexing) to stream multiple accounts on the same connection.
