### ISSUE TITLE
official nodejs client for bitmex

### ISSUE THREAD

**Issue by adityamertia** [BitMEX/api-connectors#68]
Is there an official nodejs client for bitmex apart from the autogenerated swagger based one?
How do people use bitmex APIs till date in nodejs?

**Comment by pabx06** [comment]
https://github.com/BitMEX/api-connectors/tree/master/official-ws/nodejs

i use websocket to get a  stream price then restfull api for orders placement

**Comment by adityamertia** [comment]
@pabx06 This is for websocket. What about REST API clients. Mostly i see swagger autogenerated clients which do not work and some reference sample code. Nothing like official client from bitmex. Am i missing something ?

**Comment by pabx06** [comment]
i am done with bitmex too much nerve wreaking getting 50% of the time today server "Overloaded response from API".
as a result could not exit a trade whenever you want is a bit too much for my nerves.
have my desktop ip banned at their firewall & my server API key banned.

you cant have more than 140 limit order to exit or enter gradualy either ...

too much of headache and unhealthy for me ...

i also suspect the swagger thing to be outdated ... 
you want ever be able to figure out what are the meaning of their gazillions filied in their api responses like new execution unless you had a background in the FIX protocol FIX is a brain fuck protocol

**Comment by tanmaykumar** [comment]
@pabx06 Did your IP get banned because of too many requests during a time the server was overloaded? You can just add a sleep time of 0.5 seconds if you receive a 503 response and then try again. At least you won't get banned.

**Comment by STRML** [comment]
@pabx06 Keep on topic - your complaint about hitting ratelimits is not relevant to this discussion or even correct. As was already explained to you through another channel, you must use this API responsibly and pay attention to return codes and errors. Ignoring them and continuing to generate errors will get you banned from any decent API on the planet.

**Comment by adityamertia** [comment]
@tanmaykumar @STRML @pabx06 Can we stick to the core issue? I still do not have answer to it.

**Comment by STRML** [comment]
Yes @adityamertia: See the `official-http` and `official-ws` folders in the root, both of which have Node connectors. They are starting points and you can work from there. There is also a sample market making bot at https://github.com/BitMEX/sample-market-maker/.

**Comment by adityamertia** [comment]
Thanks @STRML. This sample market maker bot does support all APIs of bitmex? Is it as close i can get to the official REST client? Is there a nodejs version of the market maker bot?

**Comment by STRML** [comment]
That is for specific market making functionality only. Please see the
Readme of each project. There is not yet a nodejs market making sample.

On Jan 18, 2018 9:16 AM, "Aditya Mertia" <notifications@github.com> wrote:

Thanks @STRML <https://github.com/strml>. This sample market maker bot does
support all APIs of bitmex? Is it as close i can get to the official REST
client? Is there a nodejs version of the market maker bot?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/BitMEX/api-connectors/issues/68#issuecomment-358677676>,
or mute the thread

**Comment by IlanFrumer** [comment]
A new API connector
https://github.com/IlanFrumer/BitMEX-nodejs
