### ISSUE TITLE
Python 2 `ImportError: No module named parse`

### ISSUE THREAD

**Issue by scopelf** [BitMEX/api-connectors#69]
Please update the imports in `/BitMEXAPIKeyAuthenticator.py` and change line 57 to `parsedURL = urlparse(url)` to assure that there is no `ImportError: No module named parse` when importing bitmex in python 2. The following code works for python 2 and 3.
```
try:
    from urllib.parse import urlparse
except ImportError:
     from urlparse import urlparse
```
For a problem description see: [Stackoverflow](https://stackoverflow.com/questions/29358403/no-module-named-urllib-parse-how-should-i-install-it)

Or since you are using `six`:
```
from six.moves.urllib.parse import urlparse
```

**Comment by ryanfox** [comment]
Python 2 is not going to be supported going forward.
