### ISSUE TITLE
How to close a position?

### ISSUE THREAD

**Issue by miguelwon** [BitMEX/api-connectors#75]
I can't close the position with python connector. 
The order is sent correctly with: 

`client.Order.Order_new(symbol='XBTUSD', ordType = 'Market', orderQty=-10).result()`

and closing with 

`client.Order.Order_new(symbol='XBTUSD',ordType = 'Market',execInst ='Close')`

I'm trying Order_new to close because documentation says closePosition is deprecated.

**Comment by ryanfox** [comment]
Calling `result()` is what actually sends the order: `client.Order.Order_new(symbol='XBTUSD',ordType = 'Market',execInst ='Close').result()`

**Comment by miguelwon** [comment]
Ah, ok. Thanks. It's working now.

**Comment by icehongssii** [comment]
@ryanfox 
Hi, just wondering about new param for order to cancel 
data = {symbol:"ETHUSD",execInst:"Close", price:100}

It seems ok but got  "Access denied, HttpError" from bitmex.
