### ISSUE TITLE
official-ws/python bugs

### ISSUE THREAD

**Issue by EUA** [BitMEX/api-connectors#81]
on Python 3.6,
It doesn't make any authentication if api keys are provided because 
stuck on **__wait_for_account(self):**
what if account doesn't have any 'order' ?
Better to remove it and leave only 'margin' key for wait

Also on line 220:
self.data[table] = self.data[table][(BitMEXWebsocket.MAX_TABLE_LEN / 2):]
generates too much error due not being integer. Fix it by
self.data[table] = self.data[table][**int**(BitMEXWebsocket.MAX_TABLE_LEN / 2):]

Also missing buy/sell commands. Does it hard to implement those?? :(

**Comment by ryanfox** [comment]
`__wait_for_account()`: an account having no orders should not be a problem. The method will still exit once your account data is streamed to the client.

Line 220: this is already fixed. Try installing `bitmex-ws` via pip or using branch `python-dev`.

The websocket API does not support placing orders. [See the API documentation](https://testnet.bitmex.com/app/restAPI) or use the official-http python connector for those.

**Comment by EUA** [comment]
It streamed but it doesn't return.
In my scenario; since "account has no order",  self.data["order"] not created and __wait_for_account() not returns due waiting creation of self.data["order"]...
Thanks.

**Comment by ryanfox** [comment]
When an account has no orders, an empty list is returned. That is enough to return from `__wait_for_account`. Have you modified the code to change message handling?
