### ISSUE TITLE
Order_cancelAll correct syntax?

### ISSUE THREAD

**Issue by dannyuan** [BitMEX/api-connectors#82]
```
import json
import bitmex
postdict = [{
    'symbol': 'XBTUSD'
}]

client = bitmex.bitmex(test = False, api_key=<>, api_secret=<>)

json_dump = json.dumps(postdict)
result = client.Order.Order_cancelAll(symbol=json_dump).result()

```
and I am getting :

`HTTPBadRequest: 400 Bad Request: {'error': {'message': 'Unknown or expired symbol.', 'name': 'ValidationError'}}`

I also tried

`result = client.Order.Order_cancelAll().result()
`
and I get 

SwaggerMappingError: Expected dict like type for <class 'list'>:

Where can I find more documentation on this? What should I fix to get it working?

**Comment by dannyuan** [comment]
when I try 
client.Order.Order_cancelAll(symbol='XBTUSD').result()

SwaggerMappingError: Expected dict like type for <class 'list'>:[]

**Comment by ryanfox** [comment]
That appears to be an error validating the response - check whether the orders were actually canceled.

**Comment by STRML** [comment]
We'll be pushing an update shortly to fix the Swagger definition for this.

**Comment by bendelo** [comment]
You're sending `symbol= json_dump` and `[{'symbol': 'XBTUSD'}]` is not a valid symbol itself.

**Comment by dannyuan** [comment]
What should be the symbol for XBTUSD?

**Comment by bendelo** [comment]
XBTUSD
