### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by pigslayer12** [BitMEX/api-connectors#84]
Hello,

I am having a problem with getting ticker data using the websocket. It works fine for a minute and then spits out this error around 50% of the time. I am using windows 10 with pycharm (if it matters)

`2018-02-09 13:48:32,612 - bitmex_websocket - ERROR - Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\bitmex_websocket.py", line 217, in __on_message
    self.data[table] = self.data[table][(BitMEXWebsocket.MAX_TABLE_LEN / 2):]
TypeError: slice indices must be integers or None or have an __index__ method`

After looking through other recent issues, this should have been fixed in version 0.3, which I have. Am I doing something wrong? I am just trying to run the example file in main.py

Also I have tried it with and without authentication with my api keys, with the same result. Also the longer I let it run, the more often the error pops up instead of the ticker data I want.

Thanks for the help

**Comment by pigslayer12** [comment]
i was able to fix it by changing line 217 (thanks to the guy who mentioned it)

self.data[table] = self.data[table][(BitMEXWebsocket.MAX_TABLE_LEN / 2):]

changed to
self.data[table] = self.data[table][(int(BitMEXWebsocket.MAX_TABLE_LEN / 2)):]

**Comment by ryanfox** [comment]
Good catch, thanks. Should be fixed if you upgrade to v0.3.1.
