### ISSUE TITLE
Differentiating between 'opened' and 'closed' orders

### ISSUE THREAD

**Issue by TomOerlemans** [BitMEX/api-connectors#87]
I am trying to collect recent (public) trades, and then distinguish between opened and closed orders. However, it seems this is impossible. Is there any other solution/hack through which I can obtain/infer this data?

Example of an open order and closed order:

**Open long**
{'grossValue': 11593, 'tickDirection': 'ZeroPlusTick', 'size': 1, 'timestamp': '2018-02-10T11:50:46.399Z', 'foreignNotional': 1, 'trdMatchID': 'd77662e1-0af4-421b-c31f-3cdf781869a', 'symbol': 'XBTUSD', 'side': 'Buy', 'price': 8626, 'homeNotional': 0.00011593}

**Close long**
{'grossValue': 11593, 'tickDirection': 'ZeroPlusTick', 'size': 1, 'timestamp': '2018-02-10T11:50:59.271Z', 'foreignNotional': 1, 'trdMatchID': 'c8b372c1-c721-50ab-9129-eb097acaa62', 'symbol': 'XBTUSD', 'side': 'Buy', 'price': 8626, 'homeNotional': 0.00011593}

**Comment by bendelo** [comment]
Subscribe to the `instrument` and look at the `openInterest` field to work this out.

**Comment by TomOerlemans** [comment]
I am sorry but I can't seem to figure it out. Could you explain what you mean in more detail?

I have tried relating the data from ``instrument`` and ``trade``, but the lack of indexes makes this rather difficult. I tried using the timestamps and pricing information to match the data, but there seem to be too many inconsistencies in the data to make this work properly. Also, data from ``openInterest`` seems to be updated periodically, which would make determining which trades specifically opened/closed impossible.

**Comment by bendelo** [comment]
We do not publish information about whether a trade is opening or closing a position. The closest you can get is looking at `openInterest` which is published every 5 seconds and see if has increased (opening long and short), decreased (closing long and short) or stayed the same (opening long and closing short, or opening short and closing long).
