### ISSUE TITLE
Node.js: example not working

### ISSUE THREAD

**Issue by Vladimir37** [BitMEX/api-connectors#9]
I'm trying to run an example from "official-http/node-swagger" inserting the valid API key, but get an error in console:
`Unable to connect: [TypeError: Cannot read property 'add' of undefined]`
The error applies to this line:
`client.clientAuthorizations.add("apiKey", new BitMEXAPIKeyAuthorization(key, secret));`
Getting an object "client" is normal, but there is no parameter `clientAuthorizations`.
What could be the problem?

**Comment by Phaethon-net** [comment]
*bump*
I'm having the same problem

**Comment by ko0f** [comment]
Code is not up to date, this somewhat works - but I get `Error: Unauthorized` when trying to send a command... not sure if that's the authentication's fault or another reason.

```
const
         SwaggerClient = require("swagger-client"),
         BitMEXAPIKeyAuthorization = require('../../lib/BitMEXAPIKeyAuthorization');

      new SwaggerClient('https://www.bitmex.com/api/explorer/swagger.json', {
         authorizations: {
            apiKey: new BitMEXAPIKeyAuthorization(apiKey, apiSecret)
         }
      })
         .then(function(_client) {
            // inspect(_client.apis);
            logger.info('Connected to BitMEX REST API.');
            callback(_client);
         })
         .catch(function(e) {
            logger.error("Unable to connect to BitMEX through Swagger:", e);
         });
```

**Comment by ryanfox** [comment]
After adding a valid API key and secret, swaggerClient.js runs successfully for me - is this still an issue? One possible gotcha is making sure your API key is for testnet or www as appropriate.
