### ISSUE TITLE
api_connectors python Order.Order_newBulk TypeError: __call__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by Krsnadeva** [BitMEX/api-connectors#90]
Hello all!
I was sending orders one at a time (TP and SL) but now I am trying to send in bulk and getting the following error:
`TypeError: __call__() takes 1 positional argument but 2 were given`
for:
`bulk_response = self.bmx.Order.Order_newBulk(bulk_orders).result()`
where:
```
        bulk_orders = [{'symbol': self.symbol,
                        'clOrdID': tp_sl_clOrdID,
                        'clOrdLinkID': tp_sl_clOrdID,
                        'orderQty': -amount,
                        'price': sl,
                        'stopPx': sl_trig,
                        'ordType': 'StopLimit',
                        'execInst': 'LastPrice',
                        'contingencyType': 'OneCancelsTheOther',
                        'text': 'Stop Loss'},
                       {'symbol': self.symbol,
                        'clOrdID': tp_sl_clOrdID,
                        'clOrdLinkID': tp_sl_clOrdID,
                        'orderQty': -amount,
                        'price': tp,
                        'stopPx': tp_trig,
                        'ordType': 'LimitIfTouched',
                        'execInst': 'LastPrice',
                        'contingencyType': 'OneCancelsTheOther',
                        'text': 'Take Profit'}]

```
The 'one at a time' approach was working but started to fail, only one of the TP/SL entered (_edit: I figure this part out '**clOrdID': tp_sl_clOrdID**, was the same on both orders, so I got bad request error, could that be the cause for the bulk error as well?, seems not._) , and this new approach is giving me the above error, am I using the correct syntax?
Please advise.
tks in advance. Cheers!

**Comment by johnprolucid** [comment]
I am having the same problem executing a short with a trailing stop.  Any advice here?

```
bulk_orders = [ { "symbol='XBTUSD', orderQty='-100', ordType='Market'" }, { "symbol='XBTUSD', orderQty='100', ordType='Stop', pegOffsetValue='20', pegPriceType='TrailingStopPeg', execInst='LastPrice'" } ]
output = client.Order.Order_newBulk(bulk_orders).result()
```

TypeError: __call__() takes 1 positional argument but 2 were given

**Comment by scoupafi** [comment]
A list of dictionaries is not JSON.
Make sure you call it like:
import json
`bulk_response = self.bmx.Order.Order_newBulk(json.dump(bulk_orders)).result()`

**Comment by johnprolucid** [comment]
Thank you scoupafi.  The Documentation just said Order_newBulk needed an "Array" - and didn't specify how it is to be formatted and didn't provide an example.  I'm getting a little further, but now I'm getting a different error.  This code:

`import bitmex
import json

apiKey='snip'
apiSecret='snip'

client = bitmex.bitmex()
client = bitmex.bitmex(test=True, api_key=apiKey, api_secret=apiSecret)

bulk_orders = [
{
  "symbol": "XBTUSD",
  "orderQty": "-1",
  "ordType": "Market"
},
{
  "symbol": "XBTUSD",
  "orderQty": "-100",
  "ordType": "Stop" ,
  "pegOffsetValue": "20",
  "pegPriceType": "TrailingStopPeg",
  "execInst": "LastPrice"
}]

output = client.Order.Order_newBulk(json.dump(bulk_orders)).result()
print(output)
print(output[1].headers)
`
yields this error:
`TypeError: dump() missing 1 required positional argument: 'fp'`

Using Python 3.5.2, any more ideas?  Thanks!

**Comment by johnprolucid** [comment]
I believe json.dump is only meant to use with a file object (that's why it's looking for fp / file pointer).  I also tried json.dumps (meant for use with strings) and that produces the same error as previously encountered:

TypeError: __call__() takes 1 positional argument but 2 were given

**Comment by ryanfox** [comment]
Specify the parameter name: `Order_newBulk(orders=json.dump(bulk_orders))`
