### ISSUE TITLE
signature not valid error php

### ISSUE THREAD

**Issue by sureimwinner** [BitMEX/api-connectors#92]
while creating a php bot i'm facing this error "signatute not valid"
and php documentation is not avilable on site. here is the code i'm using

$apiKey = "L5kwGvrsX-3FFsPtpO4jhXu9";
        $apiSecret = "OCFCnv6M2jbz-S9vioj5Ytoyjyk5dPyrkY87ecmUDh74F_6V";
        $expires = strtotime("+1 minutes");
        $verb = "POST";
        $path ="/api/v1/order";
        $data = array('symbol' => 'XBTUSD','side'=>'Buy','orderQty'=>'100','ordType'=>'Market','timeInForce'=>'GoodTillCancel');
        $data_json = json_encode($data);
        $string = $verb.$path.(string)$expires.$data_json;
        $sign = bin2hex(hash_hmac('sha256', $string, $apiSecret)); 
        $ch = curl_init();
        
        curl_setopt($ch, CURLOPT_HTTPHEADER,array(
   "Content-Type : application/x-www-form-urlencoded",
   "Accept : application/json",
  "X-Requested-With: XMLHttpRequest",
  "api-expires:".$expires,
  "api-key: ".$apiKey,
  "api-signature:".$sign
));
        curl_setopt($ch, CURLOPT_VERBOSE, true);
        curl_setopt($ch, CURLOPT_URL,"https://testnet.bitmex.com/api/v1/order");
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS,
                    $data);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $server_output = curl_exec ($ch);
        $information = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        print_r($information);
        print_r($server_output);
        curl_close ($ch);

**Comment by wilsonba** [comment]
+1

**Comment by ryanfox** [comment]
At a minimum, you should delete that API key, as the key and secret is now public.

Also, you do not need to be calling curl, you can invoke the library methods directly. For example,

    $api_instance->aPIKeyDisable($api_key_id);

As for signing messages, [see the documentation here](https://testnet.bitmex.com/app/apiKeysUsage#Authenticating-with-an-API-Key) for authenticating with an API key.

**Comment by tghilardi** [comment]
Any updates on this? I get the same message myself.

`$BitmexAPI_ID = "xxx";
$BitmexAPI_Secret = "xxx";

$url = 'https://www.bitmex.com/api/v1/execution/tradeHistory?count=100&reverse=false';
$verb = 'GET';
$path = '/api/v1/execution/tradeHistory?count=100&reverse=false';
$data = '';
$expires = '1663891200';
$sign = hash_hmac('sha256', $verb.$path.$expires.$data, $BitmexAPI_Secret);

$fetch = curl_init();
curl_setopt($fetch, CURLOPT_HTTPHEADER, array('api-signature: '.$sign, 'api-key: '.$BitmexAPI_ID, 'api-expires: '.$expires));
curl_setopt($fetch, CURLOPT_URL, $url);
curl_setopt($fetch, CURLOPT_POST, true);
curl_setopt($fetch, CURLOPT_SSL_VERIFYPEER , true);
curl_setopt($fetch, CURLOPT_RETURNTRANSFER, true);
echo "sign: $sign";
echo curl_exec($fetch);`
