### ISSUE TITLE
Official adapters have larger latency than browser

### ISSUE THREAD

**Issue by exceeddream** [BitMEX/api-connectors#93]
I have tried BitMEX Delta Server, NodeJS adapter and Python adapter. The trading datas in all the official adapters have larger latency than in browser (Chrome).  The trading datas in Chrome proximately are ahead of 2s~15s.

I found that the trading datas from official adapters are also litter different from the datas in browser.  For example the data in browser maybe: price: 10000, qty:200;price: 10000, qty:800; In  official adapters, the data maybe price: 10000, qty:1000. The trading datas in official adapters are aggregated sometimes.

I tested many times getting the above results which are stable. I suppose it's a general problem. 

What are the reasons cause these differents? 
How could I get really realtime trading datas which are not behind the browser?

**Comment by bendelo** [comment]
The browser and the adapters connect to the same WebSocket endpoint. Also none of our feeds have a `qty` field, so I am not sure what you are looking at.
