### ISSUE TITLE
about a 429 issue 

### ISSUE THREAD

**Issue by soultrain23** [BitMEX/api-connectors#95]
now im banned by bitmex market maker cuz of too many request (429 response)
defitinit;ly it is becuz of order request. My market maker is very simple. only set leverage and placing order are only i request.
but i only use bulk order(20~100 buy orders) and wait for 15 (using time.sleep 15 sec)

BITMEX said it is too many request. as i know this is only one request if i use bulk order.
am i wrong? any misunderstanding something?

i guess there was DDOS to korean sever. now BITMEX are changing or changed Policy about a request and u guys not notify yet.
this issue happenend after DDOS

if i misunderstand something plz let me know.

**Comment by soultrain23** [comment]
each orders are OVER 0.0025 XBT !!!!!

**Comment by ryanfox** [comment]
See [the BitMEX documentation](https://testnet.bitmex.com/app/restAPI#Limits) for information on rate limits.
