### ISSUE TITLE
How to respond to 403 Forbidden?

### ISSUE THREAD

**Issue by cryptomite17** [BitMEX/api-connectors#96]
I am getting this error and it seems to want some sort of response. What's the proper way to respond to this?

403 Forbidden: Response specification matching http status_code 403 not found for operation Operation(Order_amendBulk). Either add a response specification for the status_code or use a `default` response.

**Comment by scoupafi** [comment]
This error usually comes up if you've been IP banned due to a lot of 4xx or 5xx results of your requests. 
Refer to https://www.bitmex.com/app/restAPI#Limits for more information.

**Comment by ryanfox** [comment]
Can you perform other authenticated requests? Make sure you specify a valid `api_key` and `api_secret` when you create the `bitmex` object.

**Comment by zc4049** [comment]
@ryanfox you are right! i have verify it !

**Comment by zc4049** [comment]
but now it can't work

**Comment by beeflowers287** [comment]
> Can you perform other authenticated requests? Make sure you specify a valid `api_key` and `api_secret` when you create the `bitmex` object.

> as workaround, i am using OrderBook/L2

The #BitMEX API is fragmented at best, verging on broken. You can barely get a public price quote (they turned off that endpoint sometime in 2018) so I wanted to share an all in one I've hacked together from their api over the past 6 months for CT and my sanity:

1/ Price
Work around to get the current price is using another endpoint. orderBook/L2 python:

```
import requests, json
response = requests.get("https://www.bitmex.com/api/v1/orderBook/L2?symbol=eth&depth=1 …").json()
ether_bid_price = response[1]['price']
```

2/ Everything else
Digging thru the open Issues of the bitmex github repo this is the best resource I found to help you place/ammend/cancel orders without downloading their sorry excuse sample market maker bot: https://github.com/mazmex7/BitMEX-API-python … 
Thank you @mazmex7
