### ISSUE TITLE
Unable to know if I can withdraw using API

### ISSUE THREAD

**Issue by koushik72** [BitMEX/api-connectors#97]
Hi, I want to check if I can place an order and withdraw using the API and I can't find any way to do that.
I check the user model and I didn't see anything that indicates if I can order or withdraw or not.
Is there any way to do that?
This was the response in user model-
`{
    "id": 'hidden',
    "ownerId": null,
    "firstname": "Koushik",
    "lastname": "Das",
    "username": "hidden",
    "email": "hidden",
    "phone": null,
    "created": "2018-03-11T11:34:16.215Z",
    "lastUpdated": "2018-03-11T14:33:56.146Z",
    "preferences": {
        "colorTheme": "dark",
        "hideFromLeaderboard": false,
        "hideNameFromLeaderboard": true,
        "locale": "en-US",
        "orderClearImmediate": false,
        "showLocaleNumbers": true,
        "strictIPCheck": false,
        "strictTimeout": true
    },
    "TFAEnabled": "GA",
    "affiliateID": "KN65t5",
    "pgpPubKey": null,
    "country": "IN",
    "roles": []
}`
Thank you.

**Comment by scoupafi** [comment]
Check https://www.bitmex.com/api/explorer/#!/User/User_requestWithdrawal

**Comment by ryanfox** [comment]
Order and withdrawal permissions are per-API key. You can get a list of your API keys and their permissions via `/apiKey`.

**Comment by kodmanyagha** [comment]
when withdraw you must specify amount as satoshi and its type is integer. don't forget this.
