### ISSUE TITLE
Broken paths to auto-generated clients in README.md

### ISSUE THREAD

**Issue by angyvolin** [BitMEX/api-connectors#99]
Paths to auto-generated clients were broken in https://github.com/BitMEX/api-connectors/commit/58f7373fc7a27b9d131453a778b080845a4aaf6b

See https://github.com/BitMEX/api-connectors/pull/98

**Comment by ryanfox** [comment]
This is already fixed in 5a5fae59d08e5e653db2cb5fc38b8ab7d07bcfd8. Thanks.
